--- 
title: "Validation of Superpower"
author: "Aaron Caldwell & Dani&euml;l Lakens"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

This is a compilation of validation documents for `Superpower` written in **Markdown** and compiled by **Bookdown**.



```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

# Introduction

Below we have included various examples of the performance of `Superpower` against other R packages and statistical programs (such as GPower).

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
nsims <- 100 #set number of simulations
require(mvtnorm, quietly = TRUE)
require(MASS, quietly = TRUE)
require(afex, quietly = TRUE)
require(emmeans, quietly = TRUE)
require(ggplot2, quietly = TRUE)
require(gridExtra, quietly = TRUE)
require(reshape2, quietly = TRUE)
require(pwr, quietly = TRUE)
library(lsr)
# Install functions from GitHub by running the code below:
library(Superpower)
```