<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 One-way ANOVA Part 1 | Validation of Superpower</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.10 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 One-way ANOVA Part 1 | Validation of Superpower" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 One-way ANOVA Part 1 | Validation of Superpower" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Aaron Caldwell &amp; Daniël Lakens" />


<meta name="date" content="2019-09-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html">
<link rel="next" href="one-way-anova-part-2.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> One-way ANOVA Part 1</a><ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#validation-of-power-in-one-way-anova"><i class="fa fa-check"></i><b>2.1</b> Validation of Power in One-Way ANOVA</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#two-conditions"><i class="fa fa-check"></i><b>2.2</b> Two conditions</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="one-way-anova-part-2.html"><a href="one-way-anova-part-2.html"><i class="fa fa-check"></i><b>3</b> One-way ANOVA Part 2</a><ul>
<li class="chapter" data-level="3.1" data-path="one-way-anova-part-2.html"><a href="one-way-anova-part-2.html#validation-of-power-in-one-way-anova-with-brysbaert-example"><i class="fa fa-check"></i><b>3.1</b> Validation of Power in One-Way ANOVA with Brysbaert example</a><ul>
<li class="chapter" data-level="3.1.1" data-path="one-way-anova-part-2.html"><a href="one-way-anova-part-2.html#three-conditions"><i class="fa fa-check"></i><b>3.1.1</b> Three conditions</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="one-way-anova-part-2.html"><a href="one-way-anova-part-2.html#power-for-simple-effects"><i class="fa fa-check"></i><b>3.2</b> Power for simple effects</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="one-way-anova-part-3.html"><a href="one-way-anova-part-3.html"><i class="fa fa-check"></i><b>4</b> One-way ANOVA Part 3</a><ul>
<li class="chapter" data-level="4.1" data-path="one-way-anova-part-3.html"><a href="one-way-anova-part-3.html#three-conditions-replication"><i class="fa fa-check"></i><b>4.1</b> Three conditions replication</a></li>
<li class="chapter" data-level="4.2" data-path="one-way-anova-part-3.html"><a href="one-way-anova-part-3.html#variation-1"><i class="fa fa-check"></i><b>4.2</b> Variation 1</a></li>
<li class="chapter" data-level="4.3" data-path="one-way-anova-part-3.html"><a href="one-way-anova-part-3.html#three-conditions-replication-1"><i class="fa fa-check"></i><b>4.3</b> Three conditions replication</a></li>
<li class="chapter" data-level="4.4" data-path="one-way-anova-part-3.html"><a href="one-way-anova-part-3.html#variation-2"><i class="fa fa-check"></i><b>4.4</b> Variation 2</a></li>
<li class="chapter" data-level="4.5" data-path="one-way-anova-part-3.html"><a href="one-way-anova-part-3.html#three-conditions-replication-2"><i class="fa fa-check"></i><b>4.5</b> Three conditions replication</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="repeated-measures-anova-part-1.html"><a href="repeated-measures-anova-part-1.html"><i class="fa fa-check"></i><b>5</b> Repeated Measures-ANOVA Part 1</a><ul>
<li class="chapter" data-level="5.1" data-path="repeated-measures-anova-part-1.html"><a href="repeated-measures-anova-part-1.html#two-conditions-medium-effect-size"><i class="fa fa-check"></i><b>5.1</b> Two conditions, medium effect size</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="repeated-measures-anova-part-2.html"><a href="repeated-measures-anova-part-2.html"><i class="fa fa-check"></i><b>6</b> Repeated Measures-ANOVA Part 2</a><ul>
<li class="chapter" data-level="6.1" data-path="repeated-measures-anova-part-2.html"><a href="repeated-measures-anova-part-2.html#the-relation-between-cohens-f-and-cohens-d"><i class="fa fa-check"></i><b>6.1</b> The relation between Cohen’s f and Cohen’s d</a></li>
<li class="chapter" data-level="6.2" data-path="repeated-measures-anova-part-2.html"><a href="repeated-measures-anova-part-2.html#three-within-conditions-medium-effect-size"><i class="fa fa-check"></i><b>6.2</b> Three within conditions, medium effect size</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="repeated-measures-anova-part-3.html"><a href="repeated-measures-anova-part-3.html"><i class="fa fa-check"></i><b>7</b> Repeated Measures-ANOVA Part 3</a><ul>
<li class="chapter" data-level="7.1" data-path="repeated-measures-anova-part-3.html"><a href="repeated-measures-anova-part-3.html#reproducing-brysbaert"><i class="fa fa-check"></i><b>7.1</b> Reproducing Brysbaert</a></li>
<li class="chapter" data-level="7.2" data-path="repeated-measures-anova-part-3.html"><a href="repeated-measures-anova-part-3.html#reproducing-brysbaert-variation-1-changing-correlation"><i class="fa fa-check"></i><b>7.2</b> Reproducing Brysbaert Variation 1 Changing Correlation</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="mixed-anova-part-1.html"><a href="mixed-anova-part-1.html"><i class="fa fa-check"></i><b>8</b> Mixed ANOVA Part 1</a><ul>
<li class="chapter" data-level="8.1" data-path="mixed-anova-part-1.html"><a href="mixed-anova-part-1.html#two-by-two-anova-within-between-design"><i class="fa fa-check"></i><b>8.1</b> Two by two ANOVA, within-between design</a></li>
<li class="chapter" data-level="8.2" data-path="mixed-anova-part-1.html"><a href="mixed-anova-part-1.html#two-by-two-anova-within-between-design-variation-1"><i class="fa fa-check"></i><b>8.2</b> Two by two ANOVA, within-between design Variation 1</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="mixed-anova-part-2.html"><a href="mixed-anova-part-2.html"><i class="fa fa-check"></i><b>9</b> Mixed ANOVA Part 2</a><ul>
<li class="chapter" data-level="9.1" data-path="mixed-anova-part-2.html"><a href="mixed-anova-part-2.html#two-by-two-anova-within-within-design"><i class="fa fa-check"></i><b>9.1</b> Two by two ANOVA, within-within design</a></li>
<li class="chapter" data-level="9.2" data-path="mixed-anova-part-2.html"><a href="mixed-anova-part-2.html#examine-variation-of-means-and-correlation"><i class="fa fa-check"></i><b>9.2</b> Examine variation of means and correlation</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="mixed-anova-part-3.html"><a href="mixed-anova-part-3.html"><i class="fa fa-check"></i><b>10</b> Mixed ANOVA Part 3</a><ul>
<li class="chapter" data-level="10.1" data-path="mixed-anova-part-3.html"><a href="mixed-anova-part-3.html#two-by-two-anova-within-design"><i class="fa fa-check"></i><b>10.1</b> Two by two ANOVA, within design</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="simple-example-2x2-within-design.html"><a href="simple-example-2x2-within-design.html"><i class="fa fa-check"></i><b>11</b> Simple example: 2x2 within design</a></li>
<li class="chapter" data-level="12" data-path="error-control-in-exploratory-anova.html"><a href="error-control-in-exploratory-anova.html"><i class="fa fa-check"></i><b>12</b> Error Control in Exploratory ANOVA</a></li>
<li class="chapter" data-level="13" data-path="power-in-interactions.html"><a href="power-in-interactions.html"><i class="fa fa-check"></i><b>13</b> Power in Interactions</a></li>
<li class="chapter" data-level="14" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html"><i class="fa fa-check"></i><b>14</b> Analytic Power Functions</a><ul>
<li class="chapter" data-level="14.1" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html#one-way-between-subject-anova"><i class="fa fa-check"></i><b>14.1</b> One-Way Between Subject ANOVA</a></li>
<li class="chapter" data-level="14.2" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html#two-way-between-subject-interaction"><i class="fa fa-check"></i><b>14.2</b> Two-way Between Subject Interaction</a></li>
<li class="chapter" data-level="14.3" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html#x3-between-subject-anova"><i class="fa fa-check"></i><b>14.3</b> 3x3 Between Subject ANOVA</a></li>
<li class="chapter" data-level="14.4" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html#two-by-two-anova-within-design-1"><i class="fa fa-check"></i><b>14.4</b> Two by two ANOVA, within design</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="power-curves.html"><a href="power-curves.html"><i class="fa fa-check"></i><b>15</b> Power curves</a></li>
<li class="chapter" data-level="16" data-path="explore-increase-in-effect-size-for-moderated-interactions-.html"><a href="explore-increase-in-effect-size-for-moderated-interactions-.html"><i class="fa fa-check"></i><b>16</b> Explore increase in effect size for moderated interactions.</a><ul>
<li class="chapter" data-level="16.1" data-path="explore-increase-in-effect-size-for-moderated-interactions-.html"><a href="explore-increase-in-effect-size-for-moderated-interactions-.html#explore-increase-in-effect-size-for-cross-over-interactions."><i class="fa fa-check"></i><b>16.1</b> Explore increase in effect size for cross-over interactions.</a></li>
<li class="chapter" data-level="16.2" data-path="explore-increase-in-effect-size-for-moderated-interactions-.html"><a href="explore-increase-in-effect-size-for-moderated-interactions-.html#explore-increase-in-correlation-in-moderated-interactions."><i class="fa fa-check"></i><b>16.2</b> Explore increase in correlation in moderated interactions.</a></li>
<li class="chapter" data-level="16.3" data-path="explore-increase-in-effect-size-for-moderated-interactions-.html"><a href="explore-increase-in-effect-size-for-moderated-interactions-.html#increasing-correlation-in-on-factor-decreases-power-in-second-factor"><i class="fa fa-check"></i><b>16.3</b> Increasing correlation in on factor decreases power in second factor</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Validation of Superpower</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="intro" class="section level1">
<h1><span class="header-section-number">Chapter 2</span> One-way ANOVA Part 1</h1>
<div id="validation-of-power-in-one-way-anova" class="section level2">
<h2><span class="header-section-number">2.1</span> Validation of Power in One-Way ANOVA</h2>
<p>Using the formula also used in Albers &amp; Lakens (2018), we can determine the means that should yield a specified effect sizes (expressed in Cohen’s f). Eta-squared (identical to partial eta-squared for One-Way ANOVA’s) has benchmarks of .0099, .0588, and .1379 for small, medium, and large effect sizes (Cohen, 1988). Athough these benchmarks are quite random, and researchers should only use such benchmarks for power analyses as a last resort, we will demonstrate a-priori power analysis for these values.</p>
</div>
<div id="two-conditions" class="section level2">
<h2><span class="header-section-number">2.2</span> Two conditions</h2>
<p>Imagine we aim to design a study to test the hypothesis that giving people a pet to take care of will increase their life satisfaction. We have a control condition, and a condition where people get a pet, and randomly assign participants to either condition. We can simulate a One-Way ANOVA with a specified alpha, sample size, and effect size, on see the statistical power we would have for the ANOVA and the follow-up comparisons. We expect pets to increase life-satisfaction compared to the control condition. Based on work by Pavot and Diener (1993) we believe that we can expect responses on the life-satifaction scale to have a mean of approximately 24 in our population, with a standard deviation of 6.4. We expect having a pet increases life satisfaction with approximately 2.2 scale points for participants who get a pet. 200 participants in total, with 100 participants in each condition. But before we proceed with the data collection, we examine the statistical power our design would have to detect the differences we predict.</p>
<pre class="sourceCode r"><code class="sourceCode r">string &lt;-<span class="st"> &quot;2b&quot;</span>
n &lt;-<span class="st"> </span><span class="dv">100</span>
<span class="co"># We are thinking of running 50 peope in each condition</span>
mu &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">24</span>, <span class="fl">26.2</span>)
<span class="co"># Enter means in the order that matches the labels below.</span>
<span class="co"># In this case, control, cat, dog. </span>
sd &lt;-<span class="st"> </span><span class="fl">6.4</span>
labelnames &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;condition&quot;</span>, <span class="st">&quot;control&quot;</span>, <span class="st">&quot;pet&quot;</span>) <span class="co">#</span>
<span class="co"># the label names should be in the order of the means specified above.</span>
design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> string,
                   <span class="dt">n =</span> n, 
                   <span class="dt">mu =</span> mu, 
                   <span class="dt">sd =</span> sd, 
                   <span class="dt">labelnames =</span> labelnames)</code></pre>
<p><img src="SuperpowerValidation_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<pre class="sourceCode r"><code class="sourceCode r">alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span>
<span class="co"># You should think carefully about how to justify your alpha level.</span>
<span class="co"># We will give some examples later, but for now, use 0.05.</span>
<span class="kw">ANOVA_power</span>(design_result, <span class="dt">alpha_level =</span> alpha_level, <span class="dt">nsims =</span> nsims)</code></pre>
<pre><code>## Power and Effect sizes for ANOVA tests
##                 power effect_size
## anova_condition    69     0.03296
## 
## Power and Effect sizes for contrasts
##                                   power effect_size
## p_condition_control_condition_pet    69        0.34</code></pre>
<p>The result shows that we have exactly the same power for the ANOVA, as we have for the <em>t</em>-test. This is because when there are only two groups, these tests are mathematically identical. In a study with 100 participants, we would have quite low power (around 67.7%). An ANOVA with 2 groups is identical to a <em>t</em>-test. For our example, Cohen’s d (the standardized mean difference) is 2.2/6.4, or d = 0.34375 for the difference between the control condition and pets, which we can use to easily compute the expected power for these simple comparisons using the pwr package.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pwr.t.test</span>(<span class="dt">d =</span> <span class="fl">2.2</span><span class="op">/</span><span class="fl">6.4</span>,
           <span class="dt">n =</span> <span class="dv">100</span>,
           <span class="dt">sig.level =</span> <span class="fl">0.05</span>,
           <span class="dt">type=</span><span class="st">&quot;two.sample&quot;</span>,
           <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)<span class="op">$</span>power</code></pre>
<pre><code>## [1] 0.6768572</code></pre>
<p>We can also directly compute Cohen’s f from Cohen’s d for two groups, as Cohen (1988) describes, because f = 1/2d. So f = 0.5*0.34375 = 0.171875. And indeed, power analysis using the pwr package yields the same result using the pwr.anova.test as the power.t.test.</p>
<pre class="sourceCode r"><code class="sourceCode r">K &lt;-<span class="st"> </span><span class="dv">2</span>
n &lt;-<span class="st"> </span><span class="dv">100</span>
f &lt;-<span class="st"> </span><span class="fl">0.171875</span>
<span class="kw">pwr.anova.test</span>(<span class="dt">n =</span> n,
               <span class="dt">k =</span> K,
               <span class="dt">f =</span> f,
               <span class="dt">sig.level =</span> alpha_level)<span class="op">$</span>power</code></pre>
<pre><code>## [1] 0.6768572</code></pre>
<p>This analysis tells us that running the study with 100 participants in each condition is too likely to <em>not</em> yield a significant test result, even if our expected pattern of differences is true. This is not optimal.</p>
<p>Let’s mathematically explore which pattern of means we would need to expect to habe 90% power for the ANOVA with 50 participants in each group. We can use the pwr package in R to compute a sensitivity analysis that tells us the effect size, in Cohen’s f, that we are able to detect with 3 groups and 50 partiicpants in each group, in order to achive 90% power with an alpha level of 5%.</p>
<pre class="sourceCode r"><code class="sourceCode r">K &lt;-<span class="st"> </span><span class="dv">2</span>
n &lt;-<span class="st"> </span><span class="dv">100</span>
sd &lt;-<span class="st"> </span><span class="fl">6.4</span>
r &lt;-<span class="st"> </span><span class="dv">0</span>
<span class="co">#Calculate f when running simulation</span>
f &lt;-<span class="st"> </span><span class="kw">pwr.anova.test</span>(<span class="dt">n =</span> n,
                    <span class="dt">k =</span> K,
                    <span class="dt">power =</span> <span class="fl">0.9</span>,
                    <span class="dt">sig.level =</span> alpha_level)<span class="op">$</span>f
f</code></pre>
<pre><code>## [1] 0.2303587</code></pre>
<p>This sensitivity analysis shows we have 90% power in our planned design to detect effects of Cohen’s f of 0.2303587. Benchmarks by Cohen (1988) for small, medium, and large Cohen’s f values are 0.1, 0.25, and 0.4, which correspond to eta-squared values of small (.0099), medium (.0588), and large (.1379), in line with d = .2, .5, or .8. So, at least based on these benchmarks, we have 90% power to detect effects that are slightly below a medium effect benchmark.</p>
<pre class="sourceCode r"><code class="sourceCode r">f2 &lt;-<span class="st"> </span>f<span class="op">^</span><span class="dv">2</span>
ES &lt;-<span class="st"> </span>f2<span class="op">/</span>(f2<span class="op">+</span><span class="dv">1</span>)
ES</code></pre>
<pre><code>## [1] 0.0503911</code></pre>
<p>Expressed in eta-squared, we can detect values of eta-squared = 0.05 or larger.</p>
<pre class="sourceCode r"><code class="sourceCode r">mu &lt;-<span class="st"> </span><span class="kw">mu_from_ES</span>(<span class="dt">K =</span> K, <span class="dt">ES =</span> ES)
mu &lt;-<span class="st"> </span>mu <span class="op">*</span><span class="st"> </span>sd
mu</code></pre>
<pre><code>## [1] -1.474295  1.474295</code></pre>
<p>We can compute a pattern of means, given a standard deviation of 6.4, that would give us an effect size of f = 0.23, or eta-squared of 0.05. We should be able to accomplish this is the means are -1.474295 and 1.474295. We can use these values to confirm the ANOVA has 90% power.</p>
<pre class="sourceCode r"><code class="sourceCode r">design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> string,
                   <span class="dt">n =</span> n, 
                   <span class="dt">mu =</span> mu, 
                   <span class="dt">sd =</span> sd, 
                   <span class="dt">labelnames =</span> labelnames)</code></pre>
<p><img src="SuperpowerValidation_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ANOVA_power</span>(design_result, <span class="dt">alpha_level =</span> alpha_level, <span class="dt">nsims =</span> nsims)</code></pre>
<pre><code>## Power and Effect sizes for ANOVA tests
##                 power effect_size
## anova_condition    90     0.05411
## 
## Power and Effect sizes for contrasts
##                                   power effect_size
## p_condition_control_condition_pet    90      0.4595</code></pre>
<p>The simulation confirms that for the <em>F</em>-test for the ANOVA we have 90% power. This is also what g*power tells us what would happen based on a post-hoc power analysis with an f of 0.2303587, 2 groups, 200 participants in total (100 in each between subject condition), and an alpha of 5%.</p>
<p><img src="screenshots/gpower_8.png" />
If we return to our expected means, how many participants do we need for sufficient power? Given the expected difference and standard deviation, d = 0.34375, and f = 0.171875. We can perform an a-priori power analysis for this simple case, which tells us we need 179 participants in each group (we can’t split people in parts, and thus always round a power analysis upward), or 358 in total.</p>
<pre class="sourceCode r"><code class="sourceCode r">K &lt;-<span class="st"> </span><span class="dv">2</span>
power &lt;-<span class="st"> </span><span class="fl">0.9</span>
f &lt;-<span class="st"> </span><span class="fl">0.171875</span>
<span class="kw">pwr.anova.test</span>(<span class="dt">power =</span> power,
               <span class="dt">k =</span> K,
               <span class="dt">f =</span> f,
               <span class="dt">sig.level =</span> alpha_level)</code></pre>
<pre><code>## 
##      Balanced one-way analysis of variance power calculation 
## 
##               k = 2
##               n = 178.8104
##               f = 0.171875
##       sig.level = 0.05
##           power = 0.9
## 
## NOTE: n is number in each group</code></pre>
<p>If we re-run the simulation with this sample size, we indeed have 90% power.</p>
<pre class="sourceCode r"><code class="sourceCode r">string &lt;-<span class="st"> &quot;2b&quot;</span>
n &lt;-<span class="st"> </span><span class="dv">179</span>
mu &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">24</span>, <span class="fl">26.2</span>)
<span class="co"># Enter means in the order that matches the labels below.</span>
<span class="co"># In this case, control, pet. </span>
sd &lt;-<span class="st"> </span><span class="fl">6.4</span>
labelnames &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;condition&quot;</span>, <span class="st">&quot;control&quot;</span>, <span class="st">&quot;pet&quot;</span>) <span class="co">#</span>
<span class="co"># the label names should be in the order of the means specified above.</span>
design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> string,
                   <span class="dt">n =</span> n, 
                   <span class="dt">mu =</span> mu, 
                   <span class="dt">sd =</span> sd, 
                   <span class="dt">labelnames =</span> labelnames)</code></pre>
<p><img src="SuperpowerValidation_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre class="sourceCode r"><code class="sourceCode r">alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span>
power_result &lt;-<span class="st"> </span><span class="kw">ANOVA_power</span>(design_result, <span class="dt">alpha_level =</span> alpha_level, <span class="dt">nsims =</span> nsims)</code></pre>
<pre><code>## Power and Effect sizes for ANOVA tests
##                 power effect_size
## anova_condition    94     0.03254
## 
## Power and Effect sizes for contrasts
##                                   power effect_size
## p_condition_control_condition_pet    94      0.3533</code></pre>
<p>We stored the result from the power analysis in an object. This allows us to request plots (which are not printed automatically) showing the <em>p</em>-value distribution. If we request power_result$plot1 we get the p-value distribution for the ANOVA:</p>
<pre class="sourceCode r"><code class="sourceCode r">power_result<span class="op">$</span>plot1</code></pre>
<p><img src="SuperpowerValidation_files/figure-html/unnamed-chunk-11-1.png" width="672" />
If we request power_result$plot2 we get the p-value distribution for the paired comparisons (in this case only one):</p>
<pre class="sourceCode r"><code class="sourceCode r">power_result<span class="op">$</span>plot2</code></pre>
<p><img src="SuperpowerValidation_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="one-way-anova-part-2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["SuperpowerValidation.pdf", "SuperpowerValidation.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
