<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Mixed ANOVA | The Superpower R Package: Capabilities and Validation</title>
  <meta name="description" content="This is a book describing the capabilities of the Superpower R package." />
  <meta name="generator" content="bookdown 0.10 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Mixed ANOVA | The Superpower R Package: Capabilities and Validation" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a book describing the capabilities of the Superpower R package." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Mixed ANOVA | The Superpower R Package: Capabilities and Validation" />
  
  <meta name="twitter:description" content="This is a book describing the capabilities of the Superpower R package." />
  

<meta name="author" content="Aaron Caldwell &amp; Daniël Lakens" />


<meta name="date" content="2019-09-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="repeated-measures-anova.html">
<link rel="next" href="analytic-power-for-three-way-interactions.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Superpower</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="the-experimental-design.html"><a href="the-experimental-design.html"><i class="fa fa-check"></i><b>2</b> The Experimental Design</a><ul>
<li class="chapter" data-level="2.1" data-path="the-experimental-design.html"><a href="the-experimental-design.html#correlation-matrix"><i class="fa fa-check"></i><b>2.1</b> Correlation Matrix</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="one-way-anova.html"><a href="one-way-anova.html"><i class="fa fa-check"></i><b>3</b> One-way ANOVA</a><ul>
<li class="chapter" data-level="3.1" data-path="one-way-anova.html"><a href="one-way-anova.html#part-1"><i class="fa fa-check"></i><b>3.1</b> Part 1</a><ul>
<li class="chapter" data-level="3.1.1" data-path="one-way-anova.html"><a href="one-way-anova.html#two-conditions"><i class="fa fa-check"></i><b>3.1.1</b> Two conditions</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="one-way-anova.html"><a href="one-way-anova.html#part-2"><i class="fa fa-check"></i><b>3.2</b> Part 2</a><ul>
<li class="chapter" data-level="3.2.1" data-path="one-way-anova.html"><a href="one-way-anova.html#three-conditions"><i class="fa fa-check"></i><b>3.2.1</b> Three conditions</a></li>
<li class="chapter" data-level="3.2.2" data-path="one-way-anova.html"><a href="one-way-anova.html#power-for-simple-effects"><i class="fa fa-check"></i><b>3.2.2</b> Power for simple effects</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="one-way-anova.html"><a href="one-way-anova.html#part-3"><i class="fa fa-check"></i><b>3.3</b> Part 3</a><ul>
<li class="chapter" data-level="3.3.1" data-path="one-way-anova.html"><a href="one-way-anova.html#three-conditions-replication"><i class="fa fa-check"></i><b>3.3.1</b> Three conditions replication</a></li>
<li class="chapter" data-level="3.3.2" data-path="one-way-anova.html"><a href="one-way-anova.html#variation-1"><i class="fa fa-check"></i><b>3.3.2</b> Variation 1</a></li>
<li class="chapter" data-level="3.3.3" data-path="one-way-anova.html"><a href="one-way-anova.html#three-conditions-replication-1"><i class="fa fa-check"></i><b>3.3.3</b> Three conditions replication</a></li>
<li class="chapter" data-level="3.3.4" data-path="one-way-anova.html"><a href="one-way-anova.html#variation-2"><i class="fa fa-check"></i><b>3.3.4</b> Variation 2</a></li>
<li class="chapter" data-level="3.3.5" data-path="one-way-anova.html"><a href="one-way-anova.html#three-conditions-replication-2"><i class="fa fa-check"></i><b>3.3.5</b> Three conditions replication</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="one-way-anova.html"><a href="one-way-anova.html#effect-size-estimates-for-one-way-anova"><i class="fa fa-check"></i><b>3.4</b> Effect Size Estimates for One-Way ANOVA</a><ul>
<li class="chapter" data-level="3.4.1" data-path="one-way-anova.html"><a href="one-way-anova.html#three-conditions-small-effect-size"><i class="fa fa-check"></i><b>3.4.1</b> Three conditions, small effect size</a></li>
<li class="chapter" data-level="3.4.2" data-path="one-way-anova.html"><a href="one-way-anova.html#four-conditions-medium-effect-size"><i class="fa fa-check"></i><b>3.4.2</b> Four conditions, medium effect size</a></li>
<li class="chapter" data-level="3.4.3" data-path="one-way-anova.html"><a href="one-way-anova.html#two-conditions-large-effect-size"><i class="fa fa-check"></i><b>3.4.3</b> Two conditions, large effect size</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html"><i class="fa fa-check"></i><b>4</b> Repeated Measures-ANOVA</a><ul>
<li class="chapter" data-level="4.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#part-1-1"><i class="fa fa-check"></i><b>4.1</b> Part 1</a><ul>
<li class="chapter" data-level="4.1.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#two-conditions-medium-effect-size"><i class="fa fa-check"></i><b>4.1.1</b> Two conditions, medium effect size</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#repeated-measures-anova-part-2"><i class="fa fa-check"></i><b>4.2</b> Repeated Measures-ANOVA Part 2</a><ul>
<li class="chapter" data-level="4.2.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#the-relation-between-cohens-f-and-cohens-d"><i class="fa fa-check"></i><b>4.2.1</b> The relation between Cohen’s f and Cohen’s d</a></li>
<li class="chapter" data-level="4.2.2" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#three-within-conditions-medium-effect-size"><i class="fa fa-check"></i><b>4.2.2</b> Three within conditions, medium effect size</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#part-3-1"><i class="fa fa-check"></i><b>4.3</b> Part 3</a></li>
<li class="chapter" data-level="4.4" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#reproducing-brysbaert"><i class="fa fa-check"></i><b>4.4</b> Reproducing Brysbaert</a><ul>
<li class="chapter" data-level="4.4.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#results"><i class="fa fa-check"></i><b>4.4.1</b> Results</a></li>
<li class="chapter" data-level="4.4.2" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#reproducing-brysbaert-variation-1-changing-correlation"><i class="fa fa-check"></i><b>4.4.2</b> Reproducing Brysbaert Variation 1: Changing Correlation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="mixed-anova.html"><a href="mixed-anova.html"><i class="fa fa-check"></i><b>5</b> Mixed ANOVA</a><ul>
<li class="chapter" data-level="5.1" data-path="mixed-anova.html"><a href="mixed-anova.html#part-1-2"><i class="fa fa-check"></i><b>5.1</b> Part 1</a><ul>
<li class="chapter" data-level="5.1.1" data-path="mixed-anova.html"><a href="mixed-anova.html#two-by-two-anova-within-between-design"><i class="fa fa-check"></i><b>5.1.1</b> Two by two ANOVA, within-between design</a></li>
<li class="chapter" data-level="5.1.2" data-path="mixed-anova.html"><a href="mixed-anova.html#two-by-two-anova-within-between-design-variation-1"><i class="fa fa-check"></i><b>5.1.2</b> Two by two ANOVA, within-between design Variation 1</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="mixed-anova.html"><a href="mixed-anova.html#part-2-1"><i class="fa fa-check"></i><b>5.2</b> Part 2</a><ul>
<li class="chapter" data-level="5.2.1" data-path="mixed-anova.html"><a href="mixed-anova.html#two-by-two-anova-within-within-design"><i class="fa fa-check"></i><b>5.2.1</b> Two by two ANOVA, within-within design</a></li>
<li class="chapter" data-level="5.2.2" data-path="mixed-anova.html"><a href="mixed-anova.html#examine-variation-of-means-and-correlation"><i class="fa fa-check"></i><b>5.2.2</b> Examine variation of means and correlation</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="mixed-anova.html"><a href="mixed-anova.html#part-3-2"><i class="fa fa-check"></i><b>5.3</b> Part 3</a></li>
<li class="chapter" data-level="5.4" data-path="mixed-anova.html"><a href="mixed-anova.html#simple-example-2x2-within-design"><i class="fa fa-check"></i><b>5.4</b> Simple example: 2x2 within design</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="analytic-power-for-three-way-interactions.html"><a href="analytic-power-for-three-way-interactions.html"><i class="fa fa-check"></i><b>6</b> Analytic Power for Three-way Interactions</a></li>
<li class="chapter" data-level="7" data-path="power-for-interactions.html"><a href="power-for-interactions.html"><i class="fa fa-check"></i><b>7</b> Power for Interactions</a></li>
<li class="chapter" data-level="8" data-path="effect-of-varying-designs-on-power.html"><a href="effect-of-varying-designs-on-power.html"><i class="fa fa-check"></i><b>8</b> Effect of Varying Designs on Power</a><ul>
<li class="chapter" data-level="8.1" data-path="effect-of-varying-designs-on-power.html"><a href="effect-of-varying-designs-on-power.html#within-designs"><i class="fa fa-check"></i><b>8.1</b> Within Designs</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="error-control-in-exploratory-anova.html"><a href="error-control-in-exploratory-anova.html"><i class="fa fa-check"></i><b>9</b> Error Control in Exploratory ANOVA</a></li>
<li class="chapter" data-level="10" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html"><i class="fa fa-check"></i><b>10</b> Analytic Power Functions</a><ul>
<li class="chapter" data-level="10.1" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html#one-way-between-subject-anova"><i class="fa fa-check"></i><b>10.1</b> One-Way Between Subject ANOVA</a></li>
<li class="chapter" data-level="10.2" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html#two-way-between-subject-interaction"><i class="fa fa-check"></i><b>10.2</b> Two-way Between Subject Interaction</a></li>
<li class="chapter" data-level="10.3" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html#x3-between-subject-anova"><i class="fa fa-check"></i><b>10.3</b> 3x3 Between Subject ANOVA</a></li>
<li class="chapter" data-level="10.4" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html#two-by-two-anova-within-design"><i class="fa fa-check"></i><b>10.4</b> Two by two ANOVA, within design</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="power-curve.html"><a href="power-curve.html"><i class="fa fa-check"></i><b>11</b> Power Curve</a></li>
<li class="chapter" data-level="12" data-path="explore-increase-in-effect-size-for-moderated-interactions-.html"><a href="explore-increase-in-effect-size-for-moderated-interactions-.html"><i class="fa fa-check"></i><b>12</b> Explore increase in effect size for moderated interactions.</a><ul>
<li class="chapter" data-level="12.1" data-path="explore-increase-in-effect-size-for-moderated-interactions-.html"><a href="explore-increase-in-effect-size-for-moderated-interactions-.html#explore-increase-in-effect-size-for-cross-over-interactions."><i class="fa fa-check"></i><b>12.1</b> Explore increase in effect size for cross-over interactions.</a></li>
<li class="chapter" data-level="12.2" data-path="explore-increase-in-effect-size-for-moderated-interactions-.html"><a href="explore-increase-in-effect-size-for-moderated-interactions-.html#explore-increase-in-correlation-in-moderated-interactions."><i class="fa fa-check"></i><b>12.2</b> Explore increase in correlation in moderated interactions.</a></li>
<li class="chapter" data-level="12.3" data-path="explore-increase-in-effect-size-for-moderated-interactions-.html"><a href="explore-increase-in-effect-size-for-moderated-interactions-.html#increasing-correlation-in-on-factor-decreases-power-in-second-factor"><i class="fa fa-check"></i><b>12.3</b> Increasing correlation in on factor decreases power in second factor</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The Superpower R Package: Capabilities and Validation</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="mixed-anova" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> Mixed ANOVA</h1>
<div id="part-1-2" class="section level2">
<h2><span class="header-section-number">5.1</span> Part 1</h2>
<div id="two-by-two-anova-within-between-design" class="section level3">
<h3><span class="header-section-number">5.1.1</span> Two by two ANOVA, within-between design</h3>
<p>We can simulate a Two-Way ANOVA with a specific alpha, sample size and effect size, to achieve a specified statistical power. We wil try to reproduce the power analysis by g*power for an F-test, ANOVA: Repeated measures, within-between interaction.</p>
<p><img src="screenshots/gpower_5.png" /></p>
<p>For the 2-way interaction, the result should be a power of 91.25% is we have a total samplesize of 46. Since we have 2 groups in the between factor that means the sample size per group is 2 (and both these groups collect 2 repeated measures).</p>
<pre class="sourceCode r"><code class="sourceCode r">mu &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>,<span class="op">-</span><span class="fl">0.25</span>)
n &lt;-<span class="st"> </span><span class="dv">23</span>
sd &lt;-<span class="st"> </span><span class="dv">1</span>
r &lt;-<span class="st"> </span><span class="fl">0.5</span>
string =<span class="st"> &quot;2w*2b&quot;</span>
alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span>
labelnames =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;age&quot;</span>, <span class="st">&quot;old&quot;</span>, <span class="st">&quot;young&quot;</span>, <span class="st">&quot;color&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;red&quot;</span>)

design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(
<span class="dt">design =</span> string,
<span class="dt">n =</span> n,
<span class="dt">mu =</span> mu,
<span class="dt">sd =</span> sd,
<span class="dt">r =</span> r,
<span class="dt">labelnames =</span> labelnames
)</code></pre>
<p><img src="SuperpowerValidation_files/figure-html/start_mixedANOVA-1.png" width="672" /></p>
<pre class="sourceCode r"><code class="sourceCode r">simulation_result &lt;-
<span class="kw">ANOVA_power</span>(design_result, <span class="dt">alpha_level =</span> <span class="fl">0.05</span>, <span class="dt">nsims =</span> nsims)</code></pre>
<pre><code>## Power and Effect sizes for ANOVA tests
##                 power effect_size
## anova_color      4.67     0.02193
## anova_age        5.11     0.02230
## anova_color:age 91.43     0.21557
## 
## Power and Effect sizes for contrasts
##                                            power effect_size
## p_age_old_color_blue_age_old_color_red     37.85   0.5054117
## p_age_old_color_blue_age_young_color_blue  62.35   0.5151720
## p_age_old_color_blue_age_young_color_red    4.86  -0.0047292
## p_age_old_color_red_age_young_color_blue    5.11   0.0003745
## p_age_old_color_red_age_young_color_red    63.13  -0.5206442
## p_age_young_color_blue_age_young_color_red 38.39  -0.5114026
## 
## Within-Subject Factors Included: Check MANOVA Results</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">exact_result &lt;-
<span class="kw">ANOVA_exact</span>(design_result, <span class="dt">alpha_level =</span> alpha_level)</code></pre>
<pre><code>## Power and Effect sizes for ANOVA tests
##           power partial_eta_squared cohen_f non_centrality
## color      5.00              0.0000  0.0000            0.0
## age        5.00              0.0000  0.0000            0.0
## color:age 91.25              0.2072  0.5112           11.5
## 
## Power and Effect sizes for contrasts
##                                            power effect_size
## p_age_old_color_blue_age_old_color_red     38.17         0.5
## p_age_old_color_blue_age_young_color_blue  63.02         0.5
## p_age_old_color_blue_age_young_color_red    5.00         0.0
## p_age_old_color_red_age_young_color_blue    5.00         0.0
## p_age_old_color_red_age_young_color_red    63.02        -0.5
## p_age_young_color_blue_age_young_color_red 38.17        -0.5</code></pre>
</div>
<div id="two-by-two-anova-within-between-design-variation-1" class="section level3">
<h3><span class="header-section-number">5.1.2</span> Two by two ANOVA, within-between design Variation 1</h3>
<p>We can simulate the same Two-Way ANOVA increasing the correlation to 0.7.</p>
<p><img src="screenshots/gpower_6.png" /></p>
<pre class="sourceCode r"><code class="sourceCode r">mu &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">-0.25</span>)
n &lt;-<span class="st"> </span><span class="dv">23</span>
sd &lt;-<span class="st"> </span><span class="dv">1</span>
r &lt;-<span class="st"> </span><span class="fl">0.7</span>
string =<span class="st"> &quot;2w*2b&quot;</span>
alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span>
labelnames =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;age&quot;</span>, <span class="st">&quot;old&quot;</span>, <span class="st">&quot;young&quot;</span>, <span class="st">&quot;color&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;red&quot;</span>)
design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> string,
                              <span class="dt">n =</span> n, 
                              <span class="dt">mu =</span> mu, 
                              <span class="dt">sd =</span> sd, 
                              <span class="dt">r =</span> r, 
                              <span class="dt">labelnames =</span> labelnames)</code></pre>
<p><img src="SuperpowerValidation_files/figure-html/unnamed-chunk-53-1.png" width="672" /></p>
<pre class="sourceCode r"><code class="sourceCode r">simulation_result &lt;-<span class="st"> </span><span class="kw">ANOVA_power</span>(design_result, 
                                 <span class="dt">alpha_level =</span> <span class="fl">0.05</span>,
                                 <span class="dt">nsims =</span> nsims)</code></pre>
<pre><code>## Power and Effect sizes for ANOVA tests
##                 power effect_size
## anova_color      5.14     0.02244
## anova_age        5.16     0.02222
## anova_color:age 99.15     0.30856
## 
## Power and Effect sizes for contrasts
##                                            power effect_size
## p_age_old_color_blue_age_old_color_red     38.49    0.511780
## p_age_old_color_blue_age_young_color_blue  84.18    0.669953
## p_age_old_color_blue_age_young_color_red    4.97    0.002399
## p_age_old_color_red_age_young_color_blue    5.12   -0.002074
## p_age_old_color_red_age_young_color_red    84.26   -0.669801
## p_age_young_color_blue_age_young_color_red 38.07   -0.507094
## 
## Within-Subject Factors Included: Check MANOVA Results</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">exact_result &lt;-<span class="st"> </span><span class="kw">ANOVA_exact</span>(design_result, <span class="dt">alpha_level =</span> alpha_level)</code></pre>
<pre><code>## Power and Effect sizes for ANOVA tests
##           power partial_eta_squared cohen_f non_centrality
## color      5.00              0.0000    0.00         0.0000
## age        5.00              0.0000    0.00         0.0000
## color:age 98.98              0.3034    0.66        19.1667
## 
## Power and Effect sizes for contrasts
##                                            power effect_size
## p_age_old_color_blue_age_old_color_red     38.17      0.5000
## p_age_old_color_blue_age_young_color_blue  84.09      0.6455
## p_age_old_color_blue_age_young_color_red    5.00      0.0000
## p_age_old_color_red_age_young_color_blue    5.00      0.0000
## p_age_old_color_red_age_young_color_red    84.09     -0.6455
## p_age_young_color_blue_age_young_color_red 38.17     -0.5000</code></pre>
</div>
</div>
<div id="part-2-1" class="section level2">
<h2><span class="header-section-number">5.2</span> Part 2</h2>
<div id="two-by-two-anova-within-within-design" class="section level3">
<h3><span class="header-section-number">5.2.1</span> Two by two ANOVA, within-within design</h3>
<p>We can simulate a 2x2 ANOVA, both factors manipulated within participants, with a specific sample size and effect size, to achieve a desired statistical power.</p>
<p>As Potvin &amp; Schutz (2000) explain, analytic procedures for a two-factor repeated measures ANOVA do not seem to exist. The main problem is quantifying the error variance (the denominator when calculating lambda or Cohen’s f). Simulation based aproaches provide a solution.</p>
<p>We can reproduce the simulation coded by <a href="https://cognitivedatascientist.com/2015/12/14/power-simulation-in-r-the-repeated-measures-anova-5/">Ben Amsel</a></p>
<pre class="sourceCode r"><code class="sourceCode r">knitr<span class="op">::</span>opts_chunk<span class="op">$</span><span class="kw">set</span>(<span class="dt">echo =</span> <span class="ot">TRUE</span>, <span class="dt">warning =</span> <span class="ot">FALSE</span>, <span class="dt">message =</span> <span class="ot">FALSE</span>)
 
<span class="co"># define the parameters</span>
<span class="co"># true effects (in this case, a double dissociation)</span>
mu =<span class="st"> </span><span class="kw">c</span>(<span class="dv">700</span>, <span class="dv">670</span>, <span class="dv">670</span>, <span class="dv">700</span>) 
sigma =<span class="st"> </span><span class="dv">150</span>  <span class="co"># population standard deviation</span>
rho =<span class="st"> </span><span class="fl">0.75</span> <span class="co"># correlation between repeated measures</span>
nsubs =<span class="st"> </span><span class="dv">25</span> <span class="co"># how many subjects?</span>
nsims =<span class="st"> </span>nsims <span class="co"># how many simulation replicates?</span>
 
<span class="co"># create 2 factors representing the 2 independent variables</span>
cond =<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">X1 =</span> <span class="kw">rep</span>(<span class="kw">factor</span>(letters[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>]), nsubs <span class="op">*</span><span class="st"> </span><span class="dv">2</span>),
                  <span class="dt">X2 =</span> <span class="kw">rep</span>(<span class="kw">factor</span>(letters[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>]), nsubs, <span class="dt">each =</span> <span class="dv">2</span>))
 
<span class="co"># create a subjects factor</span>
subject =<span class="st"> </span><span class="kw">factor</span>(<span class="kw">sort</span>(<span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span>nsubs, <span class="dv">4</span>)))
 
<span class="co"># combine above into the design matrix</span>
dm =<span class="st"> </span><span class="kw">data.frame</span>(subject, cond)</code></pre>
<p>Build Sigma: the population variance-covariance matrix</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># create k x k matrix populated with sigma</span>
sigma.mat &lt;-<span class="st"> </span><span class="kw">rep</span>(sigma, <span class="dv">4</span>)
S &lt;-
<span class="st">  </span><span class="kw">matrix</span>(sigma.mat,
  <span class="dt">ncol =</span> <span class="kw">length</span>(sigma.mat),
  <span class="dt">nrow =</span> <span class="kw">length</span>(sigma.mat))
 
<span class="co"># compute covariance between measures</span>
Sigma &lt;-<span class="st"> </span><span class="kw">t</span>(S) <span class="op">*</span><span class="st"> </span>S <span class="op">*</span><span class="st"> </span>rho  
 
<span class="co"># put the variances on the diagonal </span>
<span class="kw">diag</span>(Sigma) &lt;-<span class="st"> </span>sigma<span class="op">^</span><span class="dv">2</span>  </code></pre>
<p>Run the simulation</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># stack &#39;nsims&#39; individual data frames into one large data frame</span>
df =<span class="st"> </span>dm[<span class="kw">rep</span>(<span class="kw">seq_len</span>(<span class="kw">nrow</span>(dm)), nsims), ]
 
<span class="co"># add an index column to track the simulation run</span>
df<span class="op">$</span>simID =<span class="st"> </span><span class="kw">sort</span>(<span class="kw">rep</span>(<span class="kw">seq_len</span>(nsims), <span class="kw">nrow</span>(dm)))
 
<span class="co"># sample the observed data from a multivariate normal distribution</span>
<span class="co"># using MASS::mvrnorm with the parameters mu and Sigma created earlier</span>
<span class="co"># and bind to the existing df</span>
 

make.y =<span class="st"> </span><span class="kw">expression</span>(<span class="kw">as.vector</span>(<span class="kw">t</span>(<span class="kw">mvrnorm</span>(nsubs, mu, Sigma))))
df<span class="op">$</span>y =<span class="st"> </span><span class="kw">as.vector</span>(<span class="kw">replicate</span>(nsims, <span class="kw">eval</span>(make.y)))             
 
<span class="co"># use do(), the general purpose complement to the specialized data </span>
<span class="co"># manipulation functions available in dplyr, to run the ANOVA on</span>
<span class="co"># each section of the grouped data frame created by group_by</span>
 

mods &lt;-<span class="st"> </span>df <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(simID) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">do</span>(<span class="dt">model =</span> <span class="kw">aov</span>(y <span class="op">~</span><span class="st"> </span>X1 <span class="op">*</span><span class="st"> </span>X2 <span class="op">+</span><span class="st"> </span><span class="kw">Error</span>(subject <span class="op">/</span><span class="st"> </span>(X1 <span class="op">*</span><span class="st"> </span>X2)), <span class="dt">qr =</span> <span class="ot">FALSE</span>, <span class="dt">data =</span> .)) 
 
<span class="co"># extract p-values for each effect and store in a data frame</span>
p =<span class="st"> </span><span class="kw">data.frame</span>(
  mods <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">do</span>(<span class="kw">as.data.frame</span>(<span class="kw">tidy</span>(.<span class="op">$</span>model[[<span class="dv">3</span>]])<span class="op">$</span>p.value[<span class="dv">1</span>])),
  mods <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">do</span>(<span class="kw">as.data.frame</span>(<span class="kw">tidy</span>(.<span class="op">$</span>model[[<span class="dv">4</span>]])<span class="op">$</span>p.value[<span class="dv">1</span>])),
  mods <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">do</span>(<span class="kw">as.data.frame</span>(<span class="kw">tidy</span>(.<span class="op">$</span>model[[<span class="dv">5</span>]])<span class="op">$</span>p.value[<span class="dv">1</span>])))
<span class="kw">colnames</span>(p) =<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;X1&#39;</span>,<span class="st">&#39;X2&#39;</span>,<span class="st">&#39;Interaction&#39;</span>)</code></pre>
<p>The empirical power is easy to compute, it’s just the proportion of simulation runs where p &lt;. 05.</p>
<pre class="sourceCode r"><code class="sourceCode r">power.res =<span class="st"> </span><span class="kw">apply</span>(<span class="kw">as.matrix</span>(p), <span class="dv">2</span>, 
  <span class="cf">function</span>(x) <span class="kw">round</span>(<span class="kw">mean</span>(<span class="kw">ifelse</span>(x <span class="op">&lt;</span><span class="st"> </span><span class="fl">.05</span>, <span class="dv">1</span>, <span class="dv">0</span>) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>),<span class="dv">2</span>))
power.res</code></pre>
<pre><code>##          X1          X2 Interaction 
##        4.81        4.92       47.98</code></pre>
<p>Visualize the distributions of p-values</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot the known effects</span>
<span class="kw">require</span>(ggplot2)
<span class="kw">require</span>(gridExtra)
 
means =<span class="st"> </span><span class="kw">data.frame</span>(cond[<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>,], mu, <span class="dt">SE =</span> sigma <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(nsubs))
plt1 =<span class="st"> </span><span class="kw">ggplot</span>(means, <span class="kw">aes</span>(<span class="dt">y =</span> mu, <span class="dt">x =</span> X1, <span class="dt">fill =</span> X2)) <span class="op">+</span>
<span class="kw">geom_bar</span>(<span class="dt">position =</span> <span class="kw">position_dodge</span>(), <span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="op">+</span>
<span class="kw">geom_errorbar</span>(
<span class="kw">aes</span>(<span class="dt">ymin =</span> mu <span class="op">-</span><span class="st"> </span>SE, <span class="dt">ymax =</span> mu <span class="op">+</span><span class="st"> </span>SE),
<span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="dt">width =</span> <span class="fl">0.9</span>),
<span class="dt">size =</span> <span class="fl">.6</span>,
<span class="dt">width =</span> <span class="fl">.3</span>
) <span class="op">+</span>
<span class="kw">coord_cartesian</span>(<span class="dt">ylim =</span> <span class="kw">c</span>((.<span class="dv">7</span> <span class="op">*</span><span class="st"> </span><span class="kw">min</span>(mu)), <span class="fl">1.2</span> <span class="op">*</span><span class="st"> </span><span class="kw">max</span>(mu))) <span class="op">+</span>
<span class="kw">theme_bw</span>()

<span class="co"># melt the data into a ggplot friendly &#39;long&#39; format</span>
<span class="kw">require</span>(reshape2)
plotData &lt;-<span class="st"> </span><span class="kw">melt</span>(p, <span class="dt">value.name =</span> <span class="st">&#39;p&#39;</span>)

<span class="co"># plot each of the p-value distributions on a log scale</span>
<span class="kw">options</span>(<span class="dt">scipen =</span> <span class="dv">999</span>) <span class="co"># &#39;turn off&#39; scientific notation</span>
plt2 =<span class="st"> </span><span class="kw">ggplot</span>(plotData, <span class="kw">aes</span>(<span class="dt">x =</span> p)) <span class="op">+</span>
<span class="kw">scale_x_log10</span>(<span class="dt">breaks =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="fl">0.05</span>, <span class="fl">0.001</span>),
<span class="dt">labels =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="fl">0.05</span>, <span class="fl">0.001</span>)) <span class="op">+</span>
<span class="kw">geom_histogram</span>(<span class="dt">colour =</span> <span class="st">&quot;darkblue&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span>
<span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="fl">0.05</span>, <span class="dt">colour =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span>
<span class="kw">facet_grid</span>(variable <span class="op">~</span><span class="st"> </span>.) <span class="op">+</span>
<span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">expression</span>(Log[<span class="dv">10</span>] <span class="op">~</span><span class="st"> </span>P)) <span class="op">+</span>
<span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">color =</span> <span class="st">&#39;black&#39;</span>, <span class="dt">size =</span> <span class="dv">7</span>))

<span class="co"># arrange plots side by side and print</span>
<span class="kw">grid.arrange</span>(plt1, plt2, <span class="dt">nrow =</span> <span class="dv">1</span>)</code></pre>
<p><img src="SuperpowerValidation_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
<p>We can reproduce this simulation:</p>
<pre class="sourceCode r"><code class="sourceCode r">mu =<span class="st"> </span><span class="kw">c</span>(<span class="dv">700</span>, <span class="dv">670</span>, <span class="dv">670</span>, <span class="dv">700</span>) <span class="co"># true effects (in this case, a double dissociation)</span>
sigma =<span class="st"> </span><span class="dv">150</span>  <span class="co"># population standard deviation</span>
n &lt;-<span class="st"> </span><span class="dv">25</span>
sd &lt;-<span class="st"> </span><span class="dv">150</span>
r &lt;-<span class="st"> </span><span class="fl">0.75</span>
string =<span class="st"> &quot;2w*2w&quot;</span>
alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span>
labelnames =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;age&quot;</span>, <span class="st">&quot;old&quot;</span>, <span class="st">&quot;young&quot;</span>, <span class="st">&quot;color&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;red&quot;</span>)
design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> string,
                              <span class="dt">n =</span> n, 
                              <span class="dt">mu =</span> mu, 
                              <span class="dt">sd =</span> sd, 
                              <span class="dt">r =</span> r, 
                              <span class="dt">labelnames =</span> labelnames)</code></pre>
<p><img src="SuperpowerValidation_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<pre class="sourceCode r"><code class="sourceCode r">simulation_result &lt;-<span class="st"> </span><span class="kw">ANOVA_power</span>(design_result, 
                                 <span class="dt">alpha_level =</span> <span class="fl">0.05</span>, 
                                 <span class="dt">nsims =</span> nsims)</code></pre>
<pre><code>## Power and Effect sizes for ANOVA tests
##                 power effect_size
## anova_age        5.04     0.03987
## anova_color      4.86     0.03978
## anova_age:color 47.87     0.16546
## 
## Power and Effect sizes for contrasts
##                                            power effect_size
## p_age_old_color_blue_age_old_color_red     27.50   -0.293176
## p_age_old_color_blue_age_young_color_blue  27.93   -0.296587
## p_age_old_color_blue_age_young_color_red    4.91   -0.005244
## p_age_old_color_red_age_young_color_blue    5.06   -0.002956
## p_age_old_color_red_age_young_color_red    26.86    0.288654
## p_age_young_color_blue_age_young_color_red 27.46    0.292591
## 
## Within-Subject Factors Included: Check MANOVA Results</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">exact_result &lt;-<span class="st"> </span><span class="kw">ANOVA_exact</span>(design_result,
                            <span class="dt">alpha_level =</span> alpha_level)</code></pre>
<pre><code>## Power and Effect sizes for ANOVA tests
##           power partial_eta_squared cohen_f non_centrality
## age         5.0              0.0000  0.0000              0
## color       5.0              0.0000  0.0000              0
## age:color  48.4              0.1429  0.4082              4
## 
## Power and Effect sizes for contrasts
##                                            power effect_size
## p_age_old_color_blue_age_old_color_red      27.4     -0.2828
## p_age_old_color_blue_age_young_color_blue   27.4     -0.2828
## p_age_old_color_blue_age_young_color_red     5.0      0.0000
## p_age_old_color_red_age_young_color_blue     5.0      0.0000
## p_age_old_color_red_age_young_color_red     27.4      0.2828
## p_age_young_color_blue_age_young_color_red  27.4      0.2828</code></pre>
<p>The simulations yield closely matching results.</p>
</div>
<div id="examine-variation-of-means-and-correlation" class="section level3">
<h3><span class="header-section-number">5.2.2</span> Examine variation of means and correlation</h3>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># define the parameters</span>
mu =<span class="st"> </span><span class="kw">c</span>(<span class="dv">700</span>, <span class="dv">670</span>, <span class="dv">690</span>, <span class="dv">750</span>) <span class="co"># true effects (in this case, a double dissociation)</span>
sigma =<span class="st"> </span><span class="dv">150</span>  <span class="co"># population standard deviation</span>
rho =<span class="st"> </span><span class="fl">0.4</span> <span class="co"># correlation between repeated measures</span>
nsubs =<span class="st"> </span><span class="dv">25</span> <span class="co"># how many subjects?</span>
nsims =<span class="st"> </span>nsims <span class="co"># how many simulation replicates?</span>
 
<span class="co"># create 2 factors representing the 2 independent variables</span>
cond =<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">X1 =</span> <span class="kw">rep</span>(<span class="kw">factor</span>(letters[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>]), nsubs <span class="op">*</span><span class="st"> </span><span class="dv">2</span>),
<span class="dt">X2 =</span> <span class="kw">rep</span>(<span class="kw">factor</span>(letters[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>]), nsubs, <span class="dt">each =</span> <span class="dv">2</span>))
 
<span class="co"># create a subjects factor</span>
subject =<span class="st"> </span><span class="kw">factor</span>(<span class="kw">sort</span>(<span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span>nsubs, <span class="dv">4</span>)))
 
<span class="co"># combine above into the design matrix</span>
dm =<span class="st"> </span><span class="kw">data.frame</span>(subject, cond)</code></pre>
<p>Build Sigma: the population variance-covariance matrix</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># create k x k matrix populated with sigma</span>
sigma.mat &lt;-<span class="st"> </span><span class="kw">rep</span>(sigma, <span class="dv">4</span>)
S &lt;-
<span class="kw">matrix</span>(sigma.mat,
<span class="dt">ncol =</span> <span class="kw">length</span>(sigma.mat),
<span class="dt">nrow =</span> <span class="kw">length</span>(sigma.mat))

<span class="co"># compute covariance between measures</span>
Sigma &lt;-<span class="st"> </span><span class="kw">t</span>(S) <span class="op">*</span><span class="st"> </span>S <span class="op">*</span><span class="st"> </span>rho

<span class="co"># put the variances on the diagonal</span>
<span class="kw">diag</span>(Sigma) &lt;-<span class="st"> </span>sigma <span class="op">^</span><span class="st"> </span><span class="dv">2</span>  </code></pre>
<p>Run the simulation</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># stack &#39;nsims&#39; individual data frames into one large data frame</span>
df =<span class="st"> </span>dm[<span class="kw">rep</span>(<span class="kw">seq_len</span>(<span class="kw">nrow</span>(dm)), nsims), ]
 
<span class="co"># add an index column to track the simulation run</span>
df<span class="op">$</span>simID =<span class="st"> </span><span class="kw">sort</span>(<span class="kw">rep</span>(<span class="kw">seq_len</span>(nsims), <span class="kw">nrow</span>(dm)))
 
<span class="co"># sample the observed data from a multivariate normal distribution</span>
<span class="co"># using MASS::mvrnorm with the parameters mu and Sigma created earlier</span>
<span class="co"># and bind to the existing df</span>
 
<span class="kw">require</span>(MASS)
make.y =<span class="st"> </span><span class="kw">expression</span>(<span class="kw">as.vector</span>(<span class="kw">t</span>(<span class="kw">mvrnorm</span>(nsubs, mu, Sigma))))
df<span class="op">$</span>y =<span class="st"> </span><span class="kw">as.vector</span>(<span class="kw">replicate</span>(nsims, <span class="kw">eval</span>(make.y)))             
 
<span class="co"># use do(), the general purpose complement to the specialized data </span>
<span class="co"># manipulation functions available in dplyr, to run the ANOVA on</span>
<span class="co"># each section of the grouped data frame created by group_by</span>
 
<span class="kw">require</span>(dplyr)
<span class="kw">require</span>(car)
<span class="kw">require</span>(broom)
 
mods &lt;-<span class="st"> </span>df <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(simID) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">do</span>(<span class="dt">model =</span> <span class="kw">aov</span>(y <span class="op">~</span><span class="st"> </span>X1 <span class="op">*</span><span class="st"> </span>X2 <span class="op">+</span><span class="st"> </span><span class="kw">Error</span>(subject <span class="op">/</span><span class="st"> </span>(X1 <span class="op">*</span><span class="st"> </span>X2)), 
                 <span class="dt">qr =</span> <span class="ot">FALSE</span>, <span class="dt">data =</span> .))
  
  <span class="co"># extract p-values for each effect and store in a data frame</span>
  p =<span class="st"> </span><span class="kw">data.frame</span>(mods <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">do</span>(<span class="kw">as.data.frame</span>(<span class="kw">tidy</span>(.<span class="op">$</span>model[[<span class="dv">3</span>]])<span class="op">$</span>p.value[<span class="dv">1</span>])),
  mods <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">do</span>(<span class="kw">as.data.frame</span>(<span class="kw">tidy</span>(.<span class="op">$</span>model[[<span class="dv">4</span>]])<span class="op">$</span>p.value[<span class="dv">1</span>])),
  mods <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">do</span>(<span class="kw">as.data.frame</span>(<span class="kw">tidy</span>(.<span class="op">$</span>model[[<span class="dv">5</span>]])<span class="op">$</span>p.value[<span class="dv">1</span>])))
  <span class="kw">colnames</span>(p) =<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;X1&#39;</span>, <span class="st">&#39;X2&#39;</span>, <span class="st">&#39;Interaction&#39;</span>)</code></pre>
<p>The empirical power is easy to compute, it’s just the proportion of simulation runs where p &lt;. 05.</p>
<pre class="sourceCode r"><code class="sourceCode r">power.res =<span class="st"> </span><span class="kw">apply</span>(<span class="kw">as.matrix</span>(p), <span class="dv">2</span>, 
  <span class="cf">function</span>(x) <span class="kw">round</span>(<span class="kw">mean</span>(<span class="kw">ifelse</span>(x <span class="op">&lt;</span><span class="st"> </span><span class="fl">.05</span>, <span class="dv">1</span>, <span class="dv">0</span>) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>),<span class="dv">2</span>))
power.res</code></pre>
<pre><code>##          X1          X2 Interaction 
##        9.59       30.69       46.05</code></pre>
<p>Visualize the distributions of p-values</p>
<pre class="sourceCode r"><code class="sourceCode r">means =<span class="st"> </span><span class="kw">data.frame</span>(cond[<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>,], mu, <span class="dt">SE =</span> sigma <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(nsubs))
plt1 =<span class="st"> </span><span class="kw">ggplot</span>(means, <span class="kw">aes</span>(<span class="dt">y =</span> mu, <span class="dt">x =</span> X1, <span class="dt">fill =</span> X2)) <span class="op">+</span>
<span class="kw">geom_bar</span>(<span class="dt">position =</span> <span class="kw">position_dodge</span>(), <span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="op">+</span>
<span class="kw">geom_errorbar</span>(
<span class="kw">aes</span>(<span class="dt">ymin =</span> mu <span class="op">-</span><span class="st"> </span>SE, <span class="dt">ymax =</span> mu <span class="op">+</span><span class="st"> </span>SE),
<span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="dt">width =</span> <span class="fl">0.9</span>),
<span class="dt">size =</span> <span class="fl">.6</span>,
<span class="dt">width =</span> <span class="fl">.3</span>
) <span class="op">+</span>
<span class="kw">coord_cartesian</span>(<span class="dt">ylim =</span> <span class="kw">c</span>((.<span class="dv">7</span> <span class="op">*</span><span class="st"> </span><span class="kw">min</span>(mu)), <span class="fl">1.2</span> <span class="op">*</span><span class="st"> </span><span class="kw">max</span>(mu))) <span class="op">+</span>
<span class="kw">theme_bw</span>()
 
<span class="co"># melt the data into a ggplot friendly &#39;long&#39; format</span>

plotData &lt;-<span class="st"> </span><span class="kw">melt</span>(p, <span class="dt">value.name =</span> <span class="st">&#39;p&#39;</span>)
 
<span class="co"># plot each of the p-value distributions on a log scale</span>
<span class="kw">options</span>(<span class="dt">scipen =</span> <span class="dv">999</span>) <span class="co"># &#39;turn off&#39; scientific notation</span>
plt2 =<span class="st"> </span><span class="kw">ggplot</span>(plotData, <span class="kw">aes</span>(<span class="dt">x =</span> p)) <span class="op">+</span>
<span class="kw">scale_x_log10</span>(<span class="dt">breaks =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="fl">0.05</span>, <span class="fl">0.001</span>),
<span class="dt">labels =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="fl">0.05</span>, <span class="fl">0.001</span>)) <span class="op">+</span>
<span class="kw">geom_histogram</span>(<span class="dt">colour =</span> <span class="st">&quot;darkblue&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span>
<span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="fl">0.05</span>, <span class="dt">colour =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span>
<span class="kw">facet_grid</span>(variable <span class="op">~</span><span class="st"> </span>.) <span class="op">+</span>
<span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">expression</span>(Log[<span class="dv">10</span>] <span class="op">~</span><span class="st"> </span>P)) <span class="op">+</span>
<span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">color =</span> <span class="st">&#39;black&#39;</span>, <span class="dt">size =</span> <span class="dv">7</span>))

<span class="co"># arrange plots side by side and print</span>
<span class="kw">grid.arrange</span>(plt1, plt2, <span class="dt">nrow =</span> <span class="dv">1</span>)</code></pre>
<p><img src="SuperpowerValidation_files/figure-html/unnamed-chunk-64-1.png" width="672" /></p>
<p>We can reproduce this simulation:</p>
<pre class="sourceCode r"><code class="sourceCode r">mu =<span class="st"> </span><span class="kw">c</span>(<span class="dv">700</span>, <span class="dv">670</span>, <span class="dv">690</span>, <span class="dv">750</span>) <span class="co"># true effects (in this case, a double dissociation)</span>
sigma =<span class="st"> </span><span class="dv">150</span>  <span class="co"># population standard deviation</span>
n &lt;-<span class="st"> </span><span class="dv">25</span>
sd &lt;-<span class="st"> </span><span class="dv">150</span>
r &lt;-<span class="st"> </span><span class="fl">0.4</span>
string =<span class="st"> &quot;2w*2w&quot;</span>
alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span>
labelnames =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;age&quot;</span>, <span class="st">&quot;old&quot;</span>, <span class="st">&quot;young&quot;</span>, <span class="st">&quot;color&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;red&quot;</span>)
design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> string,
                              <span class="dt">n =</span> n, 
                              <span class="dt">mu =</span> mu, 
                              <span class="dt">sd =</span> sd, 
                              <span class="dt">r =</span> r, 
                              <span class="dt">labelnames =</span> labelnames)</code></pre>
<p><img src="SuperpowerValidation_files/figure-html/unnamed-chunk-65-1.png" width="672" /></p>
<pre class="sourceCode r"><code class="sourceCode r">simulation_result &lt;-<span class="st"> </span><span class="kw">ANOVA_power</span>(design_result, 
                                 <span class="dt">alpha_level =</span> <span class="fl">0.05</span>, 
                                 <span class="dt">nsims =</span> nsims)</code></pre>
<pre><code>## Power and Effect sizes for ANOVA tests
##                 power effect_size
## anova_age       30.76     0.11574
## anova_color      9.31     0.05448
## anova_age:color 45.56     0.15723
## 
## Power and Effect sizes for contrasts
##                                            power effect_size
## p_age_old_color_blue_age_old_color_red     14.03    -0.18679
## p_age_old_color_blue_age_young_color_blue   6.06    -0.06037
## p_age_old_color_blue_age_young_color_red   31.38     0.31428
## p_age_old_color_red_age_young_color_blue    9.27     0.12750
## p_age_old_color_red_age_young_color_red    64.87     0.50220
## p_age_young_color_blue_age_young_color_red 41.31     0.37425
## 
## Within-Subject Factors Included: Check MANOVA Results</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">exact_result &lt;-<span class="st"> </span><span class="kw">ANOVA_exact</span>(design_result, <span class="dt">alpha_level =</span> alpha_level)</code></pre>
<pre><code>## Power and Effect sizes for ANOVA tests
##           power partial_eta_squared cohen_f non_centrality
## age       30.40              0.0864  0.3074         2.2685
## color      9.51              0.0171  0.1318         0.4167
## age:color 45.98              0.1351  0.3953         3.7500
## 
## Power and Effect sizes for contrasts
##                                            power effect_size
## p_age_old_color_blue_age_old_color_red     14.16     -0.1826
## p_age_old_color_blue_age_young_color_blue   5.98     -0.0609
## p_age_old_color_blue_age_young_color_red   30.91      0.3043
## p_age_old_color_red_age_young_color_blue    9.00      0.1217
## p_age_old_color_red_age_young_color_red    64.66      0.4869
## p_age_young_color_blue_age_young_color_red 41.80      0.3651</code></pre>
</div>
</div>
<div id="part-3-2" class="section level2">
<h2><span class="header-section-number">5.3</span> Part 3</h2>
<p>###Two by two ANOVA, within design</p>
<p>Potvin &amp; Schutz (2000) simulate a wide range of repeated measure designs. The give an example of a 3x3 design, with the following correlation matrix:</p>
<p><img src="screenshots/PS2000.png" /></p>
<p>Variances were set to 1 (so all covariance matrices in their simulations were identical). In this specific example, the white fields are related to the correlation for the A main effect (these cells have the same level for B, but different levels of A). The grey cells are related to the main effect of B (the cells have the same level of A, but different levels of B). Finally, the black cells are related to the AxB interaction (they have different levels of A and B). The diagonal (all 1) relate to cells with the same levels of A and B.</p>
<p>Potvin &amp; Schulz (2000) examine power for 2x2 within ANOVA designs and develop approximations of the error variance. For a design with 2 within factors (A and B) these are:</p>
<p>For the main effect of A:
<span class="math inline">\(\sigma _ { e } ^ { 2 } = \sigma ^ { 2 } ( 1 - \overline { \rho } _ { A } ) + \sigma ^ { 2 } ( q - 1 ) ( \overline { \rho } _ { B } - \overline { \rho } _ { AB } )\)</span></p>
<p>For the main effectof B:
<span class="math inline">\(\sigma _ { e } ^ { 2 } = \sigma ^ { 2 } ( 1 - \overline { \rho } _ { B } ) + \sigma ^ { 2 } ( p - 1 ) ( \overline { \rho } _ { A } - \overline { \rho } _ { A B } )\)</span></p>
<p>For the interaction between A and B:
<span class="math inline">\(\sigma _ { e } ^ { 2 } = \sigma ^ { 2 } ( 1 - \rho _ { \max } ) - \sigma ^ { 2 } ( \overline { \rho } _ { \min } - \overline { \rho } _ { AB } )\)</span></p>
</div>
<div id="simple-example-2x2-within-design" class="section level2">
<h2><span class="header-section-number">5.4</span> Simple example: 2x2 within design</h2>
<p>It is difficult to just come up with a positive definite covariance matrix. The best way to achieve this is to get the correlations from a pilot study. Indeed, it should be rather difficult to know which correlations to fill in without some pilot data.</p>
<p>We try to get the formulas in Potvin and Schutz (2000) working. <strong>Below, I manage for the main effects, but not for the interaction</strong>.</p>
<pre class="sourceCode r"><code class="sourceCode r">mu =<span class="st"> </span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">4</span>,<span class="dv">2</span>) 
n &lt;-<span class="st"> </span><span class="dv">20</span>
sd &lt;-<span class="st"> </span><span class="dv">5</span>
r &lt;-<span class="st"> </span><span class="kw">c</span>(
  <span class="fl">0.8</span>, <span class="fl">0.4</span>, <span class="fl">0.4</span>,
       <span class="fl">0.4</span>, <span class="fl">0.4</span>,
            <span class="fl">0.8</span>
  )
string =<span class="st"> &quot;2w*2w&quot;</span>
alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span>
labelnames =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;a1&quot;</span>, <span class="st">&quot;a2&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;b1&quot;</span>, <span class="st">&quot;b2&quot;</span>)

design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> string,
                              <span class="dt">n =</span> n, 
                              <span class="dt">mu =</span> mu, 
                              <span class="dt">sd =</span> sd, 
                              <span class="dt">r =</span> r, 
                              <span class="dt">labelnames =</span> labelnames)</code></pre>
<p><img src="SuperpowerValidation_files/figure-html/unnamed-chunk-66-1.png" width="672" /></p>
<pre class="sourceCode r"><code class="sourceCode r">exact_result &lt;-<span class="st"> </span><span class="kw">ANOVA_exact</span>(design_result)</code></pre>
<pre><code>## Power and Effect sizes for ANOVA tests
##     power partial_eta_squared cohen_f non_centrality
## A   24.71              0.0865  0.3078            1.8
## B   81.21              0.3214  0.6882            9.0
## A:B 15.81              0.0500  0.2294            1.0
## 
## Power and Effect sizes for contrasts
##                       power effect_size
## p_A_a1_B_b1_A_a1_B_b2 26.92     -0.3162
## p_A_a1_B_b1_A_a2_B_b1 34.14      0.3651
## p_A_a1_B_b1_A_a2_B_b2  5.00      0.0000
## p_A_a1_B_b2_A_a2_B_b1 64.23      0.5477
## p_A_a1_B_b2_A_a2_B_b2 12.13      0.1826
## p_A_a2_B_b1_A_a2_B_b2 76.52     -0.6325</code></pre>
<p>We can try to use the formula in Potvin &amp; Schutz (2000).</p>
<pre class="sourceCode r"><code class="sourceCode r">k &lt;-<span class="st"> </span><span class="dv">1</span> <span class="co">#one group (because all factors are within)</span>

rho_A &lt;-<span class="st"> </span><span class="fl">0.5</span> <span class="co">#mean r for factor A</span>

rho_B &lt;-<span class="st"> </span><span class="fl">0.8</span> <span class="co">#mean r for factor B</span>

rho_AB &lt;-<span class="st"> </span><span class="fl">0.4</span> <span class="co">#mean r for factor AB</span>

alpha &lt;-<span class="st"> </span><span class="fl">0.05</span>

sigma &lt;-<span class="st"> </span>sd

m_A &lt;-<span class="st"> </span><span class="dv">2</span> <span class="co">#levels factor A</span>

variance_e_A &lt;-<span class="st"> </span>sigma<span class="op">^</span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>rho_A) <span class="op">+</span><span class="st"> </span>sigma<span class="op">^</span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(m_A <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">*</span><span class="st"> </span>(rho_B <span class="op">-</span><span class="st"> </span>rho_AB) 
<span class="co">#Variance A</span>
variance_e_A</code></pre>
<pre><code>## [1] 22.5</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">m_B &lt;-<span class="st"> </span><span class="dv">2</span> <span class="co">#levels factor B</span>

variance_e_B &lt;-<span class="st"> </span>sigma<span class="op">^</span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>rho_B) <span class="op">+</span><span class="st"> </span>sigma<span class="op">^</span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(m_B <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">*</span><span class="st"> </span>(rho_A <span class="op">-</span><span class="st"> </span>rho_AB)
<span class="co">#Variance B</span>
variance_e_B</code></pre>
<pre><code>## [1] 7.5</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">variance_e_AB &lt;-
<span class="st">  </span>(sigma <span class="op">^</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">max</span>(rho_A, rho_B)) <span class="op">-</span><span class="st"> </span>sigma <span class="op">^</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(<span class="kw">min</span>(rho_A, rho_B) <span class="op">-</span><span class="st"> </span>rho_AB)) 
<span class="co">#Variance AB</span>
variance_e_AB</code></pre>
<pre><code>## [1] 2.5</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Create a mean matrix</span>
mean_mat &lt;-<span class="st"> </span><span class="kw">t</span>(<span class="kw">matrix</span>(mu, <span class="dt">nrow =</span> m_B,<span class="dt">ncol =</span> m_A)) 
mean_mat</code></pre>
<pre><code>##      [,1] [,2]
## [1,]    2    1
## [2,]    4    2</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Potving &amp; Schutz, 2000, formula 2, p. 348</span>
<span class="co"># For main effect A</span>
lambda_A &lt;-
<span class="st">  </span>n <span class="op">*</span><span class="st"> </span>m_A <span class="op">*</span><span class="st"> </span><span class="kw">sum</span>((<span class="kw">rowMeans</span>(mean_mat) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(<span class="kw">rowMeans</span>(mean_mat))) <span class="op">^</span><span class="st"> </span><span class="dv">2</span>) <span class="op">/</span><span class="st"> </span>variance_e_A
  lambda_A</code></pre>
<pre><code>## [1] 2</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#calculate degrees of freedom 1 - ignoring the * e sphericity correction</span>
df1 &lt;-<span class="st"> </span>(m_A <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) 

df2 &lt;-<span class="st"> </span>(n <span class="op">-</span><span class="st"> </span>k) <span class="op">*</span><span class="st"> </span>(m_A <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="co">#calculate degrees of freedom 2</span>

F_critical &lt;-<span class="st"> </span><span class="kw">qf</span>(alpha, <span class="co"># critical F-vaue</span>
                 df1,
                 df2, 
                 <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>) 

pow_A &lt;-<span class="st"> </span><span class="kw">pf</span>(<span class="kw">qf</span>(alpha, <span class="co">#power </span>
             df1, 
             df2, 
             <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>), 
          df1, 
          df2, 
          lambda_A, 
          <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)

lambda_B &lt;-
<span class="st">  </span>n <span class="op">*</span><span class="st"> </span>m_B <span class="op">*</span><span class="st"> </span><span class="kw">sum</span>((<span class="kw">colMeans</span>(mean_mat) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(<span class="kw">colMeans</span>(mean_mat))) <span class="op">^</span><span class="st"> </span><span class="dv">2</span>) <span class="op">/</span><span class="st"> </span>variance_e_B 
lambda_B</code></pre>
<pre><code>## [1] 6</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">df1 &lt;-<span class="st"> </span>(m_B <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="co">#calculate degrees of freedom 1</span>

df2 &lt;-<span class="st"> </span>(n <span class="op">-</span><span class="st"> </span>k) <span class="op">*</span><span class="st"> </span>(m_B <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="co">#calculate degrees of freedom 2</span>

F_critical &lt;-<span class="st"> </span><span class="kw">qf</span>(alpha, <span class="co"># critical F-vaue</span>
                 df1,
                 df2,
                 <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>) 

pow_B &lt;-<span class="st"> </span><span class="kw">pf</span>(<span class="kw">qf</span>(alpha, <span class="co">#power </span>
             df1, 
             df2, 
             <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>), 
          df1, 
          df2, 
          lambda_B, 
          <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)

pow_A</code></pre>
<pre><code>## [1] 0.2691752</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">pow_B</code></pre>
<pre><code>## [1] 0.6422587</code></pre>
<p>We see the 26.9 and 64.2 correspond to the results of the simulation quite closely.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#This (or the variance calculation above) does not work.</span>
lambda_AB &lt;-<span class="st"> </span>n <span class="op">*</span><span class="st"> </span><span class="kw">sum</span>((
mean_mat <span class="op">-</span><span class="st"> </span><span class="kw">rowMeans</span>(mean_mat) <span class="op">-</span><span class="st"> </span><span class="kw">colMeans</span>(mean_mat) <span class="op">+</span><span class="st"> </span><span class="kw">mean</span>(mean_mat)
) <span class="op">^</span><span class="st"> </span><span class="dv">2</span>) <span class="op">/</span><span class="st"> </span>variance_e_AB
lambda_AB</code></pre>
<pre><code>## [1] 38</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">df1 &lt;-<span class="st"> </span>(m_A <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">*</span><span class="st"> </span>(m_B <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)  <span class="co">#calculate degrees of freedom 1</span>
df2 &lt;-
(n <span class="op">-</span><span class="st"> </span>k) <span class="op">*</span><span class="st"> </span>(m_A <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">*</span><span class="st"> </span>(m_B <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="co">#calculate degrees of freedom 2</span>
F_critical &lt;-<span class="st"> </span><span class="kw">qf</span>(alpha, <span class="co"># critical F-vaue</span>
df1,
df2,
<span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)

pow &lt;-<span class="st"> </span><span class="kw">pf</span>(<span class="kw">qf</span>(alpha, <span class="co">#power</span>
df1,
df2,
<span class="dt">lower.tail =</span> <span class="ot">FALSE</span>),
df1,
df2,
lambda_AB,
<span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)

pow</code></pre>
<pre><code>## [1] 0.9999458</code></pre>
<p>Maybe the simulation is not correct for the interaction, or the formula is not correctly programmed.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="repeated-measures-anova.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="analytic-power-for-three-way-interactions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["SuperpowerValidation.pdf", "SuperpowerValidation.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
