<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 One-way ANOVA | Validation of Superpower</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.13 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 One-way ANOVA | Validation of Superpower" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 One-way ANOVA | Validation of Superpower" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Aaron Caldwell &amp; Daniël Lakens" />


<meta name="date" content="2019-09-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="repeated-measures-anova.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="one-way-anova.html"><a href="one-way-anova.html"><i class="fa fa-check"></i><b>2</b> One-way ANOVA</a><ul>
<li class="chapter" data-level="2.1" data-path="one-way-anova.html"><a href="one-way-anova.html#validation-of-power-in-one-way-anova-part-1"><i class="fa fa-check"></i><b>2.1</b> Validation of Power in One-Way ANOVA Part 1</a><ul>
<li class="chapter" data-level="2.1.1" data-path="one-way-anova.html"><a href="one-way-anova.html#two-conditions"><i class="fa fa-check"></i><b>2.1.1</b> Two conditions</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="one-way-anova.html"><a href="one-way-anova.html#one-way-anova-part-2-brysbaert-example"><i class="fa fa-check"></i><b>2.2</b> One-way ANOVA Part 2: Brysbaert example</a><ul>
<li class="chapter" data-level="2.2.1" data-path="one-way-anova.html"><a href="one-way-anova.html#three-conditions"><i class="fa fa-check"></i><b>2.2.1</b> Three conditions</a></li>
<li class="chapter" data-level="2.2.2" data-path="one-way-anova.html"><a href="one-way-anova.html#power-for-simple-effects"><i class="fa fa-check"></i><b>2.2.2</b> Power for simple effects</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="one-way-anova.html"><a href="one-way-anova.html#one-way-anova-part-3"><i class="fa fa-check"></i><b>2.3</b> One-way ANOVA Part 3</a><ul>
<li class="chapter" data-level="2.3.1" data-path="one-way-anova.html"><a href="one-way-anova.html#three-conditions-replication"><i class="fa fa-check"></i><b>2.3.1</b> Three conditions replication</a></li>
<li class="chapter" data-level="2.3.2" data-path="one-way-anova.html"><a href="one-way-anova.html#variation-1"><i class="fa fa-check"></i><b>2.3.2</b> Variation 1</a></li>
<li class="chapter" data-level="2.3.3" data-path="one-way-anova.html"><a href="one-way-anova.html#three-conditions-replication-1"><i class="fa fa-check"></i><b>2.3.3</b> Three conditions replication</a></li>
<li class="chapter" data-level="2.3.4" data-path="one-way-anova.html"><a href="one-way-anova.html#variation-2"><i class="fa fa-check"></i><b>2.3.4</b> Variation 2</a></li>
<li class="chapter" data-level="2.3.5" data-path="one-way-anova.html"><a href="one-way-anova.html#three-conditions-replication-2"><i class="fa fa-check"></i><b>2.3.5</b> Three conditions replication</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html"><i class="fa fa-check"></i><b>3</b> Repeated Measures-ANOVA</a><ul>
<li class="chapter" data-level="3.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#part-1"><i class="fa fa-check"></i><b>3.1</b> Part 1</a><ul>
<li class="chapter" data-level="3.1.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#two-conditions-medium-effect-size"><i class="fa fa-check"></i><b>3.1.1</b> Two conditions, medium effect size</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#repeated-measures-anova-part-2"><i class="fa fa-check"></i><b>3.2</b> Repeated Measures-ANOVA Part 2</a><ul>
<li class="chapter" data-level="3.2.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#the-relation-between-cohens-f-and-cohens-d"><i class="fa fa-check"></i><b>3.2.1</b> The relation between Cohen’s f and Cohen’s d</a></li>
<li class="chapter" data-level="3.2.2" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#three-within-conditions-medium-effect-size"><i class="fa fa-check"></i><b>3.2.2</b> Three within conditions, medium effect size</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#repeated-measures-anova-part-3"><i class="fa fa-check"></i><b>3.3</b> Repeated Measures-ANOVA Part 3</a></li>
<li class="chapter" data-level="3.4" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#reproducing-brysbaert"><i class="fa fa-check"></i><b>3.4</b> Reproducing Brysbaert</a></li>
<li class="chapter" data-level="3.5" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#reproducing-brysbaert-variation-1-changing-correlation"><i class="fa fa-check"></i><b>3.5</b> Reproducing Brysbaert Variation 1 Changing Correlation</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="mixed-anova.html"><a href="mixed-anova.html"><i class="fa fa-check"></i><b>4</b> Mixed ANOVA</a><ul>
<li class="chapter" data-level="4.1" data-path="mixed-anova.html"><a href="mixed-anova.html#part-1-two-by-two-anova-within-between-design"><i class="fa fa-check"></i><b>4.1</b> Part 1: Two by two ANOVA, within-between design</a><ul>
<li class="chapter" data-level="4.1.1" data-path="mixed-anova.html"><a href="mixed-anova.html#two-by-two-anova-within-between-design-variation-1"><i class="fa fa-check"></i><b>4.1.1</b> Two by two ANOVA, within-between design Variation 1</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="mixed-anova.html"><a href="mixed-anova.html#part-2-two-by-two-anova-within-within-design"><i class="fa fa-check"></i><b>4.2</b> Part 2: Two by two ANOVA, within-within design</a><ul>
<li class="chapter" data-level="4.2.1" data-path="mixed-anova.html"><a href="mixed-anova.html#examine-variation-of-means-and-correlation"><i class="fa fa-check"></i><b>4.2.1</b> Examine variation of means and correlation</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="mixed-anova.html"><a href="mixed-anova.html#part-3-two-by-two-anova-within-design"><i class="fa fa-check"></i><b>4.3</b> Part 3: Two by two ANOVA, within design</a></li>
<li class="chapter" data-level="4.4" data-path="mixed-anova.html"><a href="mixed-anova.html#simple-example-2x2-within-design"><i class="fa fa-check"></i><b>4.4</b> Simple example: 2x2 within design</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="error-control-in-exploratory-anova.html"><a href="error-control-in-exploratory-anova.html"><i class="fa fa-check"></i><b>5</b> Error Control in Exploratory ANOVA</a></li>
<li class="chapter" data-level="6" data-path="power-for-interactions.html"><a href="power-for-interactions.html"><i class="fa fa-check"></i><b>6</b> Power for Interactions</a></li>
<li class="chapter" data-level="7" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html"><i class="fa fa-check"></i><b>7</b> Analytic Power Functions</a><ul>
<li class="chapter" data-level="7.1" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html#one-way-between-subject-anova"><i class="fa fa-check"></i><b>7.1</b> One-Way Between Subject ANOVA</a></li>
<li class="chapter" data-level="7.2" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html#two-way-between-subject-interaction"><i class="fa fa-check"></i><b>7.2</b> Two-way Between Subject Interaction</a></li>
<li class="chapter" data-level="7.3" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html#x3-between-subject-anova"><i class="fa fa-check"></i><b>7.3</b> 3x3 Between Subject ANOVA</a></li>
<li class="chapter" data-level="7.4" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html#two-by-two-anova-within-design"><i class="fa fa-check"></i><b>7.4</b> Two by two ANOVA, within design</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="power-curve.html"><a href="power-curve.html"><i class="fa fa-check"></i><b>8</b> Power Curve</a></li>
<li class="chapter" data-level="9" data-path="explore-increase-in-effect-size-for-moderated-interactions-.html"><a href="explore-increase-in-effect-size-for-moderated-interactions-.html"><i class="fa fa-check"></i><b>9</b> Explore increase in effect size for moderated interactions.</a><ul>
<li class="chapter" data-level="9.1" data-path="explore-increase-in-effect-size-for-moderated-interactions-.html"><a href="explore-increase-in-effect-size-for-moderated-interactions-.html#explore-increase-in-effect-size-for-cross-over-interactions."><i class="fa fa-check"></i><b>9.1</b> Explore increase in effect size for cross-over interactions.</a></li>
<li class="chapter" data-level="9.2" data-path="explore-increase-in-effect-size-for-moderated-interactions-.html"><a href="explore-increase-in-effect-size-for-moderated-interactions-.html#explore-increase-in-correlation-in-moderated-interactions."><i class="fa fa-check"></i><b>9.2</b> Explore increase in correlation in moderated interactions.</a></li>
<li class="chapter" data-level="9.3" data-path="explore-increase-in-effect-size-for-moderated-interactions-.html"><a href="explore-increase-in-effect-size-for-moderated-interactions-.html#increasing-correlation-in-on-factor-decreases-power-in-second-factor"><i class="fa fa-check"></i><b>9.3</b> Increasing correlation in on factor decreases power in second factor</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="analytic-power-for-three-way-interactions.html"><a href="analytic-power-for-three-way-interactions.html"><i class="fa fa-check"></i><b>10</b> Analytic Power for Three-way Interactions</a></li>
<li class="chapter" data-level="11" data-path="power-for-design-variations.html"><a href="power-for-design-variations.html"><i class="fa fa-check"></i><b>11</b> Power for Design Variations</a><ul>
<li class="chapter" data-level="11.1" data-path="power-for-design-variations.html"><a href="power-for-design-variations.html#within-designs"><i class="fa fa-check"></i><b>11.1</b> Within Designs</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="setting-the-correlation-matrix.html"><a href="setting-the-correlation-matrix.html"><i class="fa fa-check"></i><b>12</b> Setting the Correlation Matrix</a></li>
<li class="chapter" data-level="13" data-path="validation-of-effect-size-estimates-for-one-way-anova.html"><a href="validation-of-effect-size-estimates-for-one-way-anova.html"><i class="fa fa-check"></i><b>13</b> Validation of Effect Size Estimates for One-Way ANOVA</a><ul>
<li class="chapter" data-level="13.1" data-path="validation-of-effect-size-estimates-for-one-way-anova.html"><a href="validation-of-effect-size-estimates-for-one-way-anova.html#three-conditions-small-effect-size"><i class="fa fa-check"></i><b>13.1</b> Three conditions, small effect size</a></li>
<li class="chapter" data-level="13.2" data-path="validation-of-effect-size-estimates-for-one-way-anova.html"><a href="validation-of-effect-size-estimates-for-one-way-anova.html#four-conditions-medium-effect-size"><i class="fa fa-check"></i><b>13.2</b> Four conditions, medium effect size</a></li>
<li class="chapter" data-level="13.3" data-path="validation-of-effect-size-estimates-for-one-way-anova.html"><a href="validation-of-effect-size-estimates-for-one-way-anova.html#two-conditions-large-effect-size"><i class="fa fa-check"></i><b>13.3</b> Two conditions, large effect size</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Validation of Superpower</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="one-way-anova" class="section level1">
<h1><span class="header-section-number">Chapter 2</span> One-way ANOVA</h1>
<div id="validation-of-power-in-one-way-anova-part-1" class="section level2">
<h2><span class="header-section-number">2.1</span> Validation of Power in One-Way ANOVA Part 1</h2>
<p>Using the formula also used in Albers &amp; Lakens (2018), we can determine the means that should yield a specified effect sizes (expressed in Cohen’s f). Eta-squared (identical to partial eta-squared for One-Way ANOVA’s) has benchmarks of .0099, .0588, and .1379 for small, medium, and large effect sizes (Cohen, 1988). Athough these benchmarks are quite random, and researchers should only use such benchmarks for power analyses as a last resort, we will demonstrate a-priori power analysis for these values.</p>
<div id="two-conditions" class="section level3">
<h3><span class="header-section-number">2.1.1</span> Two conditions</h3>
<p>Imagine we aim to design a study to test the hypothesis that giving people a pet to take care of will increase their life satisfaction. We have a control condition, and a condition where people get a pet, and randomly assign participants to either condition. We can simulate a One-Way ANOVA with a specified alpha, sample size, and effect size, on see the statistical power we would have for the ANOVA and the follow-up comparisons. We expect pets to increase life-satisfaction compared to the control condition. Based on work by Pavot and Diener (1993) we believe that we can expect responses on the life-satifaction scale to have a mean of approximately 24 in our population, with a standard deviation of 6.4. We expect having a pet increases life satisfaction with approximately 2.2 scale points for participants who get a pet. 200 participants in total, with 100 participants in each condition. But before we proceed with the data collection, we examine the statistical power our design would have to detect the differences we predict.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1">string &lt;-<span class="st"> &quot;2b&quot;</span></a>
<a class="sourceLine" id="cb1-2" title="2">n &lt;-<span class="st"> </span><span class="dv">100</span></a>
<a class="sourceLine" id="cb1-3" title="3"><span class="co"># We are thinking of running 50 peope in each condition</span></a>
<a class="sourceLine" id="cb1-4" title="4">mu &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">24</span>, <span class="fl">26.2</span>)</a>
<a class="sourceLine" id="cb1-5" title="5"><span class="co"># Enter means in the order that matches the labels below.</span></a>
<a class="sourceLine" id="cb1-6" title="6"><span class="co"># In this case, control, cat, dog. </span></a>
<a class="sourceLine" id="cb1-7" title="7">sd &lt;-<span class="st"> </span><span class="fl">6.4</span></a>
<a class="sourceLine" id="cb1-8" title="8">labelnames &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;condition&quot;</span>, <span class="st">&quot;control&quot;</span>, <span class="st">&quot;pet&quot;</span>) <span class="co">#</span></a>
<a class="sourceLine" id="cb1-9" title="9"><span class="co"># the label names should be in the order of the means specified above.</span></a>
<a class="sourceLine" id="cb1-10" title="10">design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> string,</a>
<a class="sourceLine" id="cb1-11" title="11">                   <span class="dt">n =</span> n, </a>
<a class="sourceLine" id="cb1-12" title="12">                   <span class="dt">mu =</span> mu, </a>
<a class="sourceLine" id="cb1-13" title="13">                   <span class="dt">sd =</span> sd, </a>
<a class="sourceLine" id="cb1-14" title="14">                   <span class="dt">labelnames =</span> labelnames)</a>
<a class="sourceLine" id="cb1-15" title="15">alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span></a>
<a class="sourceLine" id="cb1-16" title="16"><span class="co"># You should think carefully about how to justify your alpha level.</span></a>
<a class="sourceLine" id="cb1-17" title="17"><span class="co"># We will give some examples later, but for now, use 0.05.</span></a>
<a class="sourceLine" id="cb1-18" title="18"><span class="kw">ANOVA_power</span>(design_result, <span class="dt">alpha_level =</span> alpha_level, <span class="dt">nsims =</span> nsims)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##                 power effect_size
## anova_condition    69     0.03938
## 
## Power and Effect sizes for contrasts
##                                   power effect_size
## p_condition_control_condition_pet    69      0.3709</code></pre>
<p>The result shows that we have exactly the same power for the ANOVA, as we have for the <em>t</em>-test. This is because when there are only two groups, these tests are mathematically identical. In a study with 100 participants, we would have quite low power (around 67.7%). An ANOVA with 2 groups is identical to a <em>t</em>-test. For our example, Cohen’s d (the standardized mean difference) is 2.2/6.4, or d = 0.34375 for the difference between the control condition and pets, which we can use to easily compute the expected power for these simple comparisons using the pwr package.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1"><span class="kw">pwr.t.test</span>(<span class="dt">d =</span> <span class="fl">2.2</span><span class="op">/</span><span class="fl">6.4</span>,</a>
<a class="sourceLine" id="cb3-2" title="2">           <span class="dt">n =</span> <span class="dv">100</span>,</a>
<a class="sourceLine" id="cb3-3" title="3">           <span class="dt">sig.level =</span> <span class="fl">0.05</span>,</a>
<a class="sourceLine" id="cb3-4" title="4">           <span class="dt">type=</span><span class="st">&quot;two.sample&quot;</span>,</a>
<a class="sourceLine" id="cb3-5" title="5">           <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)<span class="op">$</span>power</a></code></pre></div>
<pre><code>## [1] 0.6768572</code></pre>
<p>We can also directly compute Cohen’s f from Cohen’s d for two groups, as Cohen (1988) describes, because f = 1/2d. So f = 0.5*0.34375 = 0.171875. And indeed, power analysis using the pwr package yields the same result using the <code>pwr.anova.test</code> as the <code>power.t.test</code>.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1">K &lt;-<span class="st"> </span><span class="dv">2</span></a>
<a class="sourceLine" id="cb5-2" title="2">n &lt;-<span class="st"> </span><span class="dv">100</span></a>
<a class="sourceLine" id="cb5-3" title="3">f &lt;-<span class="st"> </span><span class="fl">0.171875</span></a>
<a class="sourceLine" id="cb5-4" title="4"><span class="kw">pwr.anova.test</span>(<span class="dt">n =</span> n,</a>
<a class="sourceLine" id="cb5-5" title="5">               <span class="dt">k =</span> K,</a>
<a class="sourceLine" id="cb5-6" title="6">               <span class="dt">f =</span> f,</a>
<a class="sourceLine" id="cb5-7" title="7">               <span class="dt">sig.level =</span> alpha_level)<span class="op">$</span>power</a></code></pre></div>
<pre><code>## [1] 0.6768572</code></pre>
<p>This analysis tells us that running the study with 100 participants in each condition is too likely to <em>not</em> yield a significant test result, even if our expected pattern of differences is true. This is not optimal.</p>
<p>Let’s mathematically explore which pattern of means we would need to expect to habe 90% power for the ANOVA with 50 participants in each group. We can use the pwr package in R to compute a sensitivity analysis that tells us the effect size, in Cohen’s f, that we are able to detect with 3 groups and 50 partiicpants in each group, in order to achive 90% power with an alpha level of 5%.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1">K &lt;-<span class="st"> </span><span class="dv">2</span></a>
<a class="sourceLine" id="cb7-2" title="2">n &lt;-<span class="st"> </span><span class="dv">100</span></a>
<a class="sourceLine" id="cb7-3" title="3">sd &lt;-<span class="st"> </span><span class="fl">6.4</span></a>
<a class="sourceLine" id="cb7-4" title="4">r &lt;-<span class="st"> </span><span class="dv">0</span></a>
<a class="sourceLine" id="cb7-5" title="5"><span class="co">#Calculate f when running simulation</span></a>
<a class="sourceLine" id="cb7-6" title="6">f &lt;-<span class="st"> </span><span class="kw">pwr.anova.test</span>(<span class="dt">n =</span> n,</a>
<a class="sourceLine" id="cb7-7" title="7">                    <span class="dt">k =</span> K,</a>
<a class="sourceLine" id="cb7-8" title="8">                    <span class="dt">power =</span> <span class="fl">0.9</span>,</a>
<a class="sourceLine" id="cb7-9" title="9">                    <span class="dt">sig.level =</span> alpha_level)<span class="op">$</span>f</a>
<a class="sourceLine" id="cb7-10" title="10">f</a></code></pre></div>
<pre><code>## [1] 0.2303587</code></pre>
<p>This sensitivity analysis shows we have 90% power in our planned design to detect effects of Cohen’s f of 0.2303587. Benchmarks by Cohen (1988) for small, medium, and large Cohen’s f values are 0.1, 0.25, and 0.4, which correspond to eta-squared values of small (.0099), medium (.0588), and large (.1379), in line with d = .2, .5, or .8. So, at least based on these benchmarks, we have 90% power to detect effects that are slightly below a medium effect benchmark.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1">f2 &lt;-<span class="st"> </span>f<span class="op">^</span><span class="dv">2</span></a>
<a class="sourceLine" id="cb9-2" title="2">ES &lt;-<span class="st"> </span>f2<span class="op">/</span>(f2<span class="op">+</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb9-3" title="3">ES</a></code></pre></div>
<pre><code>## [1] 0.0503911</code></pre>
<p>Expressed in eta-squared, we can detect values of eta-squared = 0.05 or larger.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1">mu &lt;-<span class="st"> </span><span class="kw">mu_from_ES</span>(<span class="dt">K =</span> K, <span class="dt">ES =</span> ES)</a>
<a class="sourceLine" id="cb11-2" title="2">mu &lt;-<span class="st"> </span>mu <span class="op">*</span><span class="st"> </span>sd</a>
<a class="sourceLine" id="cb11-3" title="3">mu</a></code></pre></div>
<pre><code>## [1] -1.474295  1.474295</code></pre>
<p>We can compute a pattern of means, given a standard deviation of 6.4, that would give us an effect size of f = 0.23, or eta-squared of 0.05. We should be able to accomplish this is the means are -1.474295 and 1.474295. We can use these values to confirm the ANOVA has 90% power.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1">design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> string,</a>
<a class="sourceLine" id="cb13-2" title="2">                   <span class="dt">n =</span> n, </a>
<a class="sourceLine" id="cb13-3" title="3">                   <span class="dt">mu =</span> mu, </a>
<a class="sourceLine" id="cb13-4" title="4">                   <span class="dt">sd =</span> sd, </a>
<a class="sourceLine" id="cb13-5" title="5">                   <span class="dt">labelnames =</span> labelnames)</a>
<a class="sourceLine" id="cb13-6" title="6">simulation_result &lt;-<span class="st"> </span><span class="kw">ANOVA_power</span>(design_result, <span class="dt">alpha_level =</span> alpha_level, <span class="dt">nsims =</span> nsims)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##                 power effect_size
## anova_condition    89     0.05414
## 
## Power and Effect sizes for contrasts
##                                   power effect_size
## p_condition_control_condition_pet    89      0.4593</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1">exact_result &lt;-<span class="st"> </span><span class="kw">ANOVA_exact</span>(design_result, <span class="dt">alpha_level =</span> alpha_level)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##           power partial_eta_squared cohen_f non_centrality
## condition 90.01              0.0509  0.2315         10.613
## 
## Power and Effect sizes for contrasts
##                                   power effect_size
## p_condition_control_condition_pet 90.01      0.4607</code></pre>
<p>The simulation confirms that for the <em>F</em>-test for the ANOVA we have 90% power. This is also what g*power tells us what would happen based on a post-hoc power analysis with an f of 0.2303587, 2 groups, 200 participants in total (100 in each between subject condition), and an alpha of 5%.</p>
<p><img src="screenshots/gpower_8.png" />
If we return to our expected means, how many participants do we need for sufficient power? Given the expected difference and standard deviation, d = 0.34375, and f = 0.171875. We can perform an a-priori power analysis for this simple case, which tells us we need 179 participants in each group (we can’t split people in parts, and thus always round a power analysis upward), or 358 in total.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" title="1">K &lt;-<span class="st"> </span><span class="dv">2</span></a>
<a class="sourceLine" id="cb17-2" title="2">power &lt;-<span class="st"> </span><span class="fl">0.9</span></a>
<a class="sourceLine" id="cb17-3" title="3">f &lt;-<span class="st"> </span><span class="fl">0.171875</span></a>
<a class="sourceLine" id="cb17-4" title="4"><span class="kw">pwr.anova.test</span>(<span class="dt">power =</span> power,</a>
<a class="sourceLine" id="cb17-5" title="5">               <span class="dt">k =</span> K,</a>
<a class="sourceLine" id="cb17-6" title="6">               <span class="dt">f =</span> f,</a>
<a class="sourceLine" id="cb17-7" title="7">               <span class="dt">sig.level =</span> alpha_level)</a></code></pre></div>
<pre><code>## 
##      Balanced one-way analysis of variance power calculation 
## 
##               k = 2
##               n = 178.8104
##               f = 0.171875
##       sig.level = 0.05
##           power = 0.9
## 
## NOTE: n is number in each group</code></pre>
<p>If we re-run the simulation with this sample size, we indeed have 90% power.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" title="1">string &lt;-<span class="st"> &quot;2b&quot;</span></a>
<a class="sourceLine" id="cb19-2" title="2">n &lt;-<span class="st"> </span><span class="dv">179</span></a>
<a class="sourceLine" id="cb19-3" title="3">mu &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">24</span>, <span class="fl">26.2</span>)</a>
<a class="sourceLine" id="cb19-4" title="4"><span class="co"># Enter means in the order that matches the labels below.</span></a>
<a class="sourceLine" id="cb19-5" title="5"><span class="co"># In this case, control, pet. </span></a>
<a class="sourceLine" id="cb19-6" title="6">sd &lt;-<span class="st"> </span><span class="fl">6.4</span></a>
<a class="sourceLine" id="cb19-7" title="7">labelnames &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;condition&quot;</span>, <span class="st">&quot;control&quot;</span>, <span class="st">&quot;pet&quot;</span>) <span class="co">#</span></a>
<a class="sourceLine" id="cb19-8" title="8"><span class="co"># the label names should be in the order of the means specified above.</span></a>
<a class="sourceLine" id="cb19-9" title="9">design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> string,</a>
<a class="sourceLine" id="cb19-10" title="10">                   <span class="dt">n =</span> n, </a>
<a class="sourceLine" id="cb19-11" title="11">                   <span class="dt">mu =</span> mu, </a>
<a class="sourceLine" id="cb19-12" title="12">                   <span class="dt">sd =</span> sd, </a>
<a class="sourceLine" id="cb19-13" title="13">                   <span class="dt">labelnames =</span> labelnames)</a>
<a class="sourceLine" id="cb19-14" title="14">alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span></a>
<a class="sourceLine" id="cb19-15" title="15">power_result &lt;-<span class="st"> </span><span class="kw">ANOVA_power</span>(design_result, <span class="dt">alpha_level =</span> alpha_level, <span class="dt">nsims =</span> nsims)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##                 power effect_size
## anova_condition    90     0.03247
## 
## Power and Effect sizes for contrasts
##                                   power effect_size
## p_condition_control_condition_pet    90      0.3447</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" title="1">exact_result &lt;-<span class="st"> </span><span class="kw">ANOVA_exact</span>(design_result, <span class="dt">alpha_level =</span> alpha_level)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##           power partial_eta_squared cohen_f non_centrality
## condition 90.03              0.0288  0.1724        10.5757
## 
## Power and Effect sizes for contrasts
##                                   power effect_size
## p_condition_control_condition_pet 90.03      0.3437</code></pre>
<p>We stored the result from the power analysis in an object. This allows us to request plots (which are not printed automatically) showing the <em>p</em>-value distribution. If we request power_result$plot1 we get the p-value distribution for the ANOVA:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" title="1">power_result<span class="op">$</span>plot1</a></code></pre></div>
<p><img src="SuperpowerValidation_files/figure-html/unnamed-chunk-10-1.png" width="672" />
If we request power_result$plot2 we get the p-value distribution for the paired comparisons (in this case only one):</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" title="1">power_result<span class="op">$</span>plot2</a></code></pre></div>
<p><img src="SuperpowerValidation_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>

</div>
</div>
<div id="one-way-anova-part-2-brysbaert-example" class="section level2">
<h2><span class="header-section-number">2.2</span> One-way ANOVA Part 2: Brysbaert example</h2>
<div id="three-conditions" class="section level3">
<h3><span class="header-section-number">2.2.1</span> Three conditions</h3>
<p>Imagine we aim to design a study to test the hypothesis that giving people a pet to take care of will increase their life satisfaction. We have a control condition, a ‘cat’ pet condition, and a ‘dog’ pet condition. We can simulate a One-Way ANOVA with a specified alpha, sample size, and effect size, on see the statistical power we would have for the ANOVA and the follow-up comparisons. We expect all pets to increase life-satisfaction compared to the control condition. Obviously, we also expect the people who are in the ‘dog’ pet condition to have even greater life-satisfaction than people in the ‘cat’ pet condition. Based on work by Pavot and Diener (1993) we believe that we can expect responses on the life-satifaction scale to have a mean of approximately 24 in our population, with a standard deviation of 6.4. We expect having a pet increases life satisfaction with approximately 2.2 scale points for participants who get a cat, and 2.6 scale points for participants who get a dog. We initially consider collecting data from 150 participants in total, with 50 participants in each condition. But before we proceed with the data collection, we examine the statistical power our design would have to detect the differences we predict.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" title="1">string &lt;-<span class="st"> &quot;3b&quot;</span></a>
<a class="sourceLine" id="cb25-2" title="2">n &lt;-<span class="st"> </span><span class="dv">50</span></a>
<a class="sourceLine" id="cb25-3" title="3"><span class="co"># We are thinking of running 50 peope in each condition</span></a>
<a class="sourceLine" id="cb25-4" title="4">mu &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">24</span>, <span class="fl">26.2</span>, <span class="fl">26.6</span>)</a>
<a class="sourceLine" id="cb25-5" title="5"><span class="co"># Enter means in the order that matches the labels below.</span></a>
<a class="sourceLine" id="cb25-6" title="6"><span class="co"># In this case, control, cat, dog. </span></a>
<a class="sourceLine" id="cb25-7" title="7">sd &lt;-<span class="st"> </span><span class="fl">6.4</span></a>
<a class="sourceLine" id="cb25-8" title="8">labelnames &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;condition&quot;</span>, <span class="st">&quot;control&quot;</span>, <span class="st">&quot;cat&quot;</span>, <span class="st">&quot;dog&quot;</span>) <span class="co">#</span></a>
<a class="sourceLine" id="cb25-9" title="9"><span class="co"># the label names should be in the order of the means specified above.</span></a>
<a class="sourceLine" id="cb25-10" title="10">design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> string,</a>
<a class="sourceLine" id="cb25-11" title="11">                   <span class="dt">n =</span> n, </a>
<a class="sourceLine" id="cb25-12" title="12">                   <span class="dt">mu =</span> mu, </a>
<a class="sourceLine" id="cb25-13" title="13">                   <span class="dt">sd =</span> sd, </a>
<a class="sourceLine" id="cb25-14" title="14">                   <span class="dt">labelnames =</span> labelnames)</a>
<a class="sourceLine" id="cb25-15" title="15">alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span></a>
<a class="sourceLine" id="cb25-16" title="16"><span class="co"># You should think carefully about how to justify your alpha level.</span></a>
<a class="sourceLine" id="cb25-17" title="17"><span class="co"># We will give some examples later, but for now, use 0.05.</span></a>
<a class="sourceLine" id="cb25-18" title="18">simulation_result &lt;-<span class="st"> </span><span class="kw">ANOVA_power</span>(design_result, <span class="dt">alpha_level =</span> alpha_level, <span class="dt">nsims =</span> nsims)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##                 power effect_size
## anova_condition    51     0.04665
## 
## Power and Effect sizes for contrasts
##                                   power effect_size
## p_condition_control_condition_cat    46     0.37235
## p_condition_control_condition_dog    54     0.42217
## p_condition_cat_condition_dog         4     0.04717</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" title="1">exact_result &lt;-<span class="st"> </span><span class="kw">ANOVA_exact</span>(design_result, <span class="dt">alpha_level =</span> alpha_level)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##           power partial_eta_squared cohen_f non_centrality
## condition 47.69              0.0315  0.1804         4.7852
## 
## Power and Effect sizes for contrasts
##                                   power effect_size
## p_condition_control_condition_cat 39.83      0.3437
## p_condition_control_condition_dog 52.05      0.4063
## p_condition_cat_condition_dog      6.10      0.0625</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" title="1"><span class="co">#should yield</span></a>
<a class="sourceLine" id="cb29-2" title="2"><span class="co">#0.3983064</span></a>
<a class="sourceLine" id="cb29-3" title="3"><span class="co">#0.5205162</span></a>
<a class="sourceLine" id="cb29-4" title="4"><span class="co">#0.06104044</span></a></code></pre></div>
<p>The result shows that you would have quite low power with 50 participants, both for the overall ANOVA (just around 50% power), as for the follow up comparisons (approximately 40% power for the control vs cat condition, around 50% for the control vs dogs condition, and a really low power (around 6%, just above the Type 1 error rate of 5%) for the expected difference between cats and dogs.</p>
</div>
<div id="power-for-simple-effects" class="section level3">
<h3><span class="header-section-number">2.2.2</span> Power for simple effects</h3>
<p>We are typically not just interested in the ANOVA, but also in follow up comparisons. In this case, we would perform a <em>t</em>-test comparing the control condition against the cat and dog condition, and we would compare the cat and dog conditions against each other, in independent <em>t</em>-tests.</p>
<p>For our example, Cohen’s d (the standardized mean difference) is 2.2/6.4, or d = 0.34375 for the difference between the control condition and cats, 2.6/6.4 of d = 0.40625 for the difference between the control condition and dogs, and 0.4/6.4 or d = 0.0625 for the difference between cats and dogs as pets.</p>
<p>We can easily compute the expected power for these simple comparisons using the pwr package.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" title="1"><span class="kw">pwr.t.test</span>(<span class="dt">d =</span> <span class="fl">2.2</span><span class="op">/</span><span class="fl">6.4</span>,</a>
<a class="sourceLine" id="cb30-2" title="2">           <span class="dt">n =</span> <span class="dv">50</span>,</a>
<a class="sourceLine" id="cb30-3" title="3">           <span class="dt">sig.level =</span> <span class="fl">0.05</span>,</a>
<a class="sourceLine" id="cb30-4" title="4">           <span class="dt">type=</span><span class="st">&quot;two.sample&quot;</span>,</a>
<a class="sourceLine" id="cb30-5" title="5">           <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)<span class="op">$</span>power</a></code></pre></div>
<pre><code>## [1] 0.3983064</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" title="1"><span class="kw">pwr.t.test</span>(<span class="dt">d =</span> <span class="fl">2.6</span><span class="op">/</span><span class="fl">6.4</span>,</a>
<a class="sourceLine" id="cb32-2" title="2">           <span class="dt">n =</span> <span class="dv">50</span>,</a>
<a class="sourceLine" id="cb32-3" title="3">           <span class="dt">sig.level =</span> <span class="fl">0.05</span>,</a>
<a class="sourceLine" id="cb32-4" title="4">           <span class="dt">type=</span><span class="st">&quot;two.sample&quot;</span>,</a>
<a class="sourceLine" id="cb32-5" title="5">           <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)<span class="op">$</span>power</a></code></pre></div>
<pre><code>## [1] 0.5205162</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" title="1"><span class="kw">pwr.t.test</span>(<span class="dt">d =</span> <span class="fl">0.4</span><span class="op">/</span><span class="fl">6.4</span>,</a>
<a class="sourceLine" id="cb34-2" title="2">           <span class="dt">n =</span> <span class="dv">50</span>,</a>
<a class="sourceLine" id="cb34-3" title="3">           <span class="dt">sig.level =</span> <span class="fl">0.05</span>,</a>
<a class="sourceLine" id="cb34-4" title="4">           <span class="dt">type=</span><span class="st">&quot;two.sample&quot;</span>,</a>
<a class="sourceLine" id="cb34-5" title="5">           <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)<span class="op">$</span>power</a></code></pre></div>
<pre><code>## [1] 0.06104044</code></pre>
<p>This analysis tells us that running the study with 50 participants in each condition is more likely to <em>not</em> yield a significant test result, even if our expected pattern of differences is true, than that we will observe a <em>p</em>-value smaller than our alpha level. This is not optimal.</p>
<p>Let’s mathematically explore which pattern of means we would need to expect to habe 90% power for the ANOVA with 50 participants in each group. We can use the pwr package in R to compute a sensitivity analysis that tells us the effect size, in Cohen’s f, that we are able to detect with 3 groups and 50 partiicpants in each group, in order to achive 90% power with an alpha level of 5%.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" title="1">K &lt;-<span class="st"> </span><span class="dv">3</span></a>
<a class="sourceLine" id="cb36-2" title="2">n &lt;-<span class="st"> </span><span class="dv">50</span></a>
<a class="sourceLine" id="cb36-3" title="3">sd &lt;-<span class="st"> </span><span class="fl">6.4</span></a>
<a class="sourceLine" id="cb36-4" title="4">r &lt;-<span class="st"> </span><span class="dv">0</span></a>
<a class="sourceLine" id="cb36-5" title="5"><span class="co">#Calculate f when running simulation</span></a>
<a class="sourceLine" id="cb36-6" title="6">f &lt;-<span class="st"> </span><span class="kw">pwr.anova.test</span>(<span class="dt">n =</span> n,</a>
<a class="sourceLine" id="cb36-7" title="7">                    <span class="dt">k =</span> K,</a>
<a class="sourceLine" id="cb36-8" title="8">                    <span class="dt">power =</span> <span class="fl">0.9</span>,</a>
<a class="sourceLine" id="cb36-9" title="9">                    <span class="dt">sig.level =</span> alpha_level)<span class="op">$</span>f</a>
<a class="sourceLine" id="cb36-10" title="10">f</a></code></pre></div>
<pre><code>## [1] 0.2934417</code></pre>
<p>This sensitivity analysis shows we have 90% power in our planned design to detect effects of Cohen’s f of 0.2934417. Benchmarks by Cohen (1988) for small, medium, and large Cohen’s f values are 0.1, 0.25, and 0.4, which correspond to eta-squared values of small (.0099), medium (.0588), and large (.1379), in line with d = .2, .5, or .8. So, at least based on these benchmarks, we have 90% power to detect effects that are somewhat sizeable.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" title="1">f2 &lt;-<span class="st"> </span>f<span class="op">^</span><span class="dv">2</span></a>
<a class="sourceLine" id="cb38-2" title="2">ES &lt;-<span class="st"> </span>f2<span class="op">/</span>(f2<span class="op">+</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb38-3" title="3">ES</a></code></pre></div>
<pre><code>## [1] 0.07928127</code></pre>
<p>Expressed in eta-squared, we can detect values of eta-squared = 0.0793 or larger.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" title="1">mu &lt;-<span class="st"> </span><span class="kw">mu_from_ES</span>(<span class="dt">K =</span> K, <span class="dt">ES =</span> ES)</a>
<a class="sourceLine" id="cb40-2" title="2">mu &lt;-<span class="st"> </span>mu <span class="op">*</span><span class="st"> </span>sd</a>
<a class="sourceLine" id="cb40-3" title="3">mu</a></code></pre></div>
<pre><code>## [1] -2.300104  0.000000  2.300104</code></pre>
<p>We can compute a pattern of means, given a standard deviation of 6.4, that would give us an effect size of f = 0.2934, or eta-squared of 0.0793. We should be able to accomplish this is the means are -2.300104, 0.000000, and 2.300104. We can use these values to confirm the ANOVA has 90% power.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" title="1">design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> string,</a>
<a class="sourceLine" id="cb42-2" title="2">                   <span class="dt">n =</span> n, </a>
<a class="sourceLine" id="cb42-3" title="3">                   <span class="dt">mu =</span> mu, </a>
<a class="sourceLine" id="cb42-4" title="4">                   <span class="dt">sd =</span> sd, </a>
<a class="sourceLine" id="cb42-5" title="5">                   <span class="dt">labelnames =</span> labelnames)</a>
<a class="sourceLine" id="cb42-6" title="6">simulation_result &lt;-<span class="st"> </span><span class="kw">ANOVA_power</span>(design_result, <span class="dt">alpha_level =</span> alpha_level, <span class="dt">nsims =</span> nsims)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##                 power effect_size
## anova_condition    87     0.08971
## 
## Power and Effect sizes for contrasts
##                                   power effect_size
## p_condition_control_condition_cat    34      0.3320
## p_condition_control_condition_dog    94      0.7110
## p_condition_cat_condition_dog        43      0.3804</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" title="1">exact_result &lt;-<span class="st"> </span><span class="kw">ANOVA_exact</span>(design_result, <span class="dt">alpha_level =</span> alpha_level)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##           power partial_eta_squared cohen_f non_centrality
## condition    90              0.0808  0.2964        12.9162
## 
## Power and Effect sizes for contrasts
##                                   power effect_size
## p_condition_control_condition_cat 42.84      0.3594
## p_condition_control_condition_dog 94.50      0.7188
## p_condition_cat_condition_dog     42.84      0.3594</code></pre>
<p>The simulation confirms that for the <em>F</em>-test for the ANOVA we have 90% power. This is also what g*power tells us what would happen based on a post-hoc power analysis with an f of 0.2934417, 3 groups, 150 participants in total (50 in each between subject condition), and an alpha of 5%.</p>
<p><img src="screenshots/gpower_7.png" /></p>
<p>We can also compute the power for the ANOVA and simple effects in R with the pwr package. The calculated effect sizes and power match those from the simulation.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" title="1">K &lt;-<span class="st"> </span><span class="dv">3</span></a>
<a class="sourceLine" id="cb46-2" title="2">n &lt;-<span class="st"> </span><span class="dv">50</span></a>
<a class="sourceLine" id="cb46-3" title="3">sd &lt;-<span class="st"> </span><span class="fl">6.4</span></a>
<a class="sourceLine" id="cb46-4" title="4">f &lt;-<span class="st"> </span><span class="fl">0.2934417</span></a>
<a class="sourceLine" id="cb46-5" title="5"><span class="kw">pwr.anova.test</span>(<span class="dt">n =</span> n,</a>
<a class="sourceLine" id="cb46-6" title="6">               <span class="dt">k =</span> K,</a>
<a class="sourceLine" id="cb46-7" title="7">               <span class="dt">f =</span> f,</a>
<a class="sourceLine" id="cb46-8" title="8">               <span class="dt">sig.level =</span> alpha_level)<span class="op">$</span>power</a></code></pre></div>
<pre><code>## [1] 0.9000112</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" title="1">d &lt;-<span class="st"> </span><span class="fl">2.300104</span><span class="op">/</span><span class="fl">6.4</span></a>
<a class="sourceLine" id="cb48-2" title="2">d</a></code></pre></div>
<pre><code>## [1] 0.3593912</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb50-1" title="1"><span class="kw">pwr.t.test</span>(<span class="dt">d =</span> <span class="fl">2.300104</span><span class="op">/</span><span class="fl">6.4</span>,</a>
<a class="sourceLine" id="cb50-2" title="2">           <span class="dt">n =</span> <span class="dv">50</span>,</a>
<a class="sourceLine" id="cb50-3" title="3">           <span class="dt">sig.level =</span> <span class="fl">0.05</span>,</a>
<a class="sourceLine" id="cb50-4" title="4">           <span class="dt">type=</span><span class="st">&quot;two.sample&quot;</span>,</a>
<a class="sourceLine" id="cb50-5" title="5">           <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)<span class="op">$</span>power</a></code></pre></div>
<pre><code>## [1] 0.4284243</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" title="1">d &lt;-<span class="st"> </span><span class="dv">2</span><span class="op">*</span><span class="fl">2.300104</span><span class="op">/</span><span class="fl">6.4</span></a>
<a class="sourceLine" id="cb52-2" title="2">d</a></code></pre></div>
<pre><code>## [1] 0.7187825</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" title="1"><span class="kw">pwr.t.test</span>(<span class="dt">d =</span> d,</a>
<a class="sourceLine" id="cb54-2" title="2">           <span class="dt">n =</span> <span class="dv">50</span>,</a>
<a class="sourceLine" id="cb54-3" title="3">           <span class="dt">sig.level =</span> <span class="fl">0.05</span>,</a>
<a class="sourceLine" id="cb54-4" title="4">           <span class="dt">type=</span><span class="st">&quot;two.sample&quot;</span>,</a>
<a class="sourceLine" id="cb54-5" title="5">           <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)<span class="op">$</span>power</a></code></pre></div>
<pre><code>## [1] 0.9450353</code></pre>
<p>We can also compare the results against the analytic solution by Aberson (2019).</p>
<p>First, load the function for a 3-way ANOVA.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" title="1">anova1f_<span class="dv">3</span>&lt;-<span class="cf">function</span>(<span class="dt">m1=</span><span class="ot">NULL</span>,<span class="dt">m2=</span><span class="ot">NULL</span>,<span class="dt">m3=</span><span class="ot">NULL</span>,<span class="dt">s1=</span><span class="ot">NULL</span>,<span class="dt">s2=</span><span class="ot">NULL</span>,<span class="dt">s3=</span><span class="ot">NULL</span>,<span class="dt">n1=</span><span class="ot">NULL</span>,<span class="dt">n2=</span><span class="ot">NULL</span>,<span class="dt">n3=</span><span class="ot">NULL</span>,<span class="dt">alpha=</span>.<span class="dv">05</span>){</a>
<a class="sourceLine" id="cb56-2" title="2">x&lt;-stats<span class="op">::</span><span class="kw">rnorm</span>(n1,m1,s1)</a>
<a class="sourceLine" id="cb56-3" title="3">X&lt;-x</a>
<a class="sourceLine" id="cb56-4" title="4">MEAN&lt;-m1</a>
<a class="sourceLine" id="cb56-5" title="5">SD&lt;-s1</a>
<a class="sourceLine" id="cb56-6" title="6">Z &lt;-<span class="st"> </span>(((X <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(X, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))<span class="op">/</span>stats<span class="op">::</span><span class="kw">sd</span>(X, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))) <span class="op">*</span><span class="st"> </span>SD</a>
<a class="sourceLine" id="cb56-7" title="7">y&lt;-MEAN <span class="op">+</span><span class="st"> </span>Z</a>
<a class="sourceLine" id="cb56-8" title="8">group&lt;-<span class="kw">rep</span>(<span class="st">&quot;A1&quot;</span>,n1)</a>
<a class="sourceLine" id="cb56-9" title="9">l1&lt;-<span class="kw">data.frame</span>(y, group)</a>
<a class="sourceLine" id="cb56-10" title="10">x&lt;-stats<span class="op">::</span><span class="kw">rnorm</span>(n2,m2,s2)</a>
<a class="sourceLine" id="cb56-11" title="11">X&lt;-x</a>
<a class="sourceLine" id="cb56-12" title="12">MEAN&lt;-m2</a>
<a class="sourceLine" id="cb56-13" title="13">SD&lt;-s2</a>
<a class="sourceLine" id="cb56-14" title="14">Z &lt;-<span class="st"> </span>(((X <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(X, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))<span class="op">/</span>stats<span class="op">::</span><span class="kw">sd</span>(X, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))) <span class="op">*</span><span class="st"> </span>SD</a>
<a class="sourceLine" id="cb56-15" title="15">y&lt;-MEAN <span class="op">+</span><span class="st"> </span>Z</a>
<a class="sourceLine" id="cb56-16" title="16">group&lt;-<span class="kw">rep</span>(<span class="st">&quot;A2&quot;</span>,n2)</a>
<a class="sourceLine" id="cb56-17" title="17">l2&lt;-<span class="kw">data.frame</span>(y, group)</a>
<a class="sourceLine" id="cb56-18" title="18">x&lt;-stats<span class="op">::</span><span class="kw">rnorm</span>(n3,m3,s3)</a>
<a class="sourceLine" id="cb56-19" title="19">X&lt;-x</a>
<a class="sourceLine" id="cb56-20" title="20">MEAN&lt;-m3</a>
<a class="sourceLine" id="cb56-21" title="21">SD&lt;-s3</a>
<a class="sourceLine" id="cb56-22" title="22">Z &lt;-<span class="st"> </span>(((X <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(X, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))<span class="op">/</span>stats<span class="op">::</span><span class="kw">sd</span>(X, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))) <span class="op">*</span><span class="st"> </span>SD</a>
<a class="sourceLine" id="cb56-23" title="23">y&lt;-MEAN <span class="op">+</span><span class="st"> </span>Z</a>
<a class="sourceLine" id="cb56-24" title="24">group&lt;-<span class="kw">rep</span>(<span class="st">&quot;A3&quot;</span>,n3)</a>
<a class="sourceLine" id="cb56-25" title="25">l3&lt;-<span class="kw">data.frame</span>(y, group)</a>
<a class="sourceLine" id="cb56-26" title="26">simdat&lt;-<span class="kw">rbind</span>(l1,l2,l3)</a>
<a class="sourceLine" id="cb56-27" title="27">anova&lt;-stats<span class="op">::</span><span class="kw">aov</span>(y<span class="op">~</span>group, <span class="dt">data=</span>simdat)</a>
<a class="sourceLine" id="cb56-28" title="28">anova&lt;-car<span class="op">::</span><span class="kw">Anova</span>(anova, <span class="dt">type=</span><span class="st">&quot;III&quot;</span>)</a>
<a class="sourceLine" id="cb56-29" title="29">SSA&lt;-anova[<span class="dv">2</span>,<span class="dv">1</span>] <span class="co">#column, row</span></a>
<a class="sourceLine" id="cb56-30" title="30">SSwin&lt;-anova[<span class="dv">3</span>,<span class="dv">1</span>]</a>
<a class="sourceLine" id="cb56-31" title="31">dfwin&lt;-anova[<span class="dv">3</span>,<span class="dv">2</span>]</a>
<a class="sourceLine" id="cb56-32" title="32">dfbg&lt;-anova[<span class="dv">2</span>,<span class="dv">2</span>]</a>
<a class="sourceLine" id="cb56-33" title="33">eta2&lt;-SSA<span class="op">/</span>(SSA<span class="op">+</span>SSwin)</a>
<a class="sourceLine" id="cb56-34" title="34">f2&lt;-eta2<span class="op">/</span>(<span class="dv">1</span><span class="op">-</span>eta2)</a>
<a class="sourceLine" id="cb56-35" title="35">lambda&lt;-f2<span class="op">*</span>dfwin</a>
<a class="sourceLine" id="cb56-36" title="36">minusalpha&lt;-<span class="dv">1</span><span class="op">-</span>alpha</a>
<a class="sourceLine" id="cb56-37" title="37">Ft&lt;-stats<span class="op">::</span><span class="kw">qf</span>(minusalpha, dfbg, dfwin)</a>
<a class="sourceLine" id="cb56-38" title="38">power&lt;-<span class="dv">1</span><span class="op">-</span>stats<span class="op">::</span><span class="kw">pf</span>(Ft, dfbg,dfwin,lambda)</a>
<a class="sourceLine" id="cb56-39" title="39"><span class="kw">list</span>(<span class="dt">Power =</span> power)}</a></code></pre></div>
<p>Then we use the function to calculate power.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" title="1"><span class="co">#Initial example, low power</span></a>
<a class="sourceLine" id="cb57-2" title="2"><span class="kw">anova1f_3</span>(<span class="dt">m1=</span><span class="dv">24</span>, <span class="dt">m2=</span><span class="fl">26.2</span>, <span class="dt">m3=</span><span class="fl">26.6</span>, <span class="dt">s1=</span><span class="fl">6.4</span>, <span class="dt">s2=</span><span class="fl">6.4</span>, <span class="dt">s3=</span><span class="fl">6.4</span>, <span class="dt">n1=</span><span class="dv">50</span>, <span class="dt">n2=</span><span class="dv">50</span>, <span class="dt">n3=</span><span class="dv">50</span>, <span class="dt">alpha=</span>.<span class="dv">05</span>)</a></code></pre></div>
<pre><code>## $Power
## [1] 0.4769468</code></pre>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" title="1"><span class="co">#From: Aberson, Christopher L. Applied Power Analysis for the Behavioral Sciences, 2nd Edition. </span></a>
<a class="sourceLine" id="cb59-2" title="2"><span class="co"># $Power [1] 0.4769468</span></a>
<a class="sourceLine" id="cb59-3" title="3"><span class="co">#Later example, based on larger mean difference</span></a>
<a class="sourceLine" id="cb59-4" title="4"><span class="kw">anova1f_3</span>(<span class="dt">m1=</span><span class="op">-</span><span class="fl">2.300104</span>, <span class="dt">m2=</span><span class="dv">0</span>, <span class="dt">m3=</span><span class="fl">2.300104</span>, <span class="dt">s1=</span><span class="fl">6.4</span>, <span class="dt">s2=</span><span class="fl">6.4</span>, <span class="dt">s3=</span><span class="fl">6.4</span>, <span class="dt">n1=</span><span class="dv">50</span>, <span class="dt">n2=</span><span class="dv">50</span>, <span class="dt">n3=</span><span class="dv">50</span>, <span class="dt">alpha=</span>.<span class="dv">05</span>)</a></code></pre></div>
<pre><code>## $Power
## [1] 0.9000112</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" title="1"><span class="co"># $Power [1] 0.9000112</span></a></code></pre></div>

</div>
</div>
<div id="one-way-anova-part-3" class="section level2">
<h2><span class="header-section-number">2.3</span> One-way ANOVA Part 3</h2>
<p>We first repeat the simulation by Brysbaert:</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" title="1"><span class="co"># Simulations to estimate the power of an ANOVA with three unrelated groups</span></a>
<a class="sourceLine" id="cb62-2" title="2"><span class="co"># the effect between the two extreme groups is set to d = .4, the effect for the third group is d = .4 (see below for other situations)</span></a>
<a class="sourceLine" id="cb62-3" title="3"><span class="co"># we use the built-in aov-test command</span></a>
<a class="sourceLine" id="cb62-4" title="4"><span class="co"># give sample sizes (all samples sizes are equal)</span></a>
<a class="sourceLine" id="cb62-5" title="5">N =<span class="st"> </span><span class="dv">90</span></a>
<a class="sourceLine" id="cb62-6" title="6"><span class="co"># give effect size d</span></a>
<a class="sourceLine" id="cb62-7" title="7">d1 =<span class="st"> </span><span class="fl">.4</span> <span class="co">#difference between the extremes</span></a>
<a class="sourceLine" id="cb62-8" title="8">d2 =<span class="st"> </span><span class="fl">.4</span> <span class="co">#third condition goes with the highest extreme</span></a>
<a class="sourceLine" id="cb62-9" title="9"><span class="co"># give number of simulations</span></a>
<a class="sourceLine" id="cb62-10" title="10">nSim =<span class="st"> </span>nsims</a>
<a class="sourceLine" id="cb62-11" title="11"><span class="co"># give alpha levels</span></a>
<a class="sourceLine" id="cb62-12" title="12">alpha1 =<span class="st"> </span><span class="fl">.05</span> <span class="co">#alpha level for the omnibus ANOVA</span></a>
<a class="sourceLine" id="cb62-13" title="13">alpha2 =<span class="st"> </span><span class="fl">.05</span> <span class="co">#alpha level for three post hoc one-tailed t-tests Bonferroni correction</span></a>
<a class="sourceLine" id="cb62-14" title="14"><span class="co"># create progress bar in case it takes a while</span></a>
<a class="sourceLine" id="cb62-15" title="15"><span class="co">#pb &lt;- winProgressBar(title = &quot;progress bar&quot;, min = 0, max = nSim, width = 300)</span></a>
<a class="sourceLine" id="cb62-16" title="16"><span class="co"># create vectors to store p-values</span></a>
<a class="sourceLine" id="cb62-17" title="17">p1 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#p-value omnibus ANOVA</span></a>
<a class="sourceLine" id="cb62-18" title="18">p2 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#p-value first post hoc test</span></a>
<a class="sourceLine" id="cb62-19" title="19">p3 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#p-value second post hoc test</span></a>
<a class="sourceLine" id="cb62-20" title="20">p4 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#p-value third post hoc test</span></a>
<a class="sourceLine" id="cb62-21" title="21">pes1 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#partial eta-squared</span></a>
<a class="sourceLine" id="cb62-22" title="22">pes2 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#partial eta-squared two extreme conditions</span></a>
<a class="sourceLine" id="cb62-23" title="23"><span class="kw">library</span>(lsr)</a>
<a class="sourceLine" id="cb62-24" title="24"><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>nSim){ <span class="co">#for each simulated experiment</span></a>
<a class="sourceLine" id="cb62-25" title="25"> <span class="co"># setWinProgressBar(pb, i, title=paste(round(i/nSim*100, 1), &quot;% done&quot;))</span></a>
<a class="sourceLine" id="cb62-26" title="26">  x&lt;-<span class="kw">rnorm</span>(<span class="dt">n =</span> N, <span class="dt">mean =</span> <span class="dv">0</span>, <span class="dt">sd =</span> <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb62-27" title="27">  y&lt;-<span class="kw">rnorm</span>(<span class="dt">n =</span> N, <span class="dt">mean =</span> d1, <span class="dt">sd =</span> <span class="dv">1</span>) </a>
<a class="sourceLine" id="cb62-28" title="28">  z&lt;-<span class="kw">rnorm</span>(<span class="dt">n =</span> N, <span class="dt">mean =</span> d2, <span class="dt">sd =</span> <span class="dv">1</span>) </a>
<a class="sourceLine" id="cb62-29" title="29">  data =<span class="st"> </span><span class="kw">c</span>(x,y,z)</a>
<a class="sourceLine" id="cb62-30" title="30">  groups=<span class="st"> </span><span class="kw">factor</span>(<span class="kw">rep</span>(letters[<span class="dv">24</span><span class="op">:</span><span class="dv">26</span>], <span class="dt">each =</span> N))</a>
<a class="sourceLine" id="cb62-31" title="31">  test &lt;-<span class="st"> </span><span class="kw">aov</span>(data<span class="op">~</span>groups)</a>
<a class="sourceLine" id="cb62-32" title="32">  pes1[i] &lt;-<span class="st"> </span><span class="kw">etaSquared</span>(test)[<span class="dv">1</span>,<span class="dv">2</span>]</a>
<a class="sourceLine" id="cb62-33" title="33">  p1[i] &lt;-<span class="st"> </span><span class="kw">summary</span>(test)[[<span class="dv">1</span>]][[<span class="st">&quot;Pr(&gt;F)&quot;</span>]][[<span class="dv">1</span>]]</a>
<a class="sourceLine" id="cb62-34" title="34">  p2[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(x,y)<span class="op">$</span>p.value</a>
<a class="sourceLine" id="cb62-35" title="35">  p3[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(x,z)<span class="op">$</span>p.value</a>
<a class="sourceLine" id="cb62-36" title="36">  p4[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(y,z)<span class="op">$</span>p.value</a>
<a class="sourceLine" id="cb62-37" title="37">  data =<span class="st"> </span><span class="kw">c</span>(x,y)</a>
<a class="sourceLine" id="cb62-38" title="38">  groups=<span class="st"> </span><span class="kw">factor</span>(<span class="kw">rep</span>(letters[<span class="dv">24</span><span class="op">:</span><span class="dv">25</span>], <span class="dt">each =</span> N))</a>
<a class="sourceLine" id="cb62-39" title="39">  test &lt;-<span class="st"> </span><span class="kw">aov</span>(data<span class="op">~</span>groups)</a>
<a class="sourceLine" id="cb62-40" title="40">  pes2[i] &lt;-<span class="st"> </span><span class="kw">etaSquared</span>(test)[<span class="dv">1</span>,<span class="dv">2</span>]</a>
<a class="sourceLine" id="cb62-41" title="41">  }</a>
<a class="sourceLine" id="cb62-42" title="42"><span class="co">#close(pb)#close progress bar</span></a>
<a class="sourceLine" id="cb62-43" title="43"><span class="co"># results are as predicted when omnibus ANOVA is significant, t-tests are significant between x and y plus x and z; not significant between y and z</span></a>
<a class="sourceLine" id="cb62-44" title="44"><span class="co">#printing all unique tests (adjusted code by DL)</span></a>
<a class="sourceLine" id="cb62-45" title="45"><span class="kw">sum</span>(p1<span class="op">&lt;</span>alpha1)<span class="op">/</span>nSim</a></code></pre></div>
<pre><code>## [1] 0.78</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" title="1"><span class="kw">sum</span>(p2<span class="op">&lt;</span>alpha2)<span class="op">/</span>nSim</a></code></pre></div>
<pre><code>## [1] 0.76</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" title="1"><span class="kw">sum</span>(p3<span class="op">&lt;</span>alpha2)<span class="op">/</span>nSim</a></code></pre></div>
<pre><code>## [1] 0.71</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" title="1"><span class="kw">sum</span>(p4<span class="op">&lt;</span>alpha2)<span class="op">/</span>nSim</a></code></pre></div>
<pre><code>## [1] 0.02</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" title="1"><span class="kw">mean</span>(pes1)</a></code></pre></div>
<pre><code>## [1] 0.03815007</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" title="1"><span class="kw">mean</span>(pes2)</a></code></pre></div>
<pre><code>## [1] 0.04065763</code></pre>
<div id="three-conditions-replication" class="section level3">
<h3><span class="header-section-number">2.3.1</span> Three conditions replication</h3>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" title="1">K &lt;-<span class="st"> </span><span class="dv">3</span></a>
<a class="sourceLine" id="cb74-2" title="2">mu &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.4</span>, <span class="fl">0.4</span>)</a>
<a class="sourceLine" id="cb74-3" title="3">n &lt;-<span class="st"> </span><span class="dv">90</span></a>
<a class="sourceLine" id="cb74-4" title="4">sd &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb74-5" title="5">r &lt;-<span class="st"> </span><span class="dv">0</span></a>
<a class="sourceLine" id="cb74-6" title="6">design =<span class="kw">paste</span>(K,<span class="st">&quot;b&quot;</span>,<span class="dt">sep=</span><span class="st">&quot;&quot;</span>)</a></code></pre></div>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb75-1" title="1">design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span>string,</a>
<a class="sourceLine" id="cb75-2" title="2">                   <span class="dt">n =</span> n, </a>
<a class="sourceLine" id="cb75-3" title="3">                   <span class="dt">mu =</span> mu, </a>
<a class="sourceLine" id="cb75-4" title="4">                   <span class="dt">sd =</span> sd, </a>
<a class="sourceLine" id="cb75-5" title="5">                   <span class="dt">labelnames =</span> <span class="kw">c</span>(<span class="st">&quot;factor1&quot;</span>, <span class="st">&quot;level1&quot;</span>, <span class="st">&quot;level2&quot;</span>, <span class="st">&quot;level3&quot;</span>))</a>
<a class="sourceLine" id="cb75-6" title="6"><span class="kw">ANOVA_power</span>(design_result, <span class="dt">nsims =</span> nsims)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##               power effect_size
## anova_factor1    75     0.04167
## 
## Power and Effect sizes for contrasts
##                                 power effect_size
## p_factor1_level1_factor1_level2    73     0.38833
## p_factor1_level1_factor1_level3    75     0.40077
## p_factor1_level2_factor1_level3     7     0.01036</code></pre>
</div>
<div id="variation-1" class="section level3">
<h3><span class="header-section-number">2.3.2</span> Variation 1</h3>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb77-1" title="1"><span class="co"># give sample sizes (all samples sizes are equal)</span></a>
<a class="sourceLine" id="cb77-2" title="2">N =<span class="st"> </span><span class="dv">145</span></a>
<a class="sourceLine" id="cb77-3" title="3"><span class="co"># give effect size d</span></a>
<a class="sourceLine" id="cb77-4" title="4">d1 =<span class="st"> </span><span class="fl">.4</span> <span class="co">#difference between the extremes</span></a>
<a class="sourceLine" id="cb77-5" title="5">d2 =<span class="st"> </span><span class="fl">.0</span> <span class="co">#third condition goes with the highest extreme</span></a>
<a class="sourceLine" id="cb77-6" title="6"><span class="co"># give number of simulations</span></a>
<a class="sourceLine" id="cb77-7" title="7">nSim =<span class="st"> </span>nsims</a>
<a class="sourceLine" id="cb77-8" title="8"><span class="co"># give alpha levels</span></a>
<a class="sourceLine" id="cb77-9" title="9">alpha1 =<span class="st"> </span><span class="fl">.05</span> <span class="co">#alpha level for the omnibus ANOVA</span></a>
<a class="sourceLine" id="cb77-10" title="10">alpha2 =<span class="st"> </span><span class="fl">.05</span> <span class="co">#alpha level for three post hoc one-tailed t-tests Bonferroni correction</span></a>
<a class="sourceLine" id="cb77-11" title="11"><span class="co"># create progress bar in case it takes a while</span></a>
<a class="sourceLine" id="cb77-12" title="12"><span class="co">#pb &lt;- winProgressBar(title = &quot;progress bar&quot;, min = 0, max = nSim, width = 300)</span></a>
<a class="sourceLine" id="cb77-13" title="13"><span class="co"># create vectors to store p-values</span></a>
<a class="sourceLine" id="cb77-14" title="14">p1 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#p-value omnibus ANOVA</span></a>
<a class="sourceLine" id="cb77-15" title="15">p2 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#p-value first post hoc test</span></a>
<a class="sourceLine" id="cb77-16" title="16">p3 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#p-value second post hoc test</span></a>
<a class="sourceLine" id="cb77-17" title="17">p4 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#p-value third post hoc test</span></a>
<a class="sourceLine" id="cb77-18" title="18">pes1 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#partial eta-squared</span></a>
<a class="sourceLine" id="cb77-19" title="19">pes2 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#partial eta-squared two extreme conditions</span></a>
<a class="sourceLine" id="cb77-20" title="20"><span class="kw">library</span>(lsr)</a>
<a class="sourceLine" id="cb77-21" title="21"><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>nSim){ <span class="co">#for each simulated experiment</span></a>
<a class="sourceLine" id="cb77-22" title="22"> <span class="co"># setWinProgressBar(pb, i, title=paste(round(i/nSim*100, 1), &quot;% done&quot;))</span></a>
<a class="sourceLine" id="cb77-23" title="23">  x&lt;-<span class="kw">rnorm</span>(<span class="dt">n =</span> N, <span class="dt">mean =</span> <span class="dv">0</span>, <span class="dt">sd =</span> <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb77-24" title="24">  y&lt;-<span class="kw">rnorm</span>(<span class="dt">n =</span> N, <span class="dt">mean =</span> d1, <span class="dt">sd =</span> <span class="dv">1</span>) </a>
<a class="sourceLine" id="cb77-25" title="25">  z&lt;-<span class="kw">rnorm</span>(<span class="dt">n =</span> N, <span class="dt">mean =</span> d2, <span class="dt">sd =</span> <span class="dv">1</span>) </a>
<a class="sourceLine" id="cb77-26" title="26">  data =<span class="st"> </span><span class="kw">c</span>(x,y,z)</a>
<a class="sourceLine" id="cb77-27" title="27">  groups=<span class="st"> </span><span class="kw">factor</span>(<span class="kw">rep</span>(letters[<span class="dv">24</span><span class="op">:</span><span class="dv">26</span>], <span class="dt">each =</span> N))</a>
<a class="sourceLine" id="cb77-28" title="28">  test &lt;-<span class="st"> </span><span class="kw">aov</span>(data<span class="op">~</span>groups)</a>
<a class="sourceLine" id="cb77-29" title="29">  pes1[i] &lt;-<span class="st"> </span><span class="kw">etaSquared</span>(test)[<span class="dv">1</span>,<span class="dv">2</span>]</a>
<a class="sourceLine" id="cb77-30" title="30">  p1[i] &lt;-<span class="st"> </span><span class="kw">summary</span>(test)[[<span class="dv">1</span>]][[<span class="st">&quot;Pr(&gt;F)&quot;</span>]][[<span class="dv">1</span>]]</a>
<a class="sourceLine" id="cb77-31" title="31">  p2[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(x,y)<span class="op">$</span>p.value</a>
<a class="sourceLine" id="cb77-32" title="32">  p3[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(x,z)<span class="op">$</span>p.value</a>
<a class="sourceLine" id="cb77-33" title="33">  p4[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(y,z)<span class="op">$</span>p.value</a>
<a class="sourceLine" id="cb77-34" title="34">  data =<span class="st"> </span><span class="kw">c</span>(x,y)</a>
<a class="sourceLine" id="cb77-35" title="35">  groups=<span class="st"> </span><span class="kw">factor</span>(<span class="kw">rep</span>(letters[<span class="dv">24</span><span class="op">:</span><span class="dv">25</span>], <span class="dt">each =</span> N))</a>
<a class="sourceLine" id="cb77-36" title="36">  test &lt;-<span class="st"> </span><span class="kw">aov</span>(data<span class="op">~</span>groups)</a>
<a class="sourceLine" id="cb77-37" title="37">  pes2[i] &lt;-<span class="st"> </span><span class="kw">etaSquared</span>(test)[<span class="dv">1</span>,<span class="dv">2</span>]</a>
<a class="sourceLine" id="cb77-38" title="38">  }</a>
<a class="sourceLine" id="cb77-39" title="39"><span class="co">#close(pb)#close progress bar</span></a>
<a class="sourceLine" id="cb77-40" title="40"><span class="co"># results are as predicted when omnibus ANOVA is significant, t-tests are significant between x and y plus x and z; not significant between y and z</span></a>
<a class="sourceLine" id="cb77-41" title="41"><span class="co">#printing all unique tests (adjusted code by DL)</span></a>
<a class="sourceLine" id="cb77-42" title="42"><span class="kw">sum</span>(p1<span class="op">&lt;</span>alpha1)<span class="op">/</span>nSim</a></code></pre></div>
<pre><code>## [1] 0.96</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb79-1" title="1"><span class="kw">sum</span>(p2<span class="op">&lt;</span>alpha2)<span class="op">/</span>nSim</a></code></pre></div>
<pre><code>## [1] 0.94</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb81-1" title="1"><span class="kw">sum</span>(p3<span class="op">&lt;</span>alpha2)<span class="op">/</span>nSim</a></code></pre></div>
<pre><code>## [1] 0.09</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb83-1" title="1"><span class="kw">sum</span>(p4<span class="op">&lt;</span>alpha2)<span class="op">/</span>nSim</a></code></pre></div>
<pre><code>## [1] 0.91</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb85-1" title="1"><span class="kw">mean</span>(pes1)</a></code></pre></div>
<pre><code>## [1] 0.03702468</code></pre>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb87-1" title="1"><span class="kw">mean</span>(pes2)</a></code></pre></div>
<pre><code>## [1] 0.04051112</code></pre>
</div>
<div id="three-conditions-replication-1" class="section level3">
<h3><span class="header-section-number">2.3.3</span> Three conditions replication</h3>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb89-1" title="1">K &lt;-<span class="st"> </span><span class="dv">3</span></a>
<a class="sourceLine" id="cb89-2" title="2">mu &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.4</span>, <span class="fl">0.0</span>)</a>
<a class="sourceLine" id="cb89-3" title="3">n &lt;-<span class="st"> </span><span class="dv">145</span></a>
<a class="sourceLine" id="cb89-4" title="4">sd &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb89-5" title="5">r &lt;-<span class="st"> </span><span class="dv">0</span></a>
<a class="sourceLine" id="cb89-6" title="6">design =<span class="kw">paste</span>(K,<span class="st">&quot;b&quot;</span>,<span class="dt">sep=</span><span class="st">&quot;&quot;</span>)</a></code></pre></div>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb90-1" title="1">design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span>string,</a>
<a class="sourceLine" id="cb90-2" title="2">                   <span class="dt">n =</span> n, </a>
<a class="sourceLine" id="cb90-3" title="3">                   <span class="dt">mu =</span> mu, </a>
<a class="sourceLine" id="cb90-4" title="4">                   <span class="dt">sd =</span> sd, </a>
<a class="sourceLine" id="cb90-5" title="5">                   <span class="dt">labelnames =</span> <span class="kw">c</span>(<span class="st">&quot;factor1&quot;</span>, <span class="st">&quot;level1&quot;</span>, <span class="st">&quot;level2&quot;</span>, <span class="st">&quot;level3&quot;</span>))</a>
<a class="sourceLine" id="cb90-6" title="6"><span class="kw">ANOVA_power</span>(design_result, <span class="dt">nsims =</span> nsims)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##               power effect_size
## anova_factor1    94     0.03797
## 
## Power and Effect sizes for contrasts
##                                 power effect_size
## p_factor1_level1_factor1_level2    91     0.38900
## p_factor1_level1_factor1_level3     7    -0.01444
## p_factor1_level2_factor1_level3    91    -0.40198</code></pre>
</div>
<div id="variation-2" class="section level3">
<h3><span class="header-section-number">2.3.4</span> Variation 2</h3>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb92-1" title="1"><span class="co"># give sample sizes (all samples sizes are equal)</span></a>
<a class="sourceLine" id="cb92-2" title="2">N =<span class="st"> </span><span class="dv">82</span></a>
<a class="sourceLine" id="cb92-3" title="3"><span class="co"># give effect size d</span></a>
<a class="sourceLine" id="cb92-4" title="4">d1 =<span class="st"> </span><span class="fl">.4</span> <span class="co">#difference between the extremes</span></a>
<a class="sourceLine" id="cb92-5" title="5">d2 =<span class="st"> </span><span class="fl">.2</span> <span class="co">#third condition goes with the highest extreme</span></a>
<a class="sourceLine" id="cb92-6" title="6"><span class="co"># give number of simulations</span></a>
<a class="sourceLine" id="cb92-7" title="7">nSim =<span class="st"> </span>nsims</a>
<a class="sourceLine" id="cb92-8" title="8"><span class="co"># give alpha levels</span></a>
<a class="sourceLine" id="cb92-9" title="9">alpha1 =<span class="st"> </span><span class="fl">.05</span> <span class="co">#alpha level for the omnibus ANOVA</span></a>
<a class="sourceLine" id="cb92-10" title="10">alpha2 =<span class="st"> </span><span class="fl">.05</span> <span class="co">#alpha level for three post hoc one-tailed t-tests Bonferroni correction</span></a>
<a class="sourceLine" id="cb92-11" title="11"><span class="co"># create progress bar in case it takes a while</span></a>
<a class="sourceLine" id="cb92-12" title="12"><span class="co">#pb &lt;- winProgressBar(title = &quot;progress bar&quot;, min = 0, max = nSim, width = 300)</span></a>
<a class="sourceLine" id="cb92-13" title="13"><span class="co"># create vectors to store p-values</span></a>
<a class="sourceLine" id="cb92-14" title="14">p1 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#p-value omnibus ANOVA</span></a>
<a class="sourceLine" id="cb92-15" title="15">p2 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#p-value first post hoc test</span></a>
<a class="sourceLine" id="cb92-16" title="16">p3 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#p-value second post hoc test</span></a>
<a class="sourceLine" id="cb92-17" title="17">p4 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#p-value third post hoc test</span></a>
<a class="sourceLine" id="cb92-18" title="18">pes1 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#partial eta-squared</span></a>
<a class="sourceLine" id="cb92-19" title="19">pes2 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#partial eta-squared two extreme conditions</span></a>
<a class="sourceLine" id="cb92-20" title="20"><span class="kw">library</span>(lsr)</a>
<a class="sourceLine" id="cb92-21" title="21"><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>nSim){ <span class="co">#for each simulated experiment</span></a>
<a class="sourceLine" id="cb92-22" title="22"> <span class="co"># setWinProgressBar(pb, i, title=paste(round(i/nSim*100, 1), &quot;% done&quot;))</span></a>
<a class="sourceLine" id="cb92-23" title="23">  x&lt;-<span class="kw">rnorm</span>(<span class="dt">n =</span> N, <span class="dt">mean =</span> <span class="dv">0</span>, <span class="dt">sd =</span> <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb92-24" title="24">  y&lt;-<span class="kw">rnorm</span>(<span class="dt">n =</span> N, <span class="dt">mean =</span> d1, <span class="dt">sd =</span> <span class="dv">1</span>) </a>
<a class="sourceLine" id="cb92-25" title="25">  z&lt;-<span class="kw">rnorm</span>(<span class="dt">n =</span> N, <span class="dt">mean =</span> d2, <span class="dt">sd =</span> <span class="dv">1</span>) </a>
<a class="sourceLine" id="cb92-26" title="26">  data =<span class="st"> </span><span class="kw">c</span>(x,y,z)</a>
<a class="sourceLine" id="cb92-27" title="27">  groups=<span class="st"> </span><span class="kw">factor</span>(<span class="kw">rep</span>(letters[<span class="dv">24</span><span class="op">:</span><span class="dv">26</span>], <span class="dt">each =</span> N))</a>
<a class="sourceLine" id="cb92-28" title="28">  test &lt;-<span class="st"> </span><span class="kw">aov</span>(data<span class="op">~</span>groups)</a>
<a class="sourceLine" id="cb92-29" title="29">  pes1[i] &lt;-<span class="st"> </span><span class="kw">etaSquared</span>(test)[<span class="dv">1</span>,<span class="dv">2</span>]</a>
<a class="sourceLine" id="cb92-30" title="30">  p1[i] &lt;-<span class="st"> </span><span class="kw">summary</span>(test)[[<span class="dv">1</span>]][[<span class="st">&quot;Pr(&gt;F)&quot;</span>]][[<span class="dv">1</span>]]</a>
<a class="sourceLine" id="cb92-31" title="31">  p2[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(x,y)<span class="op">$</span>p.value</a>
<a class="sourceLine" id="cb92-32" title="32">  p3[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(x,z)<span class="op">$</span>p.value</a>
<a class="sourceLine" id="cb92-33" title="33">  p4[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(y,z)<span class="op">$</span>p.value</a>
<a class="sourceLine" id="cb92-34" title="34">  data =<span class="st"> </span><span class="kw">c</span>(x,y)</a>
<a class="sourceLine" id="cb92-35" title="35">  groups=<span class="st"> </span><span class="kw">factor</span>(<span class="kw">rep</span>(letters[<span class="dv">24</span><span class="op">:</span><span class="dv">25</span>], <span class="dt">each =</span> N))</a>
<a class="sourceLine" id="cb92-36" title="36">  test &lt;-<span class="st"> </span><span class="kw">aov</span>(data<span class="op">~</span>groups)</a>
<a class="sourceLine" id="cb92-37" title="37">  pes2[i] &lt;-<span class="st"> </span><span class="kw">etaSquared</span>(test)[<span class="dv">1</span>,<span class="dv">2</span>]</a>
<a class="sourceLine" id="cb92-38" title="38">  }</a>
<a class="sourceLine" id="cb92-39" title="39"><span class="co">#close(pb)#close progress bar</span></a>
<a class="sourceLine" id="cb92-40" title="40"><span class="co"># results are as predicted when omnibus ANOVA is significant, t-tests are significant between x and y plus x and z; not significant between y and z</span></a>
<a class="sourceLine" id="cb92-41" title="41"><span class="co">#printing all unique tests (adjusted code by DL)</span></a>
<a class="sourceLine" id="cb92-42" title="42"><span class="kw">sum</span>(p1<span class="op">&lt;</span>alpha1)<span class="op">/</span>nSim</a></code></pre></div>
<pre><code>## [1] 0.59</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb94-1" title="1"><span class="kw">sum</span>(p2<span class="op">&lt;</span>alpha2)<span class="op">/</span>nSim</a></code></pre></div>
<pre><code>## [1] 0.7</code></pre>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb96-1" title="1"><span class="kw">sum</span>(p3<span class="op">&lt;</span>alpha2)<span class="op">/</span>nSim</a></code></pre></div>
<pre><code>## [1] 0.23</code></pre>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb98-1" title="1"><span class="kw">sum</span>(p4<span class="op">&lt;</span>alpha2)<span class="op">/</span>nSim</a></code></pre></div>
<pre><code>## [1] 0.23</code></pre>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb100-1" title="1"><span class="kw">mean</span>(pes1)</a></code></pre></div>
<pre><code>## [1] 0.03423781</code></pre>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb102-1" title="1"><span class="kw">mean</span>(pes2)</a></code></pre></div>
<pre><code>## [1] 0.04434622</code></pre>
</div>
<div id="three-conditions-replication-2" class="section level3">
<h3><span class="header-section-number">2.3.5</span> Three conditions replication</h3>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb104-1" title="1">K &lt;-<span class="st"> </span><span class="dv">3</span></a>
<a class="sourceLine" id="cb104-2" title="2">mu &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.4</span>, <span class="fl">0.2</span>)</a>
<a class="sourceLine" id="cb104-3" title="3">n &lt;-<span class="st"> </span><span class="dv">82</span></a>
<a class="sourceLine" id="cb104-4" title="4">sd &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb104-5" title="5">design =<span class="kw">paste</span>(K,<span class="st">&quot;b&quot;</span>,<span class="dt">sep=</span><span class="st">&quot;&quot;</span>)</a></code></pre></div>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb105-1" title="1">design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span>string,</a>
<a class="sourceLine" id="cb105-2" title="2">                   <span class="dt">n =</span> n, </a>
<a class="sourceLine" id="cb105-3" title="3">                   <span class="dt">mu =</span> mu, </a>
<a class="sourceLine" id="cb105-4" title="4">                   <span class="dt">sd =</span> sd, </a>
<a class="sourceLine" id="cb105-5" title="5">                   <span class="dt">labelnames =</span> <span class="kw">c</span>(<span class="st">&quot;factor1&quot;</span>, <span class="st">&quot;level1&quot;</span>, <span class="st">&quot;level2&quot;</span>, <span class="st">&quot;level3&quot;</span>))</a>
<a class="sourceLine" id="cb105-6" title="6"><span class="kw">ANOVA_power</span>(design_result, <span class="dt">nsims =</span> nsims)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##               power effect_size
## anova_factor1    56     0.02967
## 
## Power and Effect sizes for contrasts
##                                 power effect_size
## p_factor1_level1_factor1_level2    71      0.3776
## p_factor1_level1_factor1_level3    19      0.1727
## p_factor1_level2_factor1_level3    22     -0.2094</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="repeated-measures-anova.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["SuperpowerValidation.pdf", "SuperpowerValidation.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
