<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Repeated Measures-ANOVA | Validation of Superpower</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.13 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Repeated Measures-ANOVA | Validation of Superpower" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Repeated Measures-ANOVA | Validation of Superpower" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Aaron Caldwell &amp; Daniël Lakens" />


<meta name="date" content="2019-09-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="one-way-anova.html"/>
<link rel="next" href="mixed-anova.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="one-way-anova.html"><a href="one-way-anova.html"><i class="fa fa-check"></i><b>2</b> One-way ANOVA</a><ul>
<li class="chapter" data-level="2.1" data-path="one-way-anova.html"><a href="one-way-anova.html#validation-of-power-in-one-way-anova-part-1"><i class="fa fa-check"></i><b>2.1</b> Validation of Power in One-Way ANOVA Part 1</a><ul>
<li class="chapter" data-level="2.1.1" data-path="one-way-anova.html"><a href="one-way-anova.html#two-conditions"><i class="fa fa-check"></i><b>2.1.1</b> Two conditions</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="one-way-anova.html"><a href="one-way-anova.html#one-way-anova-part-2-brysbaert-example"><i class="fa fa-check"></i><b>2.2</b> One-way ANOVA Part 2: Brysbaert example</a><ul>
<li class="chapter" data-level="2.2.1" data-path="one-way-anova.html"><a href="one-way-anova.html#three-conditions"><i class="fa fa-check"></i><b>2.2.1</b> Three conditions</a></li>
<li class="chapter" data-level="2.2.2" data-path="one-way-anova.html"><a href="one-way-anova.html#power-for-simple-effects"><i class="fa fa-check"></i><b>2.2.2</b> Power for simple effects</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="one-way-anova.html"><a href="one-way-anova.html#one-way-anova-part-3"><i class="fa fa-check"></i><b>2.3</b> One-way ANOVA Part 3</a><ul>
<li class="chapter" data-level="2.3.1" data-path="one-way-anova.html"><a href="one-way-anova.html#three-conditions-replication"><i class="fa fa-check"></i><b>2.3.1</b> Three conditions replication</a></li>
<li class="chapter" data-level="2.3.2" data-path="one-way-anova.html"><a href="one-way-anova.html#variation-1"><i class="fa fa-check"></i><b>2.3.2</b> Variation 1</a></li>
<li class="chapter" data-level="2.3.3" data-path="one-way-anova.html"><a href="one-way-anova.html#three-conditions-replication-1"><i class="fa fa-check"></i><b>2.3.3</b> Three conditions replication</a></li>
<li class="chapter" data-level="2.3.4" data-path="one-way-anova.html"><a href="one-way-anova.html#variation-2"><i class="fa fa-check"></i><b>2.3.4</b> Variation 2</a></li>
<li class="chapter" data-level="2.3.5" data-path="one-way-anova.html"><a href="one-way-anova.html#three-conditions-replication-2"><i class="fa fa-check"></i><b>2.3.5</b> Three conditions replication</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html"><i class="fa fa-check"></i><b>3</b> Repeated Measures-ANOVA</a><ul>
<li class="chapter" data-level="3.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#part-1"><i class="fa fa-check"></i><b>3.1</b> Part 1</a><ul>
<li class="chapter" data-level="3.1.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#two-conditions-medium-effect-size"><i class="fa fa-check"></i><b>3.1.1</b> Two conditions, medium effect size</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#repeated-measures-anova-part-2"><i class="fa fa-check"></i><b>3.2</b> Repeated Measures-ANOVA Part 2</a><ul>
<li class="chapter" data-level="3.2.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#the-relation-between-cohens-f-and-cohens-d"><i class="fa fa-check"></i><b>3.2.1</b> The relation between Cohen’s f and Cohen’s d</a></li>
<li class="chapter" data-level="3.2.2" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#three-within-conditions-medium-effect-size"><i class="fa fa-check"></i><b>3.2.2</b> Three within conditions, medium effect size</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#repeated-measures-anova-part-3"><i class="fa fa-check"></i><b>3.3</b> Repeated Measures-ANOVA Part 3</a></li>
<li class="chapter" data-level="3.4" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#reproducing-brysbaert"><i class="fa fa-check"></i><b>3.4</b> Reproducing Brysbaert</a></li>
<li class="chapter" data-level="3.5" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#reproducing-brysbaert-variation-1-changing-correlation"><i class="fa fa-check"></i><b>3.5</b> Reproducing Brysbaert Variation 1 Changing Correlation</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="mixed-anova.html"><a href="mixed-anova.html"><i class="fa fa-check"></i><b>4</b> Mixed ANOVA</a><ul>
<li class="chapter" data-level="4.1" data-path="mixed-anova.html"><a href="mixed-anova.html#part-1-two-by-two-anova-within-between-design"><i class="fa fa-check"></i><b>4.1</b> Part 1: Two by two ANOVA, within-between design</a><ul>
<li class="chapter" data-level="4.1.1" data-path="mixed-anova.html"><a href="mixed-anova.html#two-by-two-anova-within-between-design-variation-1"><i class="fa fa-check"></i><b>4.1.1</b> Two by two ANOVA, within-between design Variation 1</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="mixed-anova.html"><a href="mixed-anova.html#part-2-two-by-two-anova-within-within-design"><i class="fa fa-check"></i><b>4.2</b> Part 2: Two by two ANOVA, within-within design</a><ul>
<li class="chapter" data-level="4.2.1" data-path="mixed-anova.html"><a href="mixed-anova.html#examine-variation-of-means-and-correlation"><i class="fa fa-check"></i><b>4.2.1</b> Examine variation of means and correlation</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="mixed-anova.html"><a href="mixed-anova.html#part-3-two-by-two-anova-within-design"><i class="fa fa-check"></i><b>4.3</b> Part 3: Two by two ANOVA, within design</a></li>
<li class="chapter" data-level="4.4" data-path="mixed-anova.html"><a href="mixed-anova.html#simple-example-2x2-within-design"><i class="fa fa-check"></i><b>4.4</b> Simple example: 2x2 within design</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="error-control-in-exploratory-anova.html"><a href="error-control-in-exploratory-anova.html"><i class="fa fa-check"></i><b>5</b> Error Control in Exploratory ANOVA</a></li>
<li class="chapter" data-level="6" data-path="power-for-interactions.html"><a href="power-for-interactions.html"><i class="fa fa-check"></i><b>6</b> Power for Interactions</a></li>
<li class="chapter" data-level="7" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html"><i class="fa fa-check"></i><b>7</b> Analytic Power Functions</a><ul>
<li class="chapter" data-level="7.1" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html#one-way-between-subject-anova"><i class="fa fa-check"></i><b>7.1</b> One-Way Between Subject ANOVA</a></li>
<li class="chapter" data-level="7.2" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html#two-way-between-subject-interaction"><i class="fa fa-check"></i><b>7.2</b> Two-way Between Subject Interaction</a></li>
<li class="chapter" data-level="7.3" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html#x3-between-subject-anova"><i class="fa fa-check"></i><b>7.3</b> 3x3 Between Subject ANOVA</a></li>
<li class="chapter" data-level="7.4" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html#two-by-two-anova-within-design"><i class="fa fa-check"></i><b>7.4</b> Two by two ANOVA, within design</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="power-curve.html"><a href="power-curve.html"><i class="fa fa-check"></i><b>8</b> Power Curve</a></li>
<li class="chapter" data-level="9" data-path="explore-increase-in-effect-size-for-moderated-interactions-.html"><a href="explore-increase-in-effect-size-for-moderated-interactions-.html"><i class="fa fa-check"></i><b>9</b> Explore increase in effect size for moderated interactions.</a><ul>
<li class="chapter" data-level="9.1" data-path="explore-increase-in-effect-size-for-moderated-interactions-.html"><a href="explore-increase-in-effect-size-for-moderated-interactions-.html#explore-increase-in-effect-size-for-cross-over-interactions."><i class="fa fa-check"></i><b>9.1</b> Explore increase in effect size for cross-over interactions.</a></li>
<li class="chapter" data-level="9.2" data-path="explore-increase-in-effect-size-for-moderated-interactions-.html"><a href="explore-increase-in-effect-size-for-moderated-interactions-.html#explore-increase-in-correlation-in-moderated-interactions."><i class="fa fa-check"></i><b>9.2</b> Explore increase in correlation in moderated interactions.</a></li>
<li class="chapter" data-level="9.3" data-path="explore-increase-in-effect-size-for-moderated-interactions-.html"><a href="explore-increase-in-effect-size-for-moderated-interactions-.html#increasing-correlation-in-on-factor-decreases-power-in-second-factor"><i class="fa fa-check"></i><b>9.3</b> Increasing correlation in on factor decreases power in second factor</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="analytic-power-for-three-way-interactions.html"><a href="analytic-power-for-three-way-interactions.html"><i class="fa fa-check"></i><b>10</b> Analytic Power for Three-way Interactions</a></li>
<li class="chapter" data-level="11" data-path="power-for-design-variations.html"><a href="power-for-design-variations.html"><i class="fa fa-check"></i><b>11</b> Power for Design Variations</a><ul>
<li class="chapter" data-level="11.1" data-path="power-for-design-variations.html"><a href="power-for-design-variations.html#within-designs"><i class="fa fa-check"></i><b>11.1</b> Within Designs</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="setting-the-correlation-matrix.html"><a href="setting-the-correlation-matrix.html"><i class="fa fa-check"></i><b>12</b> Setting the Correlation Matrix</a></li>
<li class="chapter" data-level="13" data-path="validation-of-effect-size-estimates-for-one-way-anova.html"><a href="validation-of-effect-size-estimates-for-one-way-anova.html"><i class="fa fa-check"></i><b>13</b> Validation of Effect Size Estimates for One-Way ANOVA</a><ul>
<li class="chapter" data-level="13.1" data-path="validation-of-effect-size-estimates-for-one-way-anova.html"><a href="validation-of-effect-size-estimates-for-one-way-anova.html#three-conditions-small-effect-size"><i class="fa fa-check"></i><b>13.1</b> Three conditions, small effect size</a></li>
<li class="chapter" data-level="13.2" data-path="validation-of-effect-size-estimates-for-one-way-anova.html"><a href="validation-of-effect-size-estimates-for-one-way-anova.html#four-conditions-medium-effect-size"><i class="fa fa-check"></i><b>13.2</b> Four conditions, medium effect size</a></li>
<li class="chapter" data-level="13.3" data-path="validation-of-effect-size-estimates-for-one-way-anova.html"><a href="validation-of-effect-size-estimates-for-one-way-anova.html#two-conditions-large-effect-size"><i class="fa fa-check"></i><b>13.3</b> Two conditions, large effect size</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Validation of Superpower</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="repeated-measures-anova" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Repeated Measures-ANOVA</h1>
<div id="part-1" class="section level2">
<h2><span class="header-section-number">3.1</span> Part 1</h2>
<p>In a repeated measures design multiple observations are collected from the same participants. In the simplest case, where there are two repeated observations, a repeated measures ANOVA equals a dependent or paired <em>t</em>-test. The difference compared to a between subject design is that repeated measures can be correlated, and in psychology, they often are. Let’s first explore the impact of this correlation on the power of a repeated measures ANOVA.</p>
<div id="two-conditions-medium-effect-size" class="section level3">
<h3><span class="header-section-number">3.1.1</span> Two conditions, medium effect size</h3>
<p>To illustrate the effect of correated observations, we start by simulating data for a medium effect size for a dependent (or paired, or within-subject) <em>t</em>-test. Let’s first look at G*power. If we want to perform an a-priori power analysis, we are asked to fill in the effect size dz. As Cohen (1988) writes, “The Z subscript is used to emphasize the fact that our raw score unit is no longer X or Y, but Z”, where Z are the difference scores of X-Y.</p>
<p><img src="screenshots/gpower_9.png" /></p>
<p>Within designs can have greater power to detect differences than between designs because the values are correlated, and a within design requires less participants because each participant provides multiple observations. One difference between an independent <em>t</em>-test and a dependent <em>t</em>-test is that an independent <em>t</em>-test has 2(n-1) degrees of freedom, while a dependent <em>t</em>-test has (n-1) degrees of freedom. The sample size needed in a two-group within-design (NW) relative to the sample needed in two-group between-designs (NB), assuming normal distributions, and ignoring the difference in degrees of freedom between the two types of tests, is (from Maxwell &amp; Delaney, 2004, p. 561, formula 45):</p>
<p><span class="math inline">\(N_{W}=\frac{N_{B}(1-\rho)}{2}\)</span></p>
<p>The division by 2 in the equation is due to the fact that in a two-condition within design every participant provides two data-points. The extent to which this reduces the sample size compared to a between-subject design depends on the correlation (<em>r</em>) between the two dependent variables, as indicated by the 1-r part of the equation. If the correlation is 0, a within-subject design needs half as many participants as a between-subject design (e.g., 64 instead 128 participants), simply because every participants provides 2 datapoints. The higher the correlation, the larger the relative benefit of within designs, and whenever the correlation is negative (up to -1) the relative benefit disappears.</p>
<p>Whereas in an independent <em>t</em>-test the two observations are uncorrelated, in a within design the observations are correlated. This has an effect on the standard deviation of the difference scores. In turn, because the standardized effect size is the mean difference divided by the standard deviation of the difference scores, the correlation has an effect on the standardized mean difference in a within design, Cohen’s dz. The relation, as Cohen (1988, formula 2.3.7) explains, is:</p>
<p><span class="math inline">\(\sigma_{z}=\sigma\sqrt{2(1-\rho)}\)</span></p>
<p>Therefore, the relation between dz and d is <span class="math inline">\(\sqrt{2(1-\rho)}\)</span>. As Cohen (1988) writes: "In other words, a given difference between population means for matched (dependent) samples is standardized by a value which is <span class="math inline">\(\sqrt{2(1-\rho)}\)</span> as large as would be the case were they independent. If we enter a correlation of 0.5 in the formula, we get <span class="math inline">\(\sqrt{2(0.5)}=1\)</span>. In other words, when the correlation is 0.5, d = dz. When there is a strong correlation between dependent variables, for example r = 0.9, we get <span class="math inline">\(d=d_{z}\sqrt{2(1-0.9)}\)</span>, and a dz of 1 would be a d = 0.45. Reversely, <span class="math inline">\(d_{z}=\frac{d}{\sqrt{2(1-r)}}\)</span>, so with a r = 0.9, a d of 1 would be a dz = 2.24. Some consider this increase in dz compared to d when observations are strongly correlated an ‘inflation’ when estimating effect sizes, but since the reduction in the standard deviation of the difference scores due to the correlation makes it easier to distinguish signal from noise in a hypothesis test, it leads to a clear power benefit.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb107-1" title="1"><span class="co"># Check sample size formula Maxwell</span></a>
<a class="sourceLine" id="cb107-2" title="2"><span class="co"># Power is pretty similar with n/2, same d (assuming r = 0.5). </span></a>
<a class="sourceLine" id="cb107-3" title="3"><span class="co"># Small differences due to df = 2(n-1) vs df = n-1</span></a>
<a class="sourceLine" id="cb107-4" title="4"><span class="kw">pwr.t.test</span>(<span class="dt">d =</span> <span class="fl">0.05</span>,</a>
<a class="sourceLine" id="cb107-5" title="5">           <span class="dt">n =</span> <span class="kw">c</span>(<span class="dv">2000</span>, <span class="dv">4000</span>, <span class="dv">8000</span>),</a>
<a class="sourceLine" id="cb107-6" title="6">           <span class="dt">sig.level =</span> <span class="fl">0.05</span>,</a>
<a class="sourceLine" id="cb107-7" title="7">           <span class="dt">type =</span> <span class="st">&quot;two.sample&quot;</span>,</a>
<a class="sourceLine" id="cb107-8" title="8">           <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 2000, 4000, 8000
##               d = 0.05
##       sig.level = 0.05
##           power = 0.3524674, 0.6086764, 0.8853424
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb109-1" title="1"><span class="kw">pwr.t.test</span>(<span class="dt">d =</span> <span class="fl">0.05</span>,</a>
<a class="sourceLine" id="cb109-2" title="2">           <span class="dt">n =</span> <span class="kw">c</span>(<span class="dv">1000</span>, <span class="dv">2000</span>, <span class="dv">4000</span>),</a>
<a class="sourceLine" id="cb109-3" title="3">           <span class="dt">sig.level =</span> <span class="fl">0.05</span>,</a>
<a class="sourceLine" id="cb109-4" title="4">           <span class="dt">type =</span> <span class="st">&quot;paired&quot;</span>,</a>
<a class="sourceLine" id="cb109-5" title="5">           <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##      Paired t test power calculation 
## 
##               n = 1000, 2000, 4000
##               d = 0.05
##       sig.level = 0.05
##           power = 0.3520450, 0.6083669, 0.8852320
##     alternative = two.sided
## 
## NOTE: n is number of *pairs*</code></pre>
<p>There is no equivalent fz for Cohen’s f for a within subject ANOVA. For two groups, we can directly compute Cohen’s f from Cohen’s d for two groups, as Cohen (1988) describes, because f = 1/2d. For a d = 0.5, f = 0.25. In Gpower we can run a 2 group within-subject power analysis for ANOVA. We plan for 80% power, and reproduce the anaysis above for the dependent <em>t</em>-test. This works because the correlation is set to 0.5, when d = dz, and thus the transformation of f=1/2d works.</p>
<p><img src="screenshots/gpower_1.png" /></p>
<p>If we change the correlation to 0.7 and keep all other settings the same, the repeated measure a-priori power analysis yields a sample of 21. The correlation increases the power for the test.</p>
<p><img src="screenshots/gpower_11.png" /></p>
<p>To reproduce this analysis in Gpower with a dependent <em>t</em>-test we need to change dz following the formula above, <span class="math inline">\(d_{z}=\frac{0.5}{\sqrt{2(1-0.7)}}\)</span>, which yields dz = 0.6454972. If we enter this value in Gpower for an a-priori power analysis, we get the exact same results (as we should, since an repeated measures ANOVA with 2 groups equals a dependent <em>t</em>-test). This example illustrates that the correlation between dependent variables always factors into a power analysis, both for a dependent <em>t</em>-test, and for a repeated measures ANOVA. Because a dependent <em>t</em>-test uses dz the correlation might be less visible, but given the relation between d and dz, the correlation is always taken into account and can greatly improve power for within designs compared to between designs.</p>
<p><img src="screenshots/gpower_10.png" /></p>
<p>We can perform both these power analyses using simuations as well. We set groups to 2 for the simulation, n = 34 (which should give 80.777 power, according to the g*power program), a correlation among repeated measures of 0.5, and an alpha of 0.05. In this case, we simulate data with means -0.25 and 0.25, and set the sd to 1. This means we have a mean difference of 0.5, and a Cohen’s d of 0.5/1 = 0.5. In the first example, we set the correlation to 0.5, and the result should be 80.77% power, and an effect size estimate of 0.5 for the simple effect. We also calculate partial eta-squared for the ANOVA, which equals <span class="math inline">\(\frac{f^2}{f^2+1}\)</span>, or 0.05882353.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb111-1" title="1">K &lt;-<span class="st"> </span><span class="dv">2</span></a>
<a class="sourceLine" id="cb111-2" title="2">n &lt;-<span class="st"> </span><span class="dv">34</span></a>
<a class="sourceLine" id="cb111-3" title="3">sd &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb111-4" title="4">r &lt;-<span class="st"> </span><span class="fl">0.5</span></a>
<a class="sourceLine" id="cb111-5" title="5">alpha =<span class="st"> </span><span class="fl">0.05</span></a>
<a class="sourceLine" id="cb111-6" title="6">f &lt;-<span class="st"> </span><span class="fl">0.25</span></a>
<a class="sourceLine" id="cb111-7" title="7">f2 &lt;-<span class="st"> </span>f<span class="op">^</span><span class="dv">2</span></a>
<a class="sourceLine" id="cb111-8" title="8">ES &lt;-<span class="st"> </span>f2<span class="op">/</span>(f2<span class="op">+</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb111-9" title="9">ES</a></code></pre></div>
<pre><code>## [1] 0.05882353</code></pre>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb113-1" title="1">mu &lt;-<span class="st"> </span><span class="kw">mu_from_ES</span>(<span class="dt">K =</span> K, <span class="dt">ES =</span> ES)</a>
<a class="sourceLine" id="cb113-2" title="2">design =<span class="kw">paste</span>(K,<span class="st">&quot;w&quot;</span>,<span class="dt">sep=</span><span class="st">&quot;&quot;</span>)</a>
<a class="sourceLine" id="cb113-3" title="3">labelnames &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;speed&quot;</span>, <span class="st">&quot;fast&quot;</span>, <span class="st">&quot;slow&quot;</span>)</a>
<a class="sourceLine" id="cb113-4" title="4">design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> design,</a>
<a class="sourceLine" id="cb113-5" title="5">                   <span class="dt">n =</span> n, </a>
<a class="sourceLine" id="cb113-6" title="6">                   <span class="dt">mu =</span> mu, </a>
<a class="sourceLine" id="cb113-7" title="7">                   <span class="dt">sd =</span> sd, </a>
<a class="sourceLine" id="cb113-8" title="8">                   <span class="dt">r =</span> r, </a>
<a class="sourceLine" id="cb113-9" title="9">                   <span class="dt">labelnames =</span> labelnames)</a>
<a class="sourceLine" id="cb113-10" title="10">alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span></a>
<a class="sourceLine" id="cb113-11" title="11">simulation_result &lt;-<span class="st"> </span><span class="kw">ANOVA_power</span>(design_result, <span class="dt">nsims =</span> nsims)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##             power effect_size
## anova_speed    79      0.2104
## 
## Power and Effect sizes for contrasts
##                         power effect_size
## p_speed_fast_speed_slow    79       0.502
## 
## Within-Subject Factors Included: Check MANOVA Results</code></pre>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb115-1" title="1">exact_result &lt;-<span class="st"> </span><span class="kw">ANOVA_exact</span>(design_result, <span class="dt">alpha_level =</span> alpha_level)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##       power partial_eta_squared cohen_f non_centrality
## speed 80.78              0.2048  0.5075            8.5
## 
## Power and Effect sizes for contrasts
##                         power effect_size
## p_speed_fast_speed_slow 80.78         0.5</code></pre>
<p>The results of the simulation are indeed very close to 80.777%. Note that the simulation calculates Cohen’s dz effect sizes for paired comparisons - which here given the correlation of 0.5 is also 0.5 for a medium effect size.</p>
<p>We should see a larger dz if we increase the correlation, keeping the sample size the same, following the example in Gpower above. We repeat the simulation, and the only difference is a correlation between dependent variables of 0.7. This should yield an effect size dz = 0.6454972.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb117-1" title="1">K &lt;-<span class="st"> </span><span class="dv">2</span></a>
<a class="sourceLine" id="cb117-2" title="2">n &lt;-<span class="st"> </span><span class="dv">21</span></a>
<a class="sourceLine" id="cb117-3" title="3">sd &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb117-4" title="4">r &lt;-<span class="st"> </span><span class="fl">0.7</span></a>
<a class="sourceLine" id="cb117-5" title="5">alpha =<span class="st"> </span><span class="fl">0.05</span></a>
<a class="sourceLine" id="cb117-6" title="6">f &lt;-<span class="st"> </span><span class="fl">0.25</span></a>
<a class="sourceLine" id="cb117-7" title="7">f2 &lt;-<span class="st"> </span>f<span class="op">^</span><span class="dv">2</span></a>
<a class="sourceLine" id="cb117-8" title="8">ES &lt;-<span class="st"> </span>f2<span class="op">/</span>(f2<span class="op">+</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb117-9" title="9">ES</a></code></pre></div>
<pre><code>## [1] 0.05882353</code></pre>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb119-1" title="1">mu &lt;-<span class="st"> </span><span class="kw">mu_from_ES</span>(<span class="dt">K =</span> K, <span class="dt">ES =</span> ES)</a>
<a class="sourceLine" id="cb119-2" title="2">design =<span class="st"> </span><span class="kw">paste</span>(K,<span class="st">&quot;w&quot;</span>,<span class="dt">sep=</span><span class="st">&quot;&quot;</span>)</a>
<a class="sourceLine" id="cb119-3" title="3">labelnames &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;speed&quot;</span>, <span class="st">&quot;fast&quot;</span>, <span class="st">&quot;slow&quot;</span>)</a>
<a class="sourceLine" id="cb119-4" title="4">design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> design,</a>
<a class="sourceLine" id="cb119-5" title="5">                   <span class="dt">n =</span> n, </a>
<a class="sourceLine" id="cb119-6" title="6">                   <span class="dt">mu =</span> mu, </a>
<a class="sourceLine" id="cb119-7" title="7">                   <span class="dt">sd =</span> sd, </a>
<a class="sourceLine" id="cb119-8" title="8">                   <span class="dt">r =</span> r, </a>
<a class="sourceLine" id="cb119-9" title="9">                   <span class="dt">labelnames =</span> labelnames)</a>
<a class="sourceLine" id="cb119-10" title="10">alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span></a>
<a class="sourceLine" id="cb119-11" title="11">design_result<span class="op">$</span>sigmatrix</a></code></pre></div>
<pre><code>##      fast slow
## fast  1.0  0.7
## slow  0.7  1.0</code></pre>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb121-1" title="1">simulation_result &lt;-<span class="st"> </span><span class="kw">ANOVA_power</span>(design_result, <span class="dt">nsims =</span> nsims)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##             power effect_size
## anova_speed    84      0.3314
## 
## Power and Effect sizes for contrasts
##                         power effect_size
## p_speed_fast_speed_slow    84      0.6998
## 
## Within-Subject Factors Included: Check MANOVA Results</code></pre>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb123-1" title="1">exact_result &lt;-<span class="st"> </span><span class="kw">ANOVA_exact</span>(design_result, <span class="dt">alpha_level =</span> alpha_level)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##       power partial_eta_squared cohen_f non_centrality
## speed 80.33              0.3043  0.6614           8.75
## 
## Power and Effect sizes for contrasts
##                         power effect_size
## p_speed_fast_speed_slow 80.33      0.6455</code></pre>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb125-1" title="1"><span class="co">#relation dz and f for within designs </span></a>
<a class="sourceLine" id="cb125-2" title="2">f &lt;-<span class="st"> </span><span class="fl">0.5</span><span class="op">*</span><span class="fl">0.6454972</span></a>
<a class="sourceLine" id="cb125-3" title="3"><span class="co">#  </span></a></code></pre></div>
<p>Entering this f in G*power, with a correlation of 0.5, yields the same as entering <code>f = 0.25</code> and <code>correlation = 0.7</code>.</p>

</div>
</div>
<div id="repeated-measures-anova-part-2" class="section level2">
<h2><span class="header-section-number">3.2</span> Repeated Measures-ANOVA Part 2</h2>
<p>Here, we will examine a repeated measures experiment with 3 within-subject conditions, to illustrate how a repeated measures ANOVA extends a dependent <em>t</em>-test with 3 groups.</p>
<p>In the example for a two-group within design we provided a specific formula for the sample size benefit for two groups. The sample size needed in within-designs (NW) with more than 2 conditions, relative to the sample needed in between-designs (NB), assuming normal distributions and compound symmetry, and ignoring the difference in degrees of freedom between the two types of tests, is (from Maxwell &amp; Delaney, 2004, p. 562, formula 47):</p>
<p><span class="math inline">\(N_{W}=\frac{N_{B}(1-\rho)}{a}\)</span></p>
<p>Where a is the number of within-subject levels.</p>
<div id="the-relation-between-cohens-f-and-cohens-d" class="section level3">
<h3><span class="header-section-number">3.2.1</span> The relation between Cohen’s f and Cohen’s d</h3>
<p>Whereas in the case of a repeated measures ANOVA with 2 groups we could explain the principles of a power analysis by comparing our test against a <em>t</em>-test and Cohen’s d, this becomes more difficult when we have more than 2 groups. It is more useful to explain how to directly calculate Cohen’s f, the effect size used in power analyses for ANOVA. Cohen’s f is calculated following Cohen, 1988, formula 8.2.1 and 8.2.2:</p>
<p><span class="math inline">\(f = \sqrt{\frac{\frac{\sum(\mu-\overline{\mu})^2)}N}\sigma}\)</span></p>
<p>Imagine we have a within-subject experiment with 3 conditions. We ask people what they mood is when their alarm clock wakes them up, when they wake up naturally on a week day, and when they wake up naturally on a weekend day. Based on pilot data, we expect the means (on a 7 point validated mood scale) are 3.8, 4.2, and 4.3. The standard deviation is 0.9, and the correlation between the dependent measurements is 0.7. We can calculate Cohen’s f for the ANOVA, and Cohen’s dz for the contrasts:</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb126-1" title="1">mu &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">3.8</span>, <span class="fl">4.2</span>, <span class="fl">4.3</span>)</a>
<a class="sourceLine" id="cb126-2" title="2">sd &lt;-<span class="st"> </span><span class="fl">0.9</span></a>
<a class="sourceLine" id="cb126-3" title="3">f &lt;-<span class="st"> </span><span class="kw">sqrt</span>(<span class="kw">sum</span>((mu<span class="op">-</span><span class="kw">mean</span>(mu))<span class="op">^</span><span class="dv">2</span>)<span class="op">/</span><span class="kw">length</span>(mu))<span class="op">/</span>sd <span class="co">#Cohen, 1988, formula 8.2.1 and 8.2.2</span></a>
<a class="sourceLine" id="cb126-4" title="4">f</a></code></pre></div>
<pre><code>## [1] 0.2400274</code></pre>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb128-1" title="1">r &lt;-<span class="st"> </span><span class="fl">0.7</span></a>
<a class="sourceLine" id="cb128-2" title="2">(<span class="fl">4.2-3.8</span>)<span class="op">/</span><span class="fl">0.9</span><span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">2</span><span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>r))</a></code></pre></div>
<pre><code>## [1] 0.5737753</code></pre>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb130-1" title="1">(<span class="fl">4.3-3.8</span>)<span class="op">/</span><span class="fl">0.9</span><span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">2</span><span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>r))</a></code></pre></div>
<pre><code>## [1] 0.7172191</code></pre>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb132-1" title="1">(<span class="fl">4.3-4.2</span>)<span class="op">/</span><span class="fl">0.9</span><span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">2</span><span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>r))</a></code></pre></div>
<pre><code>## [1] 0.1434438</code></pre>
<p>The relation between Cohen’s d or dz and Cohen’s f becomes more difficult when there are multiple groups, because the relationship depends on the pattern of the means. Cohen (1988) presents calculations for three patterns, minimal variability (for example, for 5 means: -0.25, 0, 0, 0, 0.25), medium variability (for example, for 5 means: -0.25, -0.25, 0.25, 0.25, 0.25 or -0.25, -0.25, -0.25, 0.25, 0.25). For these three patterns, formula’s are available that compute Cohen’s f from Cohen’s d, where d is the effect size calculated for the difference between the largest and smallest mean (if the largest mean is 0.25 and the smallest mean is -0.25, 0.25 - -0.25 = 0.5, so d is 0.5 divided by the standard deviation of 0.9). In our example, d would be (4.3-3.8)/0.9 = 0.5555556. If we divide this value by sqrt(2*(1-r)) we have dz = 0.5555556/0.7745967 = 0.7172191.</p>
<p>I have created a custom function that will calculate f from d, based on a specification of one of the three patterns of means. Our pattern is most similar (but not identical) to a maximum variability pattern (two means are high, one is lower). So we could attempt to calculate f from d (0.5555556), by calculating d from the largest and smallest mean:</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb134-1" title="1"><span class="kw">source</span>(<span class="st">&quot;https://raw.githubusercontent.com/Lakens/ANOVA_power_simulation/master/calc_f_d_eta.R&quot;</span>)</a>
<a class="sourceLine" id="cb134-2" title="2">res &lt;-<span class="st"> </span><span class="kw">calc_f_d_eta</span>(<span class="dt">mu =</span> mu, <span class="dt">sd =</span> sd, <span class="dt">variability =</span> <span class="st">&quot;maximum&quot;</span>)</a>
<a class="sourceLine" id="cb134-3" title="3">res<span class="op">$</span>f</a></code></pre></div>
<pre><code>## [1] 0.2618914</code></pre>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb136-1" title="1">res<span class="op">$</span>d</a></code></pre></div>
<pre><code>## [1] 0.5555556</code></pre>
<p>We see the Cohen’s f value is 0.2618914 and d = 0.5555556. The Cohen’s f is not perfectly accurate - it is assuming the pattern of means is 3.8, 4.3, 4.3, and not 3.8, 4.2, 4.3. If the means and sd is known, it is best to calculate Cohen’s f directly from these values.</p>
</div>
<div id="three-within-conditions-medium-effect-size" class="section level3">
<h3><span class="header-section-number">3.2.2</span> Three within conditions, medium effect size</h3>
<p>We can perform power analyses for within designs using simuations. We set groups to 3 for the simulation, n = 20, and the correlation between dependent variables to 0.8. If the true effect size is f = 0.25, and the alpha level is 0.05, the power is 96.6%.</p>
<p>In this case, we simulate data with means -0.3061862, 0.0000000, and 0.3061862, and set the sd to 1.</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb138-1" title="1">K &lt;-<span class="st"> </span><span class="dv">3</span></a>
<a class="sourceLine" id="cb138-2" title="2">n &lt;-<span class="st"> </span><span class="dv">20</span></a>
<a class="sourceLine" id="cb138-3" title="3">sd &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb138-4" title="4">r &lt;-<span class="st"> </span><span class="fl">0.8</span></a>
<a class="sourceLine" id="cb138-5" title="5">alpha =<span class="st"> </span><span class="fl">0.05</span></a>
<a class="sourceLine" id="cb138-6" title="6">f &lt;-<span class="st"> </span><span class="fl">0.25</span></a>
<a class="sourceLine" id="cb138-7" title="7">f2 &lt;-<span class="st"> </span>f<span class="op">^</span><span class="dv">2</span></a>
<a class="sourceLine" id="cb138-8" title="8">ES &lt;-<span class="st"> </span>f2<span class="op">/</span>(f2<span class="op">+</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb138-9" title="9">ES</a></code></pre></div>
<pre><code>## [1] 0.05882353</code></pre>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb140-1" title="1">mu &lt;-<span class="st"> </span><span class="kw">mu_from_ES</span>(<span class="dt">K =</span> K, <span class="dt">ES =</span> ES)</a>
<a class="sourceLine" id="cb140-2" title="2"><span class="kw">sqrt</span>(<span class="kw">sum</span>((mu<span class="op">-</span><span class="kw">mean</span>(mu))<span class="op">^</span><span class="dv">2</span>)<span class="op">/</span><span class="kw">length</span>(mu))<span class="op">/</span>sd <span class="co">#Cohen, 1988, formula 8.2.1 and 8.2.2</span></a></code></pre></div>
<pre><code>## [1] 0.25</code></pre>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb142-1" title="1">design =<span class="kw">paste</span>(K,<span class="st">&quot;w&quot;</span>,<span class="dt">sep=</span><span class="st">&quot;&quot;</span>)</a>
<a class="sourceLine" id="cb142-2" title="2">labelnames &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;speed&quot;</span>, <span class="st">&quot;fast&quot;</span>, <span class="st">&quot;medium&quot;</span>, <span class="st">&quot;slow&quot;</span>)</a>
<a class="sourceLine" id="cb142-3" title="3">design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> design,</a>
<a class="sourceLine" id="cb142-4" title="4">                   <span class="dt">n =</span> n, </a>
<a class="sourceLine" id="cb142-5" title="5">                   <span class="dt">mu =</span> mu, </a>
<a class="sourceLine" id="cb142-6" title="6">                   <span class="dt">sd =</span> sd, </a>
<a class="sourceLine" id="cb142-7" title="7">                   <span class="dt">r =</span> r, </a>
<a class="sourceLine" id="cb142-8" title="8">                   <span class="dt">labelnames =</span> labelnames)</a>
<a class="sourceLine" id="cb142-9" title="9">alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span></a>
<a class="sourceLine" id="cb142-10" title="10">simulation_result &lt;-<span class="st"> </span><span class="kw">ANOVA_power</span>(design_result, <span class="dt">nsims =</span> nsims)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##             power effect_size
## anova_speed    98      0.3432
## 
## Power and Effect sizes for contrasts
##                           power effect_size
## p_speed_fast_speed_medium    57      0.5195
## p_speed_fast_speed_slow      98      1.0126
## p_speed_medium_speed_slow    52      0.4791
## 
## Within-Subject Factors Included: Check MANOVA Results</code></pre>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb144-1" title="1">exact_result &lt;-<span class="st"> </span><span class="kw">ANOVA_exact</span>(design_result, <span class="dt">alpha_level =</span> alpha_level)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##       power partial_eta_squared cohen_f non_centrality
## speed 96.92              0.3304  0.7024          18.75
## 
## Power and Effect sizes for contrasts
##                           power effect_size
## p_speed_fast_speed_medium 53.79      0.4841
## p_speed_fast_speed_slow   98.39      0.9682
## p_speed_medium_speed_slow 53.79      0.4841</code></pre>
<p>The results of the simulation are indeed very close to 96.9%. We can see this is in line with the power estimate from Gpower:</p>
<p><img src="screenshots/gpower_12.png" /></p>
<p>We can also validate this by creating the code to do a power analysis in R from scratch:</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb146-1" title="1">K &lt;-<span class="st"> </span><span class="dv">3</span> <span class="co">#three groups</span></a>
<a class="sourceLine" id="cb146-2" title="2">n &lt;-<span class="st"> </span><span class="dv">20</span></a>
<a class="sourceLine" id="cb146-3" title="3">sd &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb146-4" title="4">r &lt;-<span class="st"> </span><span class="fl">0.8</span></a>
<a class="sourceLine" id="cb146-5" title="5">alpha =<span class="st"> </span><span class="fl">0.05</span></a>
<a class="sourceLine" id="cb146-6" title="6">f &lt;-<span class="st"> </span><span class="fl">0.25</span></a>
<a class="sourceLine" id="cb146-7" title="7">f2 &lt;-<span class="st"> </span>f<span class="op">^</span><span class="dv">2</span></a>
<a class="sourceLine" id="cb146-8" title="8">ES &lt;-<span class="st"> </span>f2<span class="op">/</span>(f2<span class="op">+</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb146-9" title="9">ES</a></code></pre></div>
<pre><code>## [1] 0.05882353</code></pre>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb148-1" title="1">mu &lt;-<span class="st"> </span><span class="kw">mu_from_ES</span>(<span class="dt">K =</span> K, <span class="dt">ES =</span> ES)</a>
<a class="sourceLine" id="cb148-2" title="2">design =<span class="kw">paste</span>(K,<span class="st">&quot;w&quot;</span>,<span class="dt">sep=</span><span class="st">&quot;&quot;</span>)</a>
<a class="sourceLine" id="cb148-3" title="3">labelnames &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;speed&quot;</span>, <span class="st">&quot;fast&quot;</span>, <span class="st">&quot;medium&quot;</span>, <span class="st">&quot;slow&quot;</span>)</a>
<a class="sourceLine" id="cb148-4" title="4">design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> design,</a>
<a class="sourceLine" id="cb148-5" title="5">                   <span class="dt">n =</span> n, </a>
<a class="sourceLine" id="cb148-6" title="6">                   <span class="dt">mu =</span> mu, </a>
<a class="sourceLine" id="cb148-7" title="7">                   <span class="dt">sd =</span> sd, </a>
<a class="sourceLine" id="cb148-8" title="8">                   <span class="dt">r =</span> r, </a>
<a class="sourceLine" id="cb148-9" title="9">                   <span class="dt">labelnames =</span> labelnames)</a>
<a class="sourceLine" id="cb148-10" title="10"><span class="kw">power_oneway_within</span>(design_result)<span class="op">$</span>power</a></code></pre></div>
<pre><code>## [1] 0.9691634</code></pre>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb150-1" title="1"><span class="kw">power_oneway_within</span>(design_result)<span class="op">$</span>eta_p_<span class="dv">2</span></a></code></pre></div>
<pre><code>## [1] 0.05882353</code></pre>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb152-1" title="1"><span class="kw">power_oneway_within</span>(design_result)<span class="op">$</span>eta_p_<span class="dv">2</span>_SPSS</a></code></pre></div>
<pre><code>## [1] 0.3303965</code></pre>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb154-1" title="1"><span class="kw">power_oneway_within</span>(design_result)<span class="op">$</span>Cohen_f</a></code></pre></div>
<pre><code>## [1] 0.25</code></pre>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb156-1" title="1"><span class="kw">power_oneway_within</span>(design_result)<span class="op">$</span>Cohen_f_SPSS</a></code></pre></div>
<pre><code>## [1] 0.7024394</code></pre>
<p>We can even check the calculation of Cohen’s f SPSS style in GPower. We take the GPower settings as illustrated above. We click the ‘Options’ button, and check the radiobutton next to ‘As in SPSS’. Click ok, and you will notice that the ‘Corr among rep measures’ field has disappeared. The correlation does not need to be entered seperately, but is incorporated in Cohen’s f. The value of Cohen’s f, which was 0.25, has changed into 0.7024394. This is the SPSS equivalent. The value is much larger. This value, and it’s corresponding partial eta-squared, incorporate the correlation between observations.</p>
<p><img src="screenshots/gpower_14.png" /></p>

</div>
</div>
<div id="repeated-measures-anova-part-3" class="section level2">
<h2><span class="header-section-number">3.3</span> Repeated Measures-ANOVA Part 3</h2>
<p>We first repeat the simulation by Brysbaert:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb158-1" title="1"><span class="co"># give sample size</span></a>
<a class="sourceLine" id="cb158-2" title="2">N =<span class="st"> </span><span class="dv">75</span></a>
<a class="sourceLine" id="cb158-3" title="3"><span class="co"># give effect size d</span></a>
<a class="sourceLine" id="cb158-4" title="4">d1 =<span class="st"> </span><span class="fl">.4</span> <span class="co">#difference between the extremes</span></a>
<a class="sourceLine" id="cb158-5" title="5">d2 =<span class="st"> </span><span class="fl">.4</span> <span class="co">#third condition goes with the highest extreme</span></a>
<a class="sourceLine" id="cb158-6" title="6"><span class="co"># give the correlation between the conditions</span></a>
<a class="sourceLine" id="cb158-7" title="7">r =<span class="st"> </span><span class="fl">.5</span></a>
<a class="sourceLine" id="cb158-8" title="8"><span class="co"># give number of simulations</span></a>
<a class="sourceLine" id="cb158-9" title="9">nSim =<span class="st"> </span>nsims</a>
<a class="sourceLine" id="cb158-10" title="10"><span class="co"># give alpha levels</span></a>
<a class="sourceLine" id="cb158-11" title="11">alpha1 =<span class="st"> </span><span class="fl">.05</span> <span class="co">#alpha level for the omnibus ANOVA</span></a>
<a class="sourceLine" id="cb158-12" title="12">alpha2 =<span class="st"> </span><span class="fl">.05</span> <span class="co">#also adjusted from original by DL</span></a>
<a class="sourceLine" id="cb158-13" title="13"><span class="co"># create progress bar in case it takes a while</span></a>
<a class="sourceLine" id="cb158-14" title="14"><span class="co">#pb &lt;- winProgressBar(title = &quot;progress bar&quot;, min = 0, max = nSim, width = 300)</span></a>
<a class="sourceLine" id="cb158-15" title="15"><span class="co"># create vectors to store p-values</span></a>
<a class="sourceLine" id="cb158-16" title="16">p1 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#p-value omnibus ANOVA</span></a>
<a class="sourceLine" id="cb158-17" title="17">p2 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#p-value first post hoc test</span></a>
<a class="sourceLine" id="cb158-18" title="18">p3 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#p-value second post hoc test</span></a>
<a class="sourceLine" id="cb158-19" title="19">p4 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#p-value third post hoc test</span></a>
<a class="sourceLine" id="cb158-20" title="20"><span class="co"># open library MASS</span></a>
<a class="sourceLine" id="cb158-21" title="21"><span class="kw">library</span>(<span class="st">&#39;MASS&#39;</span>)</a>
<a class="sourceLine" id="cb158-22" title="22"><span class="co"># define correlation matrix</span></a>
<a class="sourceLine" id="cb158-23" title="23">rho &lt;-<span class="st"> </span><span class="kw">cbind</span>(<span class="kw">c</span>(<span class="dv">1</span>, r, r), <span class="kw">c</span>(r, <span class="dv">1</span>, r), <span class="kw">c</span>(r, r, <span class="dv">1</span>))</a>
<a class="sourceLine" id="cb158-24" title="24"><span class="co"># define participant codes</span></a>
<a class="sourceLine" id="cb158-25" title="25">part &lt;-<span class="st"> </span><span class="kw">paste</span>(<span class="st">&quot;part&quot;</span>,<span class="kw">seq</span>(<span class="dv">1</span><span class="op">:</span>N))</a>
<a class="sourceLine" id="cb158-26" title="26"><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>nSim){ <span class="co">#for each simulated experiment</span></a>
<a class="sourceLine" id="cb158-27" title="27"> <span class="co"># setWinProgressBar(pb, i, title=paste(round(i/nSim*100, 1), &quot;% done&quot;))</span></a>
<a class="sourceLine" id="cb158-28" title="28">  data =<span class="st"> </span><span class="kw">mvrnorm</span>(<span class="dt">n=</span>N, <span class="dt">mu=</span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>), <span class="dt">Sigma=</span>rho)</a>
<a class="sourceLine" id="cb158-29" title="29">  data[,<span class="dv">2</span>] =<span class="st"> </span>data[,<span class="dv">2</span>]<span class="op">+</span>d1</a>
<a class="sourceLine" id="cb158-30" title="30">  data[,<span class="dv">3</span>] =<span class="st"> </span>data[,<span class="dv">3</span>]<span class="op">+</span>d2</a>
<a class="sourceLine" id="cb158-31" title="31">  datalong =<span class="st"> </span><span class="kw">c</span>(data[,<span class="dv">1</span>],data[,<span class="dv">2</span>],data[,<span class="dv">3</span>])</a>
<a class="sourceLine" id="cb158-32" title="32">  conds=<span class="st"> </span><span class="kw">factor</span>(<span class="kw">rep</span>(letters[<span class="dv">24</span><span class="op">:</span><span class="dv">26</span>], <span class="dt">each =</span> N))</a>
<a class="sourceLine" id="cb158-33" title="33">  partID =<span class="st"> </span><span class="kw">factor</span>(<span class="kw">rep</span>(part, <span class="dt">times =</span> <span class="dv">3</span>))</a>
<a class="sourceLine" id="cb158-34" title="34">  output &lt;-<span class="kw">data.frame</span>(partID,conds,datalong)</a>
<a class="sourceLine" id="cb158-35" title="35">  test &lt;-<span class="st"> </span><span class="kw">aov</span>(datalong<span class="op">~</span>conds <span class="op">+</span><span class="st"> </span><span class="kw">Error</span>(partID<span class="op">/</span>conds), <span class="dt">data=</span>output)</a>
<a class="sourceLine" id="cb158-36" title="36">  tests &lt;-<span class="st"> </span>(<span class="kw">summary</span>(test))</a>
<a class="sourceLine" id="cb158-37" title="37">  p1[i] &lt;-<span class="st"> </span>tests<span class="op">$</span><span class="st">&#39;Error: partID:conds&#39;</span>[[<span class="dv">1</span>]]<span class="op">$</span><span class="st">&#39;Pr(&gt;F)&#39;</span>[[<span class="dv">1</span>]]</a>
<a class="sourceLine" id="cb158-38" title="38">  p2[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(data[,<span class="dv">1</span>],data[,<span class="dv">2</span>], <span class="dt">paired=</span><span class="ot">TRUE</span>)<span class="op">$</span>p.value</a>
<a class="sourceLine" id="cb158-39" title="39">  p3[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(data[,<span class="dv">1</span>],data[,<span class="dv">3</span>], <span class="dt">paired=</span><span class="ot">TRUE</span>)<span class="op">$</span>p.value</a>
<a class="sourceLine" id="cb158-40" title="40">  p4[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(data[,<span class="dv">2</span>],data[,<span class="dv">3</span>], <span class="dt">paired=</span><span class="ot">TRUE</span>)<span class="op">$</span>p.value</a>
<a class="sourceLine" id="cb158-41" title="41">  }</a>
<a class="sourceLine" id="cb158-42" title="42"><span class="co">#close(pb)#close progress bar</span></a>
<a class="sourceLine" id="cb158-43" title="43"><span class="co">#printing all unique tests (adjusted code by DL)</span></a>
<a class="sourceLine" id="cb158-44" title="44"><span class="kw">sum</span>(p1<span class="op">&lt;</span>alpha1)<span class="op">/</span>nSim</a></code></pre></div>
<pre><code>## [1] 0.95</code></pre>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb160-1" title="1"><span class="kw">sum</span>(p2<span class="op">&lt;</span>alpha2)<span class="op">/</span>nSim</a></code></pre></div>
<pre><code>## [1] 0.96</code></pre>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb162-1" title="1"><span class="kw">sum</span>(p3<span class="op">&lt;</span>alpha2)<span class="op">/</span>nSim</a></code></pre></div>
<pre><code>## [1] 0.95</code></pre>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb164-1" title="1"><span class="kw">sum</span>(p4<span class="op">&lt;</span>alpha2)<span class="op">/</span>nSim</a></code></pre></div>
<pre><code>## [1] 0.01</code></pre>
</div>
<div id="reproducing-brysbaert" class="section level2">
<h2><span class="header-section-number">3.4</span> Reproducing Brysbaert</h2>
<p>We can reproduce the same results as Brysbaeert finds with his code:</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb166-1" title="1">design &lt;-<span class="st"> &quot;3w&quot;</span></a>
<a class="sourceLine" id="cb166-2" title="2">n &lt;-<span class="st"> </span><span class="dv">75</span></a>
<a class="sourceLine" id="cb166-3" title="3">mu &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.4</span>, <span class="fl">0.4</span>)</a>
<a class="sourceLine" id="cb166-4" title="4">sd &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb166-5" title="5">r &lt;-<span class="st"> </span><span class="fl">0.5</span></a>
<a class="sourceLine" id="cb166-6" title="6">labelnames &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;speed&quot;</span>, <span class="st">&quot;fast&quot;</span>, <span class="st">&quot;medium&quot;</span>, <span class="st">&quot;slow&quot;</span>)</a></code></pre></div>
<p>We create the within design, and run the simulation</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb167-1" title="1">design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> design,</a>
<a class="sourceLine" id="cb167-2" title="2">                   <span class="dt">n =</span> n, </a>
<a class="sourceLine" id="cb167-3" title="3">                   <span class="dt">mu =</span> mu, </a>
<a class="sourceLine" id="cb167-4" title="4">                   <span class="dt">sd =</span> sd, </a>
<a class="sourceLine" id="cb167-5" title="5">                   <span class="dt">r =</span> r, </a>
<a class="sourceLine" id="cb167-6" title="6">                   <span class="dt">labelnames =</span> labelnames)</a>
<a class="sourceLine" id="cb167-7" title="7">simulation_result &lt;-<span class="st"> </span><span class="kw">ANOVA_power</span>(design_result, <span class="dt">nsims =</span> nsims)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##             power effect_size
## anova_speed    94      0.1039
## 
## Power and Effect sizes for contrasts
##                           power effect_size
## p_speed_fast_speed_medium    92    0.394891
## p_speed_fast_speed_slow      94    0.397796
## p_speed_medium_speed_slow     3    0.007351
## 
## Within-Subject Factors Included: Check MANOVA Results</code></pre>
<p>And we can again replicate this with the <code>ANOVA_exact</code> function.</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb169-1" title="1"><span class="kw">ANOVA_exact</span>(design_result)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##       power partial_eta_squared cohen_f non_centrality
## speed 95.29              0.0976  0.3288             16
## 
## Power and Effect sizes for contrasts
##                           power effect_size
## p_speed_fast_speed_medium 92.77         0.4
## p_speed_fast_speed_slow   92.77         0.4
## p_speed_medium_speed_slow  5.00         0.0</code></pre>
<p>#Results</p>
<p>The results of the simulation are very similar. Power for the ANOVA <em>F</em>-test is around 95.2%. For the three paired t-tests, power is around 92.7. This is in line with the a-priori power analysis when using g*power:</p>
<p><img src="screenshots/gpower_2.png" /></p>
<p>We can perform an post-hoc power analysis in G*power. We can calculate Cohen´s f based on the means and sd, using our own custom formula.</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb171-1" title="1"><span class="co"># Our simulation is based onthe following means and sd:</span></a>
<a class="sourceLine" id="cb171-2" title="2"><span class="co"># mu &lt;- c(0, 0.4, 0.4)</span></a>
<a class="sourceLine" id="cb171-3" title="3"><span class="co"># sd &lt;- 1</span></a>
<a class="sourceLine" id="cb171-4" title="4">f &lt;-<span class="st"> </span><span class="kw">sqrt</span>(<span class="kw">sum</span>((mu<span class="op">-</span><span class="kw">mean</span>(mu))<span class="op">^</span><span class="dv">2</span>)<span class="op">/</span><span class="kw">length</span>(mu))<span class="op">/</span>sd <span class="co">#Cohen, 1988, formula 8.2.1 and 8.2.2</span></a>
<a class="sourceLine" id="cb171-5" title="5"><span class="co"># We can see why f = 0.5*d. </span></a>
<a class="sourceLine" id="cb171-6" title="6"><span class="co"># Imagine 2 group, mu = 1 and 2</span></a>
<a class="sourceLine" id="cb171-7" title="7"><span class="co"># Grand mean is 1.5, we have sqrt(sum(0.5^2 + 0.5^2)/2), or sqrt(0.5/2), = 0.5. </span></a>
<a class="sourceLine" id="cb171-8" title="8"><span class="co"># For Cohen&#39;s d we use the difference, 2-1 = 1. </span></a></code></pre></div>
<p>The Cohen´s f is 0.1885618. We can enter the f (using the default ’as in G*Power 3.0’ in the option window) and enter a sample size of 75, number of groups as 1, number of measurements as 3, correlation as 0.5. This yields:</p>
<p><img src="screenshots/gpower_3.png" /></p>
</div>
<div id="reproducing-brysbaert-variation-1-changing-correlation" class="section level2">
<h2><span class="header-section-number">3.5</span> Reproducing Brysbaert Variation 1 Changing Correlation</h2>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb172-1" title="1"><span class="co"># give sample size</span></a>
<a class="sourceLine" id="cb172-2" title="2">N =<span class="st"> </span><span class="dv">75</span></a>
<a class="sourceLine" id="cb172-3" title="3"><span class="co"># give effect size d</span></a>
<a class="sourceLine" id="cb172-4" title="4">d1 =<span class="st"> </span><span class="fl">.4</span> <span class="co">#difference between the extremes</span></a>
<a class="sourceLine" id="cb172-5" title="5">d2 =<span class="st"> </span><span class="fl">.4</span> <span class="co">#third condition goes with the highest extreme</span></a>
<a class="sourceLine" id="cb172-6" title="6"><span class="co"># give the correlation between the conditions</span></a>
<a class="sourceLine" id="cb172-7" title="7">r =<span class="st"> </span><span class="fl">.6</span> <span class="co">#increased correlation</span></a>
<a class="sourceLine" id="cb172-8" title="8"><span class="co"># give number of simulations</span></a>
<a class="sourceLine" id="cb172-9" title="9">nSim =<span class="st"> </span>nsims</a>
<a class="sourceLine" id="cb172-10" title="10"><span class="co"># give alpha levels</span></a>
<a class="sourceLine" id="cb172-11" title="11">alpha1 =<span class="st"> </span><span class="fl">.05</span> <span class="co">#alpha level for the omnibus ANOVA</span></a>
<a class="sourceLine" id="cb172-12" title="12">alpha2 =<span class="st"> </span><span class="fl">.05</span> <span class="co">#also adjusted from original by DL</span></a>
<a class="sourceLine" id="cb172-13" title="13"><span class="co"># create progress bar in case it takes a while</span></a>
<a class="sourceLine" id="cb172-14" title="14"><span class="co">#pb &lt;- winProgressBar(title = &quot;progress bar&quot;, min = 0, max = nSim, width = 300)</span></a>
<a class="sourceLine" id="cb172-15" title="15"><span class="co"># create vectors to store p-values</span></a>
<a class="sourceLine" id="cb172-16" title="16">p1 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#p-value omnibus ANOVA</span></a>
<a class="sourceLine" id="cb172-17" title="17">p2 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#p-value first post hoc test</span></a>
<a class="sourceLine" id="cb172-18" title="18">p3 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#p-value second post hoc test</span></a>
<a class="sourceLine" id="cb172-19" title="19">p4 &lt;-<span class="kw">numeric</span>(nSim) <span class="co">#p-value third post hoc test</span></a>
<a class="sourceLine" id="cb172-20" title="20"><span class="co"># open library MASS</span></a>
<a class="sourceLine" id="cb172-21" title="21"><span class="kw">library</span>(<span class="st">&#39;MASS&#39;</span>)</a>
<a class="sourceLine" id="cb172-22" title="22"><span class="co"># define correlation matrix</span></a>
<a class="sourceLine" id="cb172-23" title="23">rho &lt;-<span class="st"> </span><span class="kw">cbind</span>(<span class="kw">c</span>(<span class="dv">1</span>, r, r), <span class="kw">c</span>(r, <span class="dv">1</span>, r), <span class="kw">c</span>(r, r, <span class="dv">1</span>))</a>
<a class="sourceLine" id="cb172-24" title="24"><span class="co"># define participant codes</span></a>
<a class="sourceLine" id="cb172-25" title="25">part &lt;-<span class="st"> </span><span class="kw">paste</span>(<span class="st">&quot;part&quot;</span>,<span class="kw">seq</span>(<span class="dv">1</span><span class="op">:</span>N))</a>
<a class="sourceLine" id="cb172-26" title="26"><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>nSim){ <span class="co">#for each simulated experiment</span></a>
<a class="sourceLine" id="cb172-27" title="27"> <span class="co"># setWinProgressBar(pb, i, title=paste(round(i/nSim*100, 1), &quot;% done&quot;))</span></a>
<a class="sourceLine" id="cb172-28" title="28">  data =<span class="st"> </span><span class="kw">mvrnorm</span>(<span class="dt">n=</span>N, <span class="dt">mu=</span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>), <span class="dt">Sigma=</span>rho)</a>
<a class="sourceLine" id="cb172-29" title="29">  data[,<span class="dv">2</span>] =<span class="st"> </span>data[,<span class="dv">2</span>]<span class="op">+</span>d1</a>
<a class="sourceLine" id="cb172-30" title="30">  data[,<span class="dv">3</span>] =<span class="st"> </span>data[,<span class="dv">3</span>]<span class="op">+</span>d2</a>
<a class="sourceLine" id="cb172-31" title="31">  datalong =<span class="st"> </span><span class="kw">c</span>(data[,<span class="dv">1</span>],data[,<span class="dv">2</span>],data[,<span class="dv">3</span>])</a>
<a class="sourceLine" id="cb172-32" title="32">  conds=<span class="st"> </span><span class="kw">factor</span>(<span class="kw">rep</span>(letters[<span class="dv">24</span><span class="op">:</span><span class="dv">26</span>], <span class="dt">each =</span> N))</a>
<a class="sourceLine" id="cb172-33" title="33">  partID =<span class="st"> </span><span class="kw">factor</span>(<span class="kw">rep</span>(part, <span class="dt">times =</span> <span class="dv">3</span>))</a>
<a class="sourceLine" id="cb172-34" title="34">  output &lt;-<span class="kw">data.frame</span>(partID,conds,datalong)</a>
<a class="sourceLine" id="cb172-35" title="35">  test &lt;-<span class="st"> </span><span class="kw">aov</span>(datalong<span class="op">~</span>conds <span class="op">+</span><span class="st"> </span><span class="kw">Error</span>(partID<span class="op">/</span>conds), <span class="dt">data=</span>output)</a>
<a class="sourceLine" id="cb172-36" title="36">  tests &lt;-<span class="st"> </span>(<span class="kw">summary</span>(test))</a>
<a class="sourceLine" id="cb172-37" title="37">  p1[i] &lt;-<span class="st"> </span>tests<span class="op">$</span><span class="st">&#39;Error: partID:conds&#39;</span>[[<span class="dv">1</span>]]<span class="op">$</span><span class="st">&#39;Pr(&gt;F)&#39;</span>[[<span class="dv">1</span>]]</a>
<a class="sourceLine" id="cb172-38" title="38">  p2[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(data[,<span class="dv">1</span>],data[,<span class="dv">2</span>], <span class="dt">paired=</span><span class="ot">TRUE</span>)<span class="op">$</span>p.value</a>
<a class="sourceLine" id="cb172-39" title="39">  p3[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(data[,<span class="dv">1</span>],data[,<span class="dv">3</span>], <span class="dt">paired=</span><span class="ot">TRUE</span>)<span class="op">$</span>p.value</a>
<a class="sourceLine" id="cb172-40" title="40">  p4[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(data[,<span class="dv">2</span>],data[,<span class="dv">3</span>], <span class="dt">paired=</span><span class="ot">TRUE</span>)<span class="op">$</span>p.value</a>
<a class="sourceLine" id="cb172-41" title="41">  }</a>
<a class="sourceLine" id="cb172-42" title="42"><span class="co">#close(pb)#close progress bar</span></a>
<a class="sourceLine" id="cb172-43" title="43"><span class="co">#printing all unique tests (adjusted code by DL)</span></a>
<a class="sourceLine" id="cb172-44" title="44"><span class="kw">sum</span>(p1<span class="op">&lt;</span>alpha1)<span class="op">/</span>nSim</a></code></pre></div>
<pre><code>## [1] 0.98</code></pre>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb174-1" title="1"><span class="kw">sum</span>(p2<span class="op">&lt;</span>alpha2)<span class="op">/</span>nSim</a></code></pre></div>
<pre><code>## [1] 0.93</code></pre>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb176-1" title="1"><span class="kw">sum</span>(p3<span class="op">&lt;</span>alpha2)<span class="op">/</span>nSim</a></code></pre></div>
<pre><code>## [1] 0.96</code></pre>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb178-1" title="1"><span class="kw">sum</span>(p4<span class="op">&lt;</span>alpha2)<span class="op">/</span>nSim</a></code></pre></div>
<pre><code>## [1] 0.06</code></pre>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb180-1" title="1">design &lt;-<span class="st"> &quot;3w&quot;</span></a>
<a class="sourceLine" id="cb180-2" title="2">n &lt;-<span class="st"> </span><span class="dv">75</span></a>
<a class="sourceLine" id="cb180-3" title="3">mu &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.4</span>, <span class="fl">0.4</span>)</a>
<a class="sourceLine" id="cb180-4" title="4">sd &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb180-5" title="5">r &lt;-<span class="st"> </span><span class="fl">0.6</span></a>
<a class="sourceLine" id="cb180-6" title="6">labelnames &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;speed&quot;</span>, <span class="st">&quot;fast&quot;</span>, <span class="st">&quot;medium&quot;</span>, <span class="st">&quot;slow&quot;</span>)</a></code></pre></div>
<p>We create the within design, and run the simulation.</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb181-1" title="1">design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> design,</a>
<a class="sourceLine" id="cb181-2" title="2">                   <span class="dt">n =</span> n, </a>
<a class="sourceLine" id="cb181-3" title="3">                   <span class="dt">mu =</span> mu, </a>
<a class="sourceLine" id="cb181-4" title="4">                   <span class="dt">sd =</span> sd, </a>
<a class="sourceLine" id="cb181-5" title="5">                   <span class="dt">r =</span> r, </a>
<a class="sourceLine" id="cb181-6" title="6">                   <span class="dt">labelnames =</span> labelnames)</a>
<a class="sourceLine" id="cb181-7" title="7"><span class="kw">ANOVA_power</span>(design_result, <span class="dt">nsims =</span> nsims)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##             power effect_size
## anova_speed    99      0.1295
## 
## Power and Effect sizes for contrasts
##                           power effect_size
## p_speed_fast_speed_medium    99     0.44861
## p_speed_fast_speed_slow      97     0.46472
## p_speed_medium_speed_slow     2     0.01053
## 
## Within-Subject Factors Included: Check MANOVA Results</code></pre>
<p>We replicate this with <code>ANOVA_exact</code>.</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb183-1" title="1"><span class="kw">ANOVA_exact</span>(design_result)</a></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##       power partial_eta_squared cohen_f non_centrality
## speed 98.35               0.119  0.3676             20
## 
## Power and Effect sizes for contrasts
##                           power effect_size
## p_speed_fast_speed_medium 96.87      0.4472
## p_speed_fast_speed_slow   96.87      0.4472
## p_speed_medium_speed_slow  5.00      0.0000</code></pre>
<p>Again, this is similar to G*Power for the ANOVA:</p>
<p><img src="screenshots/gpower_4.png" /></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="one-way-anova.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="mixed-anova.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["SuperpowerValidation.pdf", "SuperpowerValidation.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
