<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Repeated Measures ANOVA | The Superpower R Package: Capabilities and Validation</title>
  <meta name="description" content="This is a book describing the capabilities of the Superpower R package." />
  <meta name="generator" content="bookdown 0.10 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Repeated Measures ANOVA | The Superpower R Package: Capabilities and Validation" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a book describing the capabilities of the Superpower R package." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Repeated Measures ANOVA | The Superpower R Package: Capabilities and Validation" />
  
  <meta name="twitter:description" content="This is a book describing the capabilities of the Superpower R package." />
  

<meta name="author" content="Aaron R. Caldwell &amp; Daniël Lakens" />


<meta name="date" content="2019-09-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="one-way-anova.html">
<link rel="next" href="mixed-anova.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Superpower</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="the-experimental-design.html"><a href="the-experimental-design.html"><i class="fa fa-check"></i><b>1</b> The Experimental Design</a><ul>
<li class="chapter" data-level="1.1" data-path="the-experimental-design.html"><a href="the-experimental-design.html#anova_design-function"><i class="fa fa-check"></i><b>1.1</b> ANOVA_design function</a><ul>
<li class="chapter" data-level="1.1.1" data-path="the-experimental-design.html"><a href="the-experimental-design.html#specifying-the-design-using-design"><i class="fa fa-check"></i><b>1.1.1</b> Specifying the design using <code>design</code></a></li>
<li class="chapter" data-level="1.1.2" data-path="the-experimental-design.html"><a href="the-experimental-design.html#specifying-the-means-using-mu"><i class="fa fa-check"></i><b>1.1.2</b> Specifying the means using <code>mu</code></a></li>
<li class="chapter" data-level="1.1.3" data-path="the-experimental-design.html"><a href="the-experimental-design.html#specifying-label-names"><i class="fa fa-check"></i><b>1.1.3</b> Specifying label names</a></li>
<li class="chapter" data-level="1.1.4" data-path="the-experimental-design.html"><a href="the-experimental-design.html#specifying-the-correlation"><i class="fa fa-check"></i><b>1.1.4</b> Specifying the correlation</a></li>
<li class="chapter" data-level="1.1.5" data-path="the-experimental-design.html"><a href="the-experimental-design.html#specifying-the-sample-size"><i class="fa fa-check"></i><b>1.1.5</b> Specifying the sample size</a></li>
<li class="chapter" data-level="1.1.6" data-path="the-experimental-design.html"><a href="the-experimental-design.html#specifying-the-standard-deviation"><i class="fa fa-check"></i><b>1.1.6</b> Specifying the standard deviation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="one-way-anova.html"><a href="one-way-anova.html"><i class="fa fa-check"></i><b>2</b> One-Way ANOVA</a><ul>
<li class="chapter" data-level="2.1" data-path="one-way-anova.html"><a href="one-way-anova.html#part-1"><i class="fa fa-check"></i><b>2.1</b> Part 1</a><ul>
<li class="chapter" data-level="2.1.1" data-path="one-way-anova.html"><a href="one-way-anova.html#two-conditions"><i class="fa fa-check"></i><b>2.1.1</b> Two conditions</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="one-way-anova.html"><a href="one-way-anova.html#part-2"><i class="fa fa-check"></i><b>2.2</b> Part 2</a><ul>
<li class="chapter" data-level="2.2.1" data-path="one-way-anova.html"><a href="one-way-anova.html#three-conditions"><i class="fa fa-check"></i><b>2.2.1</b> Three conditions</a></li>
<li class="chapter" data-level="2.2.2" data-path="one-way-anova.html"><a href="one-way-anova.html#power-for-simple-effects"><i class="fa fa-check"></i><b>2.2.2</b> Power for simple effects</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="one-way-anova.html"><a href="one-way-anova.html#part-3"><i class="fa fa-check"></i><b>2.3</b> Part 3</a><ul>
<li class="chapter" data-level="2.3.1" data-path="one-way-anova.html"><a href="one-way-anova.html#three-conditions-replication"><i class="fa fa-check"></i><b>2.3.1</b> Three conditions replication</a></li>
<li class="chapter" data-level="2.3.2" data-path="one-way-anova.html"><a href="one-way-anova.html#variation-1"><i class="fa fa-check"></i><b>2.3.2</b> Variation 1</a></li>
<li class="chapter" data-level="2.3.3" data-path="one-way-anova.html"><a href="one-way-anova.html#three-conditions-replication-1"><i class="fa fa-check"></i><b>2.3.3</b> Three conditions replication</a></li>
<li class="chapter" data-level="2.3.4" data-path="one-way-anova.html"><a href="one-way-anova.html#variation-2"><i class="fa fa-check"></i><b>2.3.4</b> Variation 2</a></li>
<li class="chapter" data-level="2.3.5" data-path="one-way-anova.html"><a href="one-way-anova.html#three-conditions-replication-2"><i class="fa fa-check"></i><b>2.3.5</b> Three conditions replication</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="one-way-anova.html"><a href="one-way-anova.html#effect-size-estimates-for-one-way-anova"><i class="fa fa-check"></i><b>2.4</b> Effect Size Estimates for One-Way ANOVA</a><ul>
<li class="chapter" data-level="2.4.1" data-path="one-way-anova.html"><a href="one-way-anova.html#three-conditions-small-effect-size"><i class="fa fa-check"></i><b>2.4.1</b> Three conditions, small effect size</a></li>
<li class="chapter" data-level="2.4.2" data-path="one-way-anova.html"><a href="one-way-anova.html#four-conditions-medium-effect-size"><i class="fa fa-check"></i><b>2.4.2</b> Four conditions, medium effect size</a></li>
<li class="chapter" data-level="2.4.3" data-path="one-way-anova.html"><a href="one-way-anova.html#two-conditions-large-effect-size"><i class="fa fa-check"></i><b>2.4.3</b> Two conditions, large effect size</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html"><i class="fa fa-check"></i><b>3</b> Repeated Measures ANOVA</a><ul>
<li class="chapter" data-level="3.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#part-1-1"><i class="fa fa-check"></i><b>3.1</b> Part 1</a><ul>
<li class="chapter" data-level="3.1.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#two-conditions-medium-effect-size"><i class="fa fa-check"></i><b>3.1.1</b> Two conditions, medium effect size</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#part-2-1"><i class="fa fa-check"></i><b>3.2</b> Part 2</a><ul>
<li class="chapter" data-level="3.2.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#the-relation-between-cohens-f-and-cohens-d"><i class="fa fa-check"></i><b>3.2.1</b> The relation between Cohen’s f and Cohen’s d</a></li>
<li class="chapter" data-level="3.2.2" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#three-within-conditions-medium-effect-size"><i class="fa fa-check"></i><b>3.2.2</b> Three within conditions, medium effect size</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#part-3-1"><i class="fa fa-check"></i><b>3.3</b> Part 3</a><ul>
<li class="chapter" data-level="3.3.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#reproducing-brysbaerts-examples"><i class="fa fa-check"></i><b>3.3.1</b> Reproducing Brysbaert’s Examples</a></li>
<li class="chapter" data-level="3.3.2" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#reproducing-brysbaert-variation-1-changing-correlation"><i class="fa fa-check"></i><b>3.3.2</b> Reproducing Brysbaert Variation 1: Changing Correlation</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#part-4"><i class="fa fa-check"></i><b>3.4</b> Part 4</a><ul>
<li class="chapter" data-level="3.4.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#two-by-two-anova-within-within-design"><i class="fa fa-check"></i><b>3.4.1</b> Two by two ANOVA, within-within design</a></li>
<li class="chapter" data-level="3.4.2" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#examine-variation-of-means-and-correlation"><i class="fa fa-check"></i><b>3.4.2</b> Examine variation of means and correlation</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#part-5"><i class="fa fa-check"></i><b>3.5</b> Part 5</a><ul>
<li class="chapter" data-level="3.5.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#x2-anova-within-design"><i class="fa fa-check"></i><b>3.5.1</b> 2x2 ANOVA, within design</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="mixed-anova.html"><a href="mixed-anova.html"><i class="fa fa-check"></i><b>4</b> Mixed ANOVA</a><ul>
<li class="chapter" data-level="4.1" data-path="mixed-anova.html"><a href="mixed-anova.html#x2-anova-within-between-design"><i class="fa fa-check"></i><b>4.1</b> 2x2 ANOVA, within-between design</a><ul>
<li class="chapter" data-level="4.1.1" data-path="mixed-anova.html"><a href="mixed-anova.html#two-by-two-anova-within-between-design-variation-1"><i class="fa fa-check"></i><b>4.1.1</b> Two by two ANOVA, within-between design Variation 1</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="power-for-three-way-interactions.html"><a href="power-for-three-way-interactions.html"><i class="fa fa-check"></i><b>5</b> Power for Three-way Interactions</a></li>
<li class="chapter" data-level="6" data-path="the-no-way-interactions.html"><a href="the-no-way-interactions.html"><i class="fa fa-check"></i><b>6</b> The ‘No-Way’ Interactions</a></li>
<li class="chapter" data-level="7" data-path="effect-of-varying-designs-on-power.html"><a href="effect-of-varying-designs-on-power.html"><i class="fa fa-check"></i><b>7</b> Effect of Varying Designs on Power</a><ul>
<li class="chapter" data-level="7.1" data-path="effect-of-varying-designs-on-power.html"><a href="effect-of-varying-designs-on-power.html#within-designs"><i class="fa fa-check"></i><b>7.1</b> Within Designs</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="error-control-in-exploratory-anova.html"><a href="error-control-in-exploratory-anova.html"><i class="fa fa-check"></i><b>8</b> Error Control in Exploratory ANOVA</a></li>
<li class="chapter" data-level="9" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html"><i class="fa fa-check"></i><b>9</b> Analytic Power Functions</a><ul>
<li class="chapter" data-level="9.1" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html#one-way-between-subjects-anova"><i class="fa fa-check"></i><b>9.1</b> One-Way Between Subjects ANOVA</a></li>
<li class="chapter" data-level="9.2" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html#two-way-between-subject-interaction"><i class="fa fa-check"></i><b>9.2</b> Two-way Between Subject Interaction</a></li>
<li class="chapter" data-level="9.3" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html#x3-between-subject-anova"><i class="fa fa-check"></i><b>9.3</b> 3x3 Between Subject ANOVA</a></li>
<li class="chapter" data-level="9.4" data-path="analytic-power-functions.html"><a href="analytic-power-functions.html#two-by-two-anova-within-design"><i class="fa fa-check"></i><b>9.4</b> Two by two ANOVA, within design</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="power-curve.html"><a href="power-curve.html"><i class="fa fa-check"></i><b>10</b> Power Curve</a><ul>
<li class="chapter" data-level="10.1" data-path="power-curve.html"><a href="power-curve.html#explore-increase-in-effect-size-for-moderated-interactions."><i class="fa fa-check"></i><b>10.1</b> Explore increase in effect size for moderated interactions.</a></li>
<li class="chapter" data-level="10.2" data-path="power-curve.html"><a href="power-curve.html#explore-increase-in-effect-size-for-cross-over-interactions."><i class="fa fa-check"></i><b>10.2</b> Explore increase in effect size for cross-over interactions.</a></li>
<li class="chapter" data-level="10.3" data-path="power-curve.html"><a href="power-curve.html#explore-increase-in-correlation-in-moderated-interactions."><i class="fa fa-check"></i><b>10.3</b> Explore increase in correlation in moderated interactions.</a></li>
<li class="chapter" data-level="10.4" data-path="power-curve.html"><a href="power-curve.html#increasing-correlation-in-on-factor-decreases-power-in-second-factor"><i class="fa fa-check"></i><b>10.4</b> Increasing correlation in on factor decreases power in second factor</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-1-direct-comparison-to-pwr2ppl.html"><a href="appendix-1-direct-comparison-to-pwr2ppl.html"><i class="fa fa-check"></i>Appendix 1: Direct Comparison to pwr2ppl</a><ul>
<li class="chapter" data-level="10.5" data-path="appendix-1-direct-comparison-to-pwr2ppl.html"><a href="appendix-1-direct-comparison-to-pwr2ppl.html#examples-from-chapter-5"><i class="fa fa-check"></i><b>10.5</b> Examples from Chapter 5</a><ul>
<li class="chapter" data-level="10.5.1" data-path="appendix-1-direct-comparison-to-pwr2ppl.html"><a href="appendix-1-direct-comparison-to-pwr2ppl.html#example-5.15.2"><i class="fa fa-check"></i><b>10.5.1</b> Example 5.1/5.2</a></li>
<li class="chapter" data-level="10.5.2" data-path="appendix-1-direct-comparison-to-pwr2ppl.html"><a href="appendix-1-direct-comparison-to-pwr2ppl.html#example-5.3"><i class="fa fa-check"></i><b>10.5.2</b> Example 5.3</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="appendix-1-direct-comparison-to-pwr2ppl.html"><a href="appendix-1-direct-comparison-to-pwr2ppl.html#examples-from-chapter-6"><i class="fa fa-check"></i><b>10.6</b> Examples from Chapter 6</a><ul>
<li class="chapter" data-level="10.6.1" data-path="appendix-1-direct-comparison-to-pwr2ppl.html"><a href="appendix-1-direct-comparison-to-pwr2ppl.html#example-from-table-6.2"><i class="fa fa-check"></i><b>10.6.1</b> Example from Table 6.2</a></li>
<li class="chapter" data-level="10.6.2" data-path="appendix-1-direct-comparison-to-pwr2ppl.html"><a href="appendix-1-direct-comparison-to-pwr2ppl.html#example-from-table-6.6"><i class="fa fa-check"></i><b>10.6.2</b> Example from Table 6.6</a></li>
<li class="chapter" data-level="10.6.3" data-path="appendix-1-direct-comparison-to-pwr2ppl.html"><a href="appendix-1-direct-comparison-to-pwr2ppl.html#example-from-table-6.8"><i class="fa fa-check"></i><b>10.6.3</b> Example from Table 6.8</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="appendix-1-direct-comparison-to-pwr2ppl.html"><a href="appendix-1-direct-comparison-to-pwr2ppl.html#example-from-chapter-7"><i class="fa fa-check"></i><b>10.7</b> Example from Chapter 7</a><ul>
<li class="chapter" data-level="10.7.1" data-path="appendix-1-direct-comparison-to-pwr2ppl.html"><a href="appendix-1-direct-comparison-to-pwr2ppl.html#from-table-7.2"><i class="fa fa-check"></i><b>10.7.1</b> From Table 7.2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-2-direct-comparison-to-morepower.html"><a href="appendix-2-direct-comparison-to-morepower.html"><i class="fa fa-check"></i>Appendix 2: Direct Comparison to MOREpower</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The Superpower R Package: Capabilities and Validation</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="repeated-measures-anova" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Repeated Measures ANOVA</h1>
<div id="part-1-1" class="section level2">
<h2><span class="header-section-number">3.1</span> Part 1</h2>
<p>In a repeated measures design multiple observations are collected from the same participants. In the simplest case, where there are two repeated observations, a repeated measures ANOVA equals a dependent or paired <em>t</em>-test. The difference compared to a between subject design is that repeated measures can be correlated, and in psychology, they often are. Let’s first explore the impact of this correlation on the power of a repeated measures ANOVA.</p>
<div id="two-conditions-medium-effect-size" class="section level3">
<h3><span class="header-section-number">3.1.1</span> Two conditions, medium effect size</h3>
<p>To illustrate the effect of correated observations, we start by simulating data for a medium effect size for a dependent (or paired, or within-subject) <em>t</em>-test. Let’s first look at G*power. If we want to perform an a-priori power analysis, we are asked to fill in the effect size dz. As Cohen (1988) writes, “The Z subscript is used to emphasize the fact that our raw score unit is no longer X or Y, but Z”, where Z are the difference scores of X-Y.</p>
<p><img src="screenshots/gpower_9.png" /></p>
<p>Within designs can have greater power to detect differences than between designs because the values are correlated, and a within design requires less participants because each participant provides multiple observations. One difference between an independent <em>t</em>-test and a dependent <em>t</em>-test is that an independent <em>t</em>-test has 2(n-1) degrees of freedom, while a dependent <em>t</em>-test has (n-1) degrees of freedom. The sample size needed in a two-group within-design (NW) relative to the sample needed in two-group between-designs (NB), assuming normal distributions, and ignoring the difference in degrees of freedom between the two types of tests, is (from Maxwell &amp; Delaney, 2004, p. 561, formula 45):</p>
<p><span class="math inline">\(N_{W}=\frac{N_{B}(1-\rho)}{2}\)</span></p>
<p>The division by 2 in the equation is due to the fact that in a two-condition within design every participant provides two data-points. The extent to which this reduces the sample size compared to a between-subject design depends on the correlation (<em>r</em>) between the two dependent variables, as indicated by the <code>1-r</code> part of the equation. If the correlation is 0, a within-subject design needs half as many participants as a between-subject design (e.g., 64 instead 128 participants), simply because every participants provides 2 datapoints. The higher the correlation, the larger the relative benefit of within designs, and whenever the correlation is negative (up to -1) the relative benefit disappears.</p>
<p>Whereas in an independent <em>t</em>-test the two observations are uncorrelated, in a within design the observations are correlated. This has an effect on the standard deviation of the difference scores. In turn, because the standardized effect size is the mean difference divided by the standard deviation of the difference scores, the correlation has an effect on the standardized mean difference in a within design, Cohen’s dz. The relation, as Cohen (1988, formula 2.3.7) explains, is:</p>
<p><span class="math inline">\(\sigma_{z}=\sigma\sqrt{2(1-\rho)}\)</span></p>
<p>Therefore, the relation between dz and d is <span class="math inline">\(\sqrt{2(1-\rho)}\)</span>. A given difference between population means for matched (dependent) samples is standardized by a value which is <span class="math inline">\(\sqrt{2(1-\rho)}\)</span> as large as would be the case were they independent. If we enter a correlation of 0.5 in the formula, we get <span class="math inline">\(\sqrt{2(0.5)}=1\)</span>. In other words, when the correlation is 0.5, d = dz. When there is a strong correlation between dependent variables, for example r = 0.9, we get <span class="math inline">\(d=d_{z}\sqrt{2(1-0.9)}\)</span>, and a dz of 1 would be a d = 0.45. Reversely, <span class="math inline">\(d_{z}=\frac{d}{\sqrt{2(1-r)}}\)</span>, so with a r = 0.9, a d of 1 would be a dz = 2.24. Some consider this increase in dz compared to d when observations are strongly correlated an ‘inflation’ when estimating effect sizes, but since the reduction in the standard deviation of the difference scores due to the correlation makes it easier to distinguish signal from noise in a hypothesis test, it leads to a clear power benefit.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Check sample size formula Maxwell</span>
<span class="co"># Power is pretty similar with n/2, same d (assuming r = 0.5). </span>
<span class="co"># Small differences due to df = 2(n-1) vs df = n-1</span>
<span class="kw">pwr.t.test</span>(<span class="dt">d =</span> <span class="fl">0.05</span>,
           <span class="dt">n =</span> <span class="kw">c</span>(<span class="dv">2000</span>, <span class="dv">4000</span>, <span class="dv">8000</span>),
           <span class="dt">sig.level =</span> <span class="fl">0.05</span>,
           <span class="dt">type =</span> <span class="st">&quot;two.sample&quot;</span>,
           <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</code></pre>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 2000, 4000, 8000
##               d = 0.05
##       sig.level = 0.05
##           power = 0.3524674, 0.6086764, 0.8853424
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pwr.t.test</span>(<span class="dt">d =</span> <span class="fl">0.05</span>,
           <span class="dt">n =</span> <span class="kw">c</span>(<span class="dv">1000</span>, <span class="dv">2000</span>, <span class="dv">4000</span>),
           <span class="dt">sig.level =</span> <span class="fl">0.05</span>,
           <span class="dt">type =</span> <span class="st">&quot;paired&quot;</span>,
           <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</code></pre>
<pre><code>## 
##      Paired t test power calculation 
## 
##               n = 1000, 2000, 4000
##               d = 0.05
##       sig.level = 0.05
##           power = 0.3520450, 0.6083669, 0.8852320
##     alternative = two.sided
## 
## NOTE: n is number of *pairs*</code></pre>
<p>There is no equivalent “fz” for Cohen’s <em>f</em> for a within subject ANOVA. For two groups, we can directly compute Cohen’s <em>f</em> from Cohen’s d for two groups, as Cohen (1988) describes, because f = 1/2d. For a d = 0.5, f = 0.25. In Gpower we can run a 2 group within-subject power analysis for ANOVA. We plan for 80% power, and reproduce the anaysis above for the dependent <em>t</em>-test. This works because the correlation is set to 0.5, when d = dz, and thus the transformation of f=1/2d works.</p>
<p><img src="screenshots/gpower_1.png" /></p>
<p>If we change the correlation to 0.7 and keep all other settings the same, the repeated measure a-priori power analysis yields a sample of 21. The correlation increases the power for the test.</p>
<p><img src="screenshots/gpower_11.png" /></p>
<p>To reproduce this analysis in Gpower with a dependent <em>t</em>-test we need to change dz following the formula above, <span class="math inline">\(d_{z}=\frac{0.5}{\sqrt{2(1-0.7)}}\)</span>, which yields dz = 0.6454972. If we enter this value in Gpower for an a-priori power analysis, we get the exact same results (as we should, since an repeated measures ANOVA with 2 groups equals a dependent <em>t</em>-test). This example illustrates that the correlation between dependent variables always factors into a power analysis, both for a dependent <em>t</em>-test, and for a repeated measures ANOVA. Because a dependent <em>t</em>-test uses dz the correlation might be less visible, but given the relation between d and dz, the correlation is always taken into account and can greatly improve power for within designs compared to between designs.</p>
<p><img src="screenshots/gpower_10.png" /></p>
<p>We can perform both these power analyses using simuations as well. We set groups to 2 for the simulation, n = 34 (which should give 80.777 power, according to the g*power program), a correlation among repeated measures of 0.5, and an alpha of 0.05. In this case, we simulate data with means -0.25 and 0.25, and set the sd to 1. This means we have a mean difference of 0.5, and a Cohen’s d of 0.5/1 = 0.5. In the first example, we set the correlation to 0.5, and the result should be 80.77% power, and an effect size estimate of 0.5 for the simple effect. We also calculate partial eta-squared for the ANOVA, which equals <span class="math inline">\(\frac{f^2}{f^2+1}\)</span>, or 0.05882353.</p>
<pre class="sourceCode r"><code class="sourceCode r">K &lt;-<span class="st"> </span><span class="dv">2</span>
n &lt;-<span class="st"> </span><span class="dv">34</span>
sd &lt;-<span class="st"> </span><span class="dv">1</span>
r &lt;-<span class="st"> </span><span class="fl">0.5</span>
alpha =<span class="st"> </span><span class="fl">0.05</span>
f &lt;-<span class="st"> </span><span class="fl">0.25</span>
f2 &lt;-<span class="st"> </span>f<span class="op">^</span><span class="dv">2</span>
ES &lt;-<span class="st"> </span>f2<span class="op">/</span>(f2 <span class="op">+</span><span class="st"> </span><span class="dv">1</span>)
ES</code></pre>
<pre><code>## [1] 0.05882353</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">mu &lt;-<span class="st"> </span><span class="kw">mu_from_ES</span>(<span class="dt">K =</span> K, <span class="dt">ES =</span> ES)
design =<span class="st"> </span><span class="kw">paste</span>(K,<span class="st">&quot;w&quot;</span>,<span class="dt">sep =</span> <span class="st">&quot;&quot;</span>)
labelnames &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;speed&quot;</span>, <span class="st">&quot;fast&quot;</span>, <span class="st">&quot;slow&quot;</span>)

design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> design,
                   <span class="dt">n =</span> n, 
                   <span class="dt">mu =</span> mu, 
                   <span class="dt">sd =</span> sd, 
                   <span class="dt">r =</span> r, 
                   <span class="dt">labelnames =</span> labelnames)

alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span></code></pre>
<pre class="sourceCode r"><code class="sourceCode r">simulation_result &lt;-<span class="st"> </span><span class="kw">ANOVA_power</span>(design_result, 
                                 <span class="dt">alpha_level =</span> alpha_level, 
                                 <span class="dt">nsims =</span> nsims,
                                 <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-98">Table 3.1: </span>Simulated ANOVA Result
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
power
</th>
<th style="text-align:right;">
effect_size
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
anova_speed
</td>
<td style="text-align:right;">
80.74
</td>
<td style="text-align:right;">
0.2149221
</td>
</tr>
</tbody>
</table>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-100">Table 3.2: </span>Exact ANOVA Result
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
power
</th>
<th style="text-align:right;">
partial_eta_squared
</th>
<th style="text-align:right;">
cohen_f
</th>
<th style="text-align:right;">
non_centrality
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
speed
</td>
<td style="text-align:right;">
80.78
</td>
<td style="text-align:right;">
0.2048
</td>
<td style="text-align:right;">
0.5075
</td>
<td style="text-align:right;">
8.5
</td>
</tr>
</tbody>
</table>
<p>The results of the simulation are indeed very close to 80.777%. Note that the simulation calculates Cohen’s dz effect sizes for paired comparisons - which here given the correlation of 0.5 is also 0.5 for a medium effect size.</p>
<p>We should see a larger dz if we increase the correlation, keeping the sample size the same, following the example in Gpower above. We repeat the simulation, and the only difference is a correlation between dependent variables of 0.7. This should yield an effect size dz = 0.6454972.</p>
<pre class="sourceCode r"><code class="sourceCode r">K &lt;-<span class="st"> </span><span class="dv">2</span>
n &lt;-<span class="st"> </span><span class="dv">21</span>
sd &lt;-<span class="st"> </span><span class="dv">1</span>
r &lt;-<span class="st"> </span><span class="fl">0.7</span>
alpha =<span class="st"> </span><span class="fl">0.05</span>
f &lt;-<span class="st"> </span><span class="fl">0.25</span>
f2 &lt;-<span class="st"> </span>f<span class="op">^</span><span class="dv">2</span>
ES &lt;-<span class="st"> </span>f2<span class="op">/</span>(f2 <span class="op">+</span><span class="st"> </span><span class="dv">1</span>)
ES</code></pre>
<pre><code>## [1] 0.05882353</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">mu &lt;-<span class="st"> </span><span class="kw">mu_from_ES</span>(<span class="dt">K =</span> K, <span class="dt">ES =</span> ES)
design =<span class="st"> </span><span class="kw">paste</span>(K,<span class="st">&quot;w&quot;</span>,<span class="dt">sep =</span> <span class="st">&quot;&quot;</span>)
labelnames &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;speed&quot;</span>, <span class="st">&quot;fast&quot;</span>, <span class="st">&quot;slow&quot;</span>)
design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> design,
                   <span class="dt">n =</span> n, 
                   <span class="dt">mu =</span> mu, 
                   <span class="dt">sd =</span> sd, 
                   <span class="dt">r =</span> r, 
                   <span class="dt">labelnames =</span> labelnames)

alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span>

design_result<span class="op">$</span>sigmatrix</code></pre>
<pre><code>##      fast slow
## fast  1.0  0.7
## slow  0.7  1.0</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">simulation_result &lt;-<span class="st"> </span><span class="kw">ANOVA_power</span>(design_result, 
                                 <span class="dt">alpha_level =</span> alpha_level, 
                                 <span class="dt">nsims =</span> nsims,
                                 <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-103">Table 3.3: </span>Simulated ANOVA Result
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
power
</th>
<th style="text-align:right;">
effect_size
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
anova_speed
</td>
<td style="text-align:right;">
80.48
</td>
<td style="text-align:right;">
0.3153414
</td>
</tr>
</tbody>
</table>
<pre class="sourceCode r"><code class="sourceCode r">exact_result &lt;-<span class="st"> </span><span class="kw">ANOVA_exact</span>(design_result,
                            <span class="dt">alpha_level =</span> alpha_level,
                            <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-105">Table 3.4: </span>Exact ANOVA Result
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
power
</th>
<th style="text-align:right;">
partial_eta_squared
</th>
<th style="text-align:right;">
cohen_f
</th>
<th style="text-align:right;">
non_centrality
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
speed
</td>
<td style="text-align:right;">
80.33
</td>
<td style="text-align:right;">
0.3043
</td>
<td style="text-align:right;">
0.6614
</td>
<td style="text-align:right;">
8.75
</td>
</tr>
</tbody>
</table>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#relation dz and f for within designs </span>
f &lt;-<span class="st"> </span><span class="fl">0.5</span><span class="op">*</span><span class="fl">0.6454972</span>
<span class="co">#  </span></code></pre>
<p>Entering this f in G*power, with a correlation of 0.5, yields the same as entering <code>f = 0.25</code> and <code>correlation = 0.7</code>.</p>
</div>
</div>
<div id="part-2-1" class="section level2">
<h2><span class="header-section-number">3.2</span> Part 2</h2>
<p>Here, we will examine a repeated measures experiment with 3 within-subject conditions, to illustrate how a repeated measures ANOVA extends a dependent <em>t</em>-test with 3 groups.</p>
<p>In the example for a two-group within design we provided a specific formula for the sample size benefit for two groups. The sample size needed in within-designs (NW) with more than 2 conditions, relative to the sample needed in between-designs (NB), assuming normal distributions and compound symmetry, and ignoring the difference in degrees of freedom between the two types of tests, is (from Maxwell &amp; Delaney, 2004, p. 562, formula 47):</p>
<p><span class="math inline">\(N_{W}=\frac{N_{B}(1-\rho)}{a}\)</span></p>
<p>Where a is the number of within-subject levels.</p>
<div id="the-relation-between-cohens-f-and-cohens-d" class="section level3">
<h3><span class="header-section-number">3.2.1</span> The relation between Cohen’s f and Cohen’s d</h3>
<p>Whereas in the case of a repeated measures ANOVA with 2 groups we could explain the principles of a power analysis by comparing our test against a <em>t</em>-test and Cohen’s d, this becomes more difficult when we have more than 2 groups. It is more useful to explain how to directly calculate Cohen’s <em>f</em>, the effect size used in power analyses for ANOVA. Cohen’s <em>f</em> is calculated following Cohen, 1988, formula 8.2.1 and 8.2.2:</p>
<p><span class="math inline">\(f = \sqrt{\frac{\frac{\sum(\mu-\overline{\mu})^2)}N}\sigma}\)</span></p>
<p>Imagine we have a within-subject experiment with 3 conditions. We ask people what they mood is when their alarm clock wakes them up, when they wake up naturally on a week day, and when they wake up naturally on a weekend day. Based on pilot data, we expect the means (on a 7 point validated mood scale) are 3.8, 4.2, and 4.3. The standard deviation is 0.9, and the correlation between the dependent measurements is 0.7. We can calculate Cohen’s <em>f</em> for the ANOVA, and Cohen’s dz for the contrasts:</p>
<pre class="sourceCode r"><code class="sourceCode r">mu &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">3.8</span>, <span class="fl">4.2</span>, <span class="fl">4.3</span>)
sd &lt;-<span class="st"> </span><span class="fl">0.9</span>
f &lt;-<span class="st"> </span><span class="kw">sqrt</span>(<span class="kw">sum</span>((mu <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(mu)) <span class="op">^</span><span class="st"> </span><span class="dv">2</span>) <span class="op">/</span><span class="st"> </span><span class="kw">length</span>(mu)) <span class="op">/</span><span class="st"> </span>sd 
<span class="co">#Cohen, 1988, formula 8.2.1 and 8.2.2</span>
  f</code></pre>
<pre><code>## [1] 0.2400274</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">  r &lt;-<span class="st"> </span><span class="fl">0.7</span>
  (<span class="fl">4.2</span> <span class="op">-</span><span class="st"> </span><span class="fl">3.8</span>) <span class="op">/</span><span class="st"> </span><span class="fl">0.9</span> <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(<span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>r))</code></pre>
<pre><code>## [1] 0.5737753</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">  (<span class="fl">4.3</span> <span class="op">-</span><span class="st"> </span><span class="fl">3.8</span>) <span class="op">/</span><span class="st"> </span><span class="fl">0.9</span> <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(<span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>r))</code></pre>
<pre><code>## [1] 0.7172191</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">  (<span class="fl">4.3</span> <span class="op">-</span><span class="st"> </span><span class="fl">4.2</span>) <span class="op">/</span><span class="st"> </span><span class="fl">0.9</span> <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(<span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>r))</code></pre>
<pre><code>## [1] 0.1434438</code></pre>
<p>The relation between Cohen’s d or dz and Cohen’s <em>f</em> becomes more difficult when there are multiple groups, because the relationship depends on the pattern of the means. Cohen (1988) presents calculations for three patterns, minimal variability (for example, for 5 means: -0.25, 0, 0, 0, 0.25), medium variability (for example, for 5 means: -0.25, -0.25, 0.25, 0.25, 0.25 or -0.25, -0.25, -0.25, 0.25, 0.25). For these three patterns, formula’s are available that compute Cohen’s <em>f</em> from Cohen’s d, where d is the effect size calculated for the difference between the largest and smallest mean (if the largest mean is 0.25 and the smallest mean is -0.25, 0.25 - -0.25 = 0.5, so d is 0.5 divided by the standard deviation of 0.9). In our example, d would be (4.3-3.8)/0.9 = 0.5555556. If we divide this value by <code>sqrt(2*(1-r))</code> we have dz = 0.5555556/0.7745967 = 0.7172191.</p>
<p>I have created a custom function that will calculate f from d, based on a specification of one of the three patterns of means. Our pattern is most similar (but not identical) to a maximum variability pattern (two means are high, one is lower). So we could attempt to calculate f from d (0.5555556), by calculating d from the largest and smallest mean:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#This function allows you to calculate f, d and eta squared </span>
<span class="co">#following Cohen, 1988, p 277</span>
<span class="co"># From Cohen, 1988, p 277</span>
<span class="co"># The patterns are:</span>
<span class="co"># I. Minimum variability: one mean at each end of d, </span>
<span class="co">#the remaining k- 2 means all at the midpoint.</span>
<span class="co"># 2. Intermediate variability: the k means equally spaced over d.</span>
<span class="co"># 3. Maximum variability: the means all at the end points of d.</span>

<span class="co"># For each of these patterns, </span>
<span class="co"># there is a fixed relationship between f and d for any given number of means, k.</span>

<span class="co"># Pattern 1. For any given range of means, d, the minimum standard</span>
<span class="co"># deviation, f1, results when the remaining k - 2 means are concentrated at</span>
<span class="co"># the mean of the means (0 when expressed in standard units), i.e., half-way</span>
<span class="co"># between the largest and smallest.</span>
<span class="co"># </span>
<span class="co"># Pattern 2. A pattern of medium variability results when the k means</span>
<span class="co"># are equally spaced over the range, and therefore at intervals of d/(k- 1).</span>
<span class="co"># </span>
<span class="co"># Pattern 3. It is demonstrable and intuitively evident that for any given</span>
<span class="co"># range the dispersion which yield~ the maximum standard deviation has the</span>
<span class="co"># k means falling at both extremes of the range. When k is even, !k fall at</span>
<span class="co"># - !d and the other !k fall at + !d; when k is odd, (k + I )/2 of the means</span>
<span class="co"># fall at either end and the (k- 1)/2 remaining means at the other. With this</span>
<span class="co"># pattern, for all even numbers of means, use formula (8.2.12).</span>
<span class="co"># When k is odd, and there is thus one more mean at one extreme than at</span>
<span class="co"># the other, use formula (8.2.13).</span>

calc_f_d_eta &lt;-<span class="st"> </span><span class="cf">function</span>(mu, sd, variability){
  <span class="cf">if</span> (variability <span class="op">==</span><span class="st"> &quot;minimum&quot;</span>) {
    k =<span class="st"> </span><span class="kw">length</span>(mu)
    d &lt;-<span class="st"> </span>(<span class="kw">max</span>(mu) <span class="op">-</span><span class="st"> </span><span class="kw">min</span>(mu)) <span class="op">/</span><span class="st"> </span>sd
    f &lt;-<span class="st"> </span>d <span class="op">*</span><span class="st"> </span><span class="kw">sqrt</span>(<span class="dv">1</span> <span class="op">/</span><span class="st"> </span>(<span class="dv">2</span> <span class="op">*</span><span class="st"> </span>k))
    f2 &lt;-<span class="st"> </span>f <span class="op">^</span><span class="st"> </span><span class="dv">2</span>
    ES &lt;-<span class="st"> </span>f2 <span class="op">/</span><span class="st"> </span>(f2 <span class="op">+</span><span class="st"> </span><span class="dv">1</span>)
  }
  <span class="cf">if</span> (variability <span class="op">==</span><span class="st"> &quot;medium&quot;</span>) {
    k =<span class="st"> </span><span class="kw">length</span>(mu)
    d &lt;-<span class="st"> </span>(<span class="kw">max</span>(mu) <span class="op">-</span><span class="st"> </span><span class="kw">min</span>(mu)) <span class="op">/</span><span class="st"> </span>sd
    f &lt;-<span class="st"> </span>(d <span class="op">/</span><span class="st"> </span><span class="dv">2</span>) <span class="op">*</span><span class="st"> </span><span class="kw">sqrt</span>((k <span class="op">+</span><span class="st"> </span><span class="dv">1</span>) <span class="op">/</span><span class="st"> </span>(<span class="dv">3</span> <span class="op">*</span><span class="st"> </span>(k <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)))
    f2 &lt;-<span class="st"> </span>f <span class="op">^</span><span class="st"> </span><span class="dv">2</span>
    ES &lt;-<span class="st"> </span>f2 <span class="op">/</span><span class="st"> </span>(f2 <span class="op">+</span><span class="st"> </span><span class="dv">1</span>)
  }
  <span class="cf">if</span> (variability <span class="op">==</span><span class="st"> &quot;maximum&quot;</span>) {
    k =<span class="st"> </span><span class="kw">length</span>(mu)
    d &lt;-<span class="st"> </span>(<span class="kw">max</span>(mu) <span class="op">-</span><span class="st"> </span><span class="kw">min</span>(mu)) <span class="op">/</span><span class="st"> </span>sd
    f &lt;-<span class="st"> </span><span class="kw">ifelse</span>(k <span class="op">%%</span><span class="st"> </span><span class="dv">2</span> <span class="op">==</span><span class="st"> </span><span class="dv">0</span>, <span class="fl">.5</span> <span class="op">*</span><span class="st"> </span>d, d <span class="op">*</span><span class="st"> </span>(<span class="kw">sqrt</span>(k <span class="op">^</span><span class="st"> </span><span class="dv">2</span> <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">/</span><span class="st"> </span>(<span class="dv">2</span> <span class="op">*</span><span class="st"> </span>k)))
    f2 &lt;-<span class="st"> </span>f <span class="op">^</span><span class="st"> </span><span class="dv">2</span>
    ES &lt;-<span class="st"> </span>f2 <span class="op">/</span><span class="st"> </span>(f2 <span class="op">+</span><span class="st"> </span><span class="dv">1</span>)
  }
  <span class="kw">invisible</span>(<span class="kw">list</span>(<span class="dt">mu =</span> mu,
                 <span class="dt">sd =</span> sd,
                 <span class="dt">d =</span> d,
                 <span class="dt">f =</span> f,
                 <span class="dt">f2 =</span> f2,
                 <span class="dt">ES =</span> ES))
}
res &lt;-<span class="st"> </span><span class="kw">calc_f_d_eta</span>(<span class="dt">mu =</span> mu, <span class="dt">sd =</span> sd, <span class="dt">variability =</span> <span class="st">&quot;maximum&quot;</span>)
res<span class="op">$</span>f</code></pre>
<pre><code>## [1] 0.2618914</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">res<span class="op">$</span>d</code></pre>
<pre><code>## [1] 0.5555556</code></pre>
<p>We see the Cohen’s <em>f</em> value is 0.2618914 and d = 0.5555556. The Cohen’s <em>f</em> is not perfectly accurate - it is assuming the pattern of means is 3.8, 4.3, 4.3, and not 3.8, 4.2, 4.3. If the means and sd is known, it is best to calculate Cohen’s <em>f</em> directly from these values.</p>
</div>
<div id="three-within-conditions-medium-effect-size" class="section level3">
<h3><span class="header-section-number">3.2.2</span> Three within conditions, medium effect size</h3>
<p>We can perform power analyses for within designs using simuations. We set groups to 3 for the simulation, n = 20, and the correlation between dependent variables to 0.8. If the true effect size is f = 0.25, and the alpha level is 0.05, the power is 96.6%.</p>
<p>In this case, we simulate data with means -0.3061862, 0.0000000, and 0.3061862, and set the sd to 1.</p>
<pre class="sourceCode r"><code class="sourceCode r">K &lt;-<span class="st"> </span><span class="dv">3</span>
n &lt;-<span class="st"> </span><span class="dv">20</span>
sd &lt;-<span class="st"> </span><span class="dv">1</span>
r &lt;-<span class="st"> </span><span class="fl">0.8</span>
alpha =<span class="st"> </span><span class="fl">0.05</span>
f &lt;-<span class="st"> </span><span class="fl">0.25</span>
f2 &lt;-<span class="st"> </span>f<span class="op">^</span><span class="dv">2</span>
ES &lt;-<span class="st"> </span>f2 <span class="op">/</span><span class="st"> </span>(f2 <span class="op">+</span><span class="st"> </span><span class="dv">1</span>)
ES</code></pre>
<pre><code>## [1] 0.05882353</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">mu &lt;-<span class="st"> </span><span class="kw">mu_from_ES</span>(<span class="dt">K =</span> K, <span class="dt">ES =</span> ES)

<span class="co">#Cohen, 1988, formula 8.2.1 and 8.2.2</span>
<span class="kw">sqrt</span>(<span class="kw">sum</span>((mu <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(mu)) <span class="op">^</span><span class="st"> </span><span class="dv">2</span>) <span class="op">/</span><span class="st"> </span><span class="kw">length</span>(mu)) <span class="op">/</span><span class="st"> </span>sd </code></pre>
<pre><code>## [1] 0.25</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">design =<span class="st"> </span><span class="kw">paste</span>(K, <span class="st">&quot;w&quot;</span>, <span class="dt">sep =</span> <span class="st">&quot;&quot;</span>)
labelnames &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;speed&quot;</span>, <span class="st">&quot;fast&quot;</span>, <span class="st">&quot;medium&quot;</span>, <span class="st">&quot;slow&quot;</span>)
design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> design,
                   <span class="dt">n =</span> n, 
                   <span class="dt">mu =</span> mu, 
                   <span class="dt">sd =</span> sd, 
                   <span class="dt">r =</span> r, 
                   <span class="dt">labelnames =</span> labelnames)

alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span></code></pre>
<pre class="sourceCode r"><code class="sourceCode r">simulation_result &lt;-<span class="st"> </span><span class="kw">ANOVA_power</span>(design_result, 
                                 <span class="dt">alpha_level =</span> alpha_level, 
                                 <span class="dt">nsims =</span> nsims,
                                 <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-111">Table 3.5: </span>Simulated ANOVA Result
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
power
</th>
<th style="text-align:right;">
effect_size
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
anova_speed
</td>
<td style="text-align:right;">
97.04
</td>
<td style="text-align:right;">
0.345486
</td>
</tr>
</tbody>
</table>
<pre class="sourceCode r"><code class="sourceCode r">exact_result &lt;-<span class="st"> </span><span class="kw">ANOVA_exact</span>(design_result,
                            <span class="dt">alpha_level =</span> alpha_level,
                            <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-113">Table 3.6: </span>Exact ANOVA Result
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
power
</th>
<th style="text-align:right;">
partial_eta_squared
</th>
<th style="text-align:right;">
cohen_f
</th>
<th style="text-align:right;">
non_centrality
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
speed
</td>
<td style="text-align:right;">
96.92
</td>
<td style="text-align:right;">
0.3304
</td>
<td style="text-align:right;">
0.7024
</td>
<td style="text-align:right;">
18.75
</td>
</tr>
</tbody>
</table>
<p>The results of the simulation are indeed very close to 96.9%. We can see this is in line with the power estimate from Gpower:</p>
<p><img src="screenshots/gpower_12.png" /></p>
<p>We can also validate this by creating the code to do a power analysis in R from scratch:</p>
<pre class="sourceCode r"><code class="sourceCode r">K &lt;-<span class="st"> </span><span class="dv">3</span> <span class="co">#three groups</span>
n &lt;-<span class="st"> </span><span class="dv">20</span>
sd &lt;-<span class="st"> </span><span class="dv">1</span>
r &lt;-<span class="st"> </span><span class="fl">0.8</span>
alpha =<span class="st"> </span><span class="fl">0.05</span>
f &lt;-<span class="st"> </span><span class="fl">0.25</span>
f2 &lt;-<span class="st"> </span>f<span class="op">^</span><span class="dv">2</span>
ES &lt;-<span class="st"> </span>f2 <span class="op">/</span><span class="st"> </span>(f2 <span class="op">+</span><span class="st"> </span><span class="dv">1</span>)
ES</code></pre>
<pre><code>## [1] 0.05882353</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">mu &lt;-<span class="st"> </span><span class="kw">mu_from_ES</span>(<span class="dt">K =</span> K, <span class="dt">ES =</span> ES)
design =<span class="st"> </span><span class="kw">paste</span>(K, <span class="st">&quot;w&quot;</span>, <span class="dt">sep =</span> <span class="st">&quot;&quot;</span>)
labelnames &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;speed&quot;</span>, <span class="st">&quot;fast&quot;</span>, <span class="st">&quot;medium&quot;</span>, <span class="st">&quot;slow&quot;</span>)
design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> design,
                   <span class="dt">n =</span> n, 
                   <span class="dt">mu =</span> mu, 
                   <span class="dt">sd =</span> sd, 
                   <span class="dt">r =</span> r, 
                   <span class="dt">labelnames =</span> labelnames)

<span class="kw">power_oneway_within</span>(design_result)<span class="op">$</span>power</code></pre>
<pre><code>## [1] 96.91634</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">power_oneway_within</span>(design_result)<span class="op">$</span>eta_p_<span class="dv">2</span></code></pre>
<pre><code>## [1] 0.05882353</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">power_oneway_within</span>(design_result)<span class="op">$</span>eta_p_<span class="dv">2</span>_SPSS</code></pre>
<pre><code>## [1] 0.3303965</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">power_oneway_within</span>(design_result)<span class="op">$</span>Cohen_f</code></pre>
<pre><code>## [1] 0.25</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">power_oneway_within</span>(design_result)<span class="op">$</span>Cohen_f_SPSS</code></pre>
<pre><code>## [1] 0.7024394</code></pre>
<p>We can even check the calculation of Cohen’s <em>f</em> SPSS style in GPower. We take the GPower settings as illustrated above. We click the ‘Options’ button, and check the radiobutton next to ‘As in SPSS’. Click ok, and you will notice that the ‘Corr among rep measures’ field has disappeared. The correlation does not need to be entered seperately, but is incorporated in Cohen’s <em>f</em>. The value of Cohen’s <em>f</em>, which was 0.25, has changed into 0.7024394. This is the SPSS equivalent. The value is much larger. This value, and it’s corresponding partial eta-squared, incorporate the correlation between observations.</p>
<p><img src="screenshots/gpower_14.png" /></p>
</div>
</div>
<div id="part-3-1" class="section level2">
<h2><span class="header-section-number">3.3</span> Part 3</h2>
<p>We first repeat the simulation by Brysbaert:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># give sample size</span>
N =<span class="st"> </span><span class="dv">75</span>
<span class="co"># give effect size d</span>
d1 =<span class="st"> </span><span class="fl">.4</span> <span class="co">#difference between the extremes</span>
d2 =<span class="st"> </span><span class="fl">.4</span> <span class="co">#third condition goes with the highest extreme</span>
<span class="co"># give the correlation between the conditions</span>
r =<span class="st"> </span><span class="fl">.5</span>
<span class="co"># give number of simulations</span>
nSim =<span class="st"> </span>nsims
<span class="co"># give alpha levels</span>
alpha1 =<span class="st"> </span><span class="fl">.05</span> <span class="co">#alpha level for the omnibus ANOVA</span>
alpha2 =<span class="st"> </span><span class="fl">.05</span> <span class="co">#also adjusted from original by DL</span></code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># create vectors to store p-values</span>
p1 &lt;-<span class="st"> </span><span class="kw">numeric</span>(nSim) <span class="co">#p-value omnibus ANOVA</span>
p2 &lt;-<span class="st"> </span><span class="kw">numeric</span>(nSim) <span class="co">#p-value first post hoc test</span>
p3 &lt;-<span class="st"> </span><span class="kw">numeric</span>(nSim) <span class="co">#p-value second post hoc test</span>
p4 &lt;-<span class="st"> </span><span class="kw">numeric</span>(nSim) <span class="co">#p-value third post hoc test</span>

<span class="co"># define correlation matrix</span>
rho &lt;-<span class="st"> </span><span class="kw">cbind</span>(<span class="kw">c</span>(<span class="dv">1</span>, r, r), <span class="kw">c</span>(r, <span class="dv">1</span>, r), <span class="kw">c</span>(r, r, <span class="dv">1</span>))
<span class="co"># define participant codes</span>
part &lt;-<span class="st"> </span><span class="kw">paste</span>(<span class="st">&quot;part&quot;</span>,<span class="kw">seq</span>(<span class="dv">1</span><span class="op">:</span>N))
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>nSim) {
  <span class="co">#for each simulated experiment</span>

  data =<span class="st"> </span><span class="kw">mvrnorm</span>(<span class="dt">n =</span> N,
  <span class="dt">mu =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>),
  <span class="dt">Sigma =</span> rho)
  data[, <span class="dv">2</span>] =<span class="st"> </span>data[, <span class="dv">2</span>] <span class="op">+</span><span class="st"> </span>d1
  data[, <span class="dv">3</span>] =<span class="st"> </span>data[, <span class="dv">3</span>] <span class="op">+</span><span class="st"> </span>d2
  datalong =<span class="st"> </span><span class="kw">c</span>(data[, <span class="dv">1</span>], data[, <span class="dv">2</span>], data[, <span class="dv">3</span>])
  conds =<span class="st"> </span><span class="kw">factor</span>(<span class="kw">rep</span>(letters[<span class="dv">24</span><span class="op">:</span><span class="dv">26</span>], <span class="dt">each =</span> N))
  partID =<span class="st"> </span><span class="kw">factor</span>(<span class="kw">rep</span>(part, <span class="dt">times =</span> <span class="dv">3</span>))
  output &lt;-<span class="st"> </span><span class="kw">data.frame</span>(partID, conds, datalong)
  test &lt;-<span class="st"> </span><span class="kw">aov</span>(datalong <span class="op">~</span><span class="st"> </span>conds <span class="op">+</span><span class="st"> </span><span class="kw">Error</span>(partID <span class="op">/</span><span class="st"> </span>conds), <span class="dt">data =</span> output)
  tests &lt;-<span class="st"> </span>(<span class="kw">summary</span>(test))
  p1[i] &lt;-<span class="st"> </span>tests<span class="op">$</span><span class="st">&#39;Error: partID:conds&#39;</span>[[<span class="dv">1</span>]]<span class="op">$</span><span class="st">&#39;Pr(&gt;F)&#39;</span>[[<span class="dv">1</span>]]
  p2[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(data[, <span class="dv">1</span>], data[, <span class="dv">2</span>], <span class="dt">paired =</span> <span class="ot">TRUE</span>)<span class="op">$</span>p.value
  p3[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(data[, <span class="dv">1</span>], data[, <span class="dv">3</span>], <span class="dt">paired =</span> <span class="ot">TRUE</span>)<span class="op">$</span>p.value
  p4[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(data[, <span class="dv">2</span>], data[, <span class="dv">3</span>], <span class="dt">paired =</span> <span class="ot">TRUE</span>)<span class="op">$</span>p.value
}</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#printing all unique tests (adjusted code by DL)</span>
<span class="kw">sum</span>(p1 <span class="op">&lt;</span><span class="st"> </span>alpha1) <span class="op">/</span><span class="st"> </span>nSim
<span class="kw">sum</span>(p2 <span class="op">&lt;</span><span class="st"> </span>alpha2) <span class="op">/</span><span class="st"> </span>nSim
<span class="kw">sum</span>(p3 <span class="op">&lt;</span><span class="st"> </span>alpha2) <span class="op">/</span><span class="st"> </span>nSim
<span class="kw">sum</span>(p4 <span class="op">&lt;</span><span class="st"> </span>alpha2) <span class="op">/</span><span class="st"> </span>nSim</code></pre>
<pre><code>## [1] 0.7961</code></pre>
<pre><code>## [1] 0.7624</code></pre>
<pre><code>## [1] 0.7574</code></pre>
<pre><code>## [1] 0.0452</code></pre>
<div id="reproducing-brysbaerts-examples" class="section level3">
<h3><span class="header-section-number">3.3.1</span> Reproducing Brysbaert’s Examples</h3>
<p>We can reproduce the same results as Brysbaert finds with his code:</p>
<pre class="sourceCode r"><code class="sourceCode r">design &lt;-<span class="st"> &quot;3w&quot;</span>
n &lt;-<span class="st"> </span><span class="dv">75</span>
mu &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.4</span>, <span class="fl">0.4</span>)
sd &lt;-<span class="st"> </span><span class="dv">1</span>
r &lt;-<span class="st"> </span><span class="fl">0.5</span>
labelnames &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;speed&quot;</span>, <span class="st">&quot;fast&quot;</span>, <span class="st">&quot;medium&quot;</span>, <span class="st">&quot;slow&quot;</span>)</code></pre>
<p>We create the within design, and run the simulation</p>
<pre class="sourceCode r"><code class="sourceCode r">design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> design,
                   <span class="dt">n =</span> n, 
                   <span class="dt">mu =</span> mu, 
                   <span class="dt">sd =</span> sd, 
                   <span class="dt">r =</span> r, 
                   <span class="dt">labelnames =</span> labelnames)</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">simulation_result &lt;-<span class="st"> </span><span class="kw">ANOVA_power</span>(design_result, 
                                 <span class="dt">alpha_level =</span> alpha_level, 
                                 <span class="dt">nsims =</span> nsims,
                                 <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-122">Table 3.7: </span>Simulated ANOVA Result
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
power
</th>
<th style="text-align:right;">
effect_size
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
anova_speed
</td>
<td style="text-align:right;">
95.25
</td>
<td style="text-align:right;">
0.1075912
</td>
</tr>
</tbody>
</table>
<pre class="sourceCode r"><code class="sourceCode r">exact_result &lt;-<span class="st"> </span><span class="kw">ANOVA_exact</span>(design_result,
                            <span class="dt">alpha_level =</span> alpha_level,
                            <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-124">Table 3.8: </span>Exact ANOVA Result
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
power
</th>
<th style="text-align:right;">
partial_eta_squared
</th>
<th style="text-align:right;">
cohen_f
</th>
<th style="text-align:right;">
non_centrality
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
speed
</td>
<td style="text-align:right;">
95.29
</td>
<td style="text-align:right;">
0.0976
</td>
<td style="text-align:right;">
0.3288
</td>
<td style="text-align:right;">
16
</td>
</tr>
</tbody>
</table>
<p><strong>Results</strong></p>
<p>The results of the simulation are very similar. Power for the ANOVA <em>F</em>-test is around 95.2%. For the three paired t-tests, power is around 92.7. This is in line with the a-priori power analysis when using g*power:</p>
<p><img src="screenshots/gpower_2.png" /></p>
<p>We can perform an post-hoc power analysis in G*power. We can calculate Cohen´s f based on the means and sd, using our own custom formula.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Our simulation is based onthe following means and sd:</span>
<span class="co"># mu &lt;- c(0, 0.4, 0.4)</span>
<span class="co"># sd &lt;- 1</span>
<span class="co"># Cohen, 1988, formula 8.2.1 and 8.2.2</span>
f &lt;-<span class="st"> </span><span class="kw">sqrt</span>(<span class="kw">sum</span>((mu <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(mu)) <span class="op">^</span><span class="st"> </span><span class="dv">2</span>) <span class="op">/</span><span class="st"> </span><span class="kw">length</span>(mu)) <span class="op">/</span><span class="st"> </span>sd 

<span class="co"># We can see why f = 0.5*d.</span>
<span class="co"># Imagine 2 group, mu = 1 and 2</span>
<span class="co"># Grand mean is 1.5, </span>
<span class="co"># we have sqrt(sum(0.5^2 + 0.5^2)/2), or sqrt(0.5/2), = 0.5.</span>
<span class="co"># For Cohen&#39;s d we use the difference, 2-1 = 1. </span></code></pre>
<p>The Cohen´s <em>f</em> is 0.1885618. We can enter the <em>f</em> (using the default ’as in G*Power 3.0’ in the option window) and enter a sample size of 75, number of groups as 1, number of measurements as 3, correlation as 0.5. This yields:</p>
<p><img src="screenshots/gpower_3.png" /></p>
</div>
<div id="reproducing-brysbaert-variation-1-changing-correlation" class="section level3">
<h3><span class="header-section-number">3.3.2</span> Reproducing Brysbaert Variation 1: Changing Correlation</h3>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># give sample size</span>
N =<span class="st"> </span><span class="dv">75</span>
<span class="co"># give effect size d</span>
d1 =<span class="st"> </span><span class="fl">.4</span> <span class="co">#difference between the extremes</span>
d2 =<span class="st"> </span><span class="fl">.4</span> <span class="co">#third condition goes with the highest extreme</span>
<span class="co"># give the correlation between the conditions</span>
r =<span class="st"> </span><span class="fl">.6</span> <span class="co">#increased correlation</span>
<span class="co"># give number of simulations</span>
nSim =<span class="st"> </span>nsims
<span class="co"># give alpha levels</span>
alpha1 =<span class="st"> </span><span class="fl">.05</span> <span class="co">#alpha level for the omnibus ANOVA</span>
alpha2 =<span class="st"> </span><span class="fl">.05</span> <span class="co">#also adjusted from original by DL</span></code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># create vectors to store p-values</span>
p1 &lt;-<span class="st"> </span><span class="kw">numeric</span>(nSim) <span class="co">#p-value omnibus ANOVA</span>
p2 &lt;-<span class="st"> </span><span class="kw">numeric</span>(nSim) <span class="co">#p-value first post hoc test</span>
p3 &lt;-<span class="st"> </span><span class="kw">numeric</span>(nSim) <span class="co">#p-value second post hoc test</span>
p4 &lt;-<span class="st"> </span><span class="kw">numeric</span>(nSim) <span class="co">#p-value third post hoc test</span>

<span class="co"># define correlation matrix</span>
rho &lt;-<span class="st"> </span><span class="kw">cbind</span>(<span class="kw">c</span>(<span class="dv">1</span>, r, r), <span class="kw">c</span>(r, <span class="dv">1</span>, r), <span class="kw">c</span>(r, r, <span class="dv">1</span>))
<span class="co"># define participant codes</span>
part &lt;-<span class="st"> </span><span class="kw">paste</span>(<span class="st">&quot;part&quot;</span>,<span class="kw">seq</span>(<span class="dv">1</span><span class="op">:</span>N))
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>nSim) {
  
  <span class="co">#for each simulated experiment</span>

  data =<span class="st"> </span><span class="kw">mvrnorm</span>(<span class="dt">n =</span> N,
  <span class="dt">mu =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>),
  <span class="dt">Sigma =</span> rho)
  data[, <span class="dv">2</span>] =<span class="st"> </span>data[, <span class="dv">2</span>] <span class="op">+</span><span class="st"> </span>d1
  data[, <span class="dv">3</span>] =<span class="st"> </span>data[, <span class="dv">3</span>] <span class="op">+</span><span class="st"> </span>d2
  datalong =<span class="st"> </span><span class="kw">c</span>(data[, <span class="dv">1</span>], data[, <span class="dv">2</span>], data[, <span class="dv">3</span>])
  conds =<span class="st"> </span><span class="kw">factor</span>(<span class="kw">rep</span>(letters[<span class="dv">24</span><span class="op">:</span><span class="dv">26</span>], <span class="dt">each =</span> N))
  partID =<span class="st"> </span><span class="kw">factor</span>(<span class="kw">rep</span>(part, <span class="dt">times =</span> <span class="dv">3</span>))
  output &lt;-<span class="st"> </span><span class="kw">data.frame</span>(partID, conds, datalong)
  test &lt;-<span class="st"> </span><span class="kw">aov</span>(datalong <span class="op">~</span><span class="st"> </span>conds <span class="op">+</span><span class="st"> </span><span class="kw">Error</span>(partID <span class="op">/</span><span class="st"> </span>conds), <span class="dt">data =</span> output)
  tests &lt;-<span class="st"> </span>(<span class="kw">summary</span>(test))
  p1[i] &lt;-<span class="st"> </span>tests<span class="op">$</span><span class="st">&#39;Error: partID:conds&#39;</span>[[<span class="dv">1</span>]]<span class="op">$</span><span class="st">&#39;Pr(&gt;F)&#39;</span>[[<span class="dv">1</span>]]
  p2[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(data[, <span class="dv">1</span>], data[, <span class="dv">2</span>], <span class="dt">paired =</span> <span class="ot">TRUE</span>)<span class="op">$</span>p.value
  p3[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(data[, <span class="dv">1</span>], data[, <span class="dv">3</span>], <span class="dt">paired =</span> <span class="ot">TRUE</span>)<span class="op">$</span>p.value
  p4[i] &lt;-<span class="st"> </span><span class="kw">t.test</span>(data[, <span class="dv">2</span>], data[, <span class="dv">3</span>], <span class="dt">paired =</span> <span class="ot">TRUE</span>)<span class="op">$</span>p.value
}</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(p1 <span class="op">&lt;</span><span class="st"> </span>alpha1) <span class="op">/</span><span class="st"> </span>nSim
<span class="kw">sum</span>(p2 <span class="op">&lt;</span><span class="st"> </span>alpha2) <span class="op">/</span><span class="st"> </span>nSim
<span class="kw">sum</span>(p3 <span class="op">&lt;</span><span class="st"> </span>alpha2) <span class="op">/</span><span class="st"> </span>nSim
<span class="kw">sum</span>(p4 <span class="op">&lt;</span><span class="st"> </span>alpha2) <span class="op">/</span><span class="st"> </span>nSim</code></pre>
<pre><code>## [1] 0.9472</code></pre>
<pre><code>## [1] 0.9245</code></pre>
<pre><code>## [1] 0.0503</code></pre>
<pre><code>## [1] 0.923</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">design &lt;-<span class="st"> &quot;3w&quot;</span>
n &lt;-<span class="st"> </span><span class="dv">75</span>
mu &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.4</span>, <span class="fl">0.4</span>)
sd &lt;-<span class="st"> </span><span class="dv">1</span>
r &lt;-<span class="st"> </span><span class="fl">0.6</span>
labelnames &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;SPEED&quot;</span>, 
                <span class="st">&quot;fast&quot;</span>, <span class="st">&quot;medium&quot;</span>, <span class="st">&quot;slow&quot;</span>)</code></pre>
<p>We create the 3-level repeated measures design, and run the simulation.</p>
<pre class="sourceCode r"><code class="sourceCode r">design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> design,
                   <span class="dt">n =</span> n, 
                   <span class="dt">mu =</span> mu, 
                   <span class="dt">sd =</span> sd, 
                   <span class="dt">r =</span> r, 
                   <span class="dt">labelnames =</span> labelnames)</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">simulation_result &lt;-<span class="st"> </span><span class="kw">ANOVA_power</span>(design_result, 
                                 <span class="dt">alpha_level =</span> alpha_level, 
                                 <span class="dt">nsims =</span> nsims,
                                 <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-133">Table 3.9: </span>Simulated ANOVA Result
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
power
</th>
<th style="text-align:right;">
effect_size
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
anova_SPEED
</td>
<td style="text-align:right;">
98.37
</td>
<td style="text-align:right;">
0.1287432
</td>
</tr>
</tbody>
</table>
<pre class="sourceCode r"><code class="sourceCode r">exact_result &lt;-<span class="st"> </span><span class="kw">ANOVA_exact</span>(design_result,
                            <span class="dt">alpha_level =</span> alpha_level,
                            <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-135">Table 3.10: </span>Exact ANOVA Result
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
power
</th>
<th style="text-align:right;">
partial_eta_squared
</th>
<th style="text-align:right;">
cohen_f
</th>
<th style="text-align:right;">
non_centrality
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
SPEED
</td>
<td style="text-align:right;">
98.35
</td>
<td style="text-align:right;">
0.119
</td>
<td style="text-align:right;">
0.3676
</td>
<td style="text-align:right;">
20
</td>
</tr>
</tbody>
</table>
<p>Again, this is similar to G*Power for the ANOVA:</p>
<p><a href="screenshots/gpower_4.png"></a></p>
</div>
</div>
<div id="part-4" class="section level2">
<h2><span class="header-section-number">3.4</span> Part 4</h2>
<div id="two-by-two-anova-within-within-design" class="section level3">
<h3><span class="header-section-number">3.4.1</span> Two by two ANOVA, within-within design</h3>
<p>We can simulate a 2x2 ANOVA, both factors manipulated within participants, with a specific sample size and effect size, to achieve a desired statistical power.</p>
<p>As Potvin &amp; Schutz (2000) explain, analytic procedures for a two-factor repeated measures ANOVA do not seem to exist. The main problem is quantifying the error variance (the denominator when calculating lambda or Cohen’s <em>f</em>). Simulation based aproaches provide a solution.</p>
<p>We can reproduce the simulation coded by <a href="https://cognitivedatascientist.com/2015/12/14/power-simulation-in-r-the-repeated-measures-anova-5/">Ben Amsel</a></p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># define the parameters</span>
<span class="co"># true effects (in this case, a double dissociation)</span>
mu =<span class="st"> </span><span class="kw">c</span>(<span class="dv">700</span>, <span class="dv">670</span>, <span class="dv">670</span>, <span class="dv">700</span>) 
sigma =<span class="st"> </span><span class="dv">150</span>  <span class="co"># population standard deviation</span>
rho =<span class="st"> </span><span class="fl">0.75</span> <span class="co"># correlation between repeated measures</span>
nsubs =<span class="st"> </span><span class="dv">25</span> <span class="co"># how many subjects?</span>
nsims =<span class="st"> </span>nsims <span class="co"># how many simulation replicates?</span>
 
<span class="co"># create 2 factors representing the 2 independent variables</span>
cond =<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">X1 =</span> <span class="kw">rep</span>(<span class="kw">factor</span>(letters[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>]), nsubs <span class="op">*</span><span class="st"> </span><span class="dv">2</span>),
                  <span class="dt">X2 =</span> <span class="kw">rep</span>(<span class="kw">factor</span>(letters[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>]), nsubs, <span class="dt">each =</span> <span class="dv">2</span>))
 
<span class="co"># create a subjects factor</span>
subject =<span class="st"> </span><span class="kw">factor</span>(<span class="kw">sort</span>(<span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span>nsubs, <span class="dv">4</span>)))
 
<span class="co"># combine above into the design matrix</span>
dm =<span class="st"> </span><span class="kw">data.frame</span>(subject, cond)</code></pre>
<p>Build Sigma: the population variance-covariance matrix</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># create k x k matrix populated with sigma</span>
sigma.mat &lt;-<span class="st"> </span><span class="kw">rep</span>(sigma, <span class="dv">4</span>)
S &lt;-
<span class="st">  </span><span class="kw">matrix</span>(sigma.mat,
  <span class="dt">ncol =</span> <span class="kw">length</span>(sigma.mat),
  <span class="dt">nrow =</span> <span class="kw">length</span>(sigma.mat))
 
<span class="co"># compute covariance between measures</span>
Sigma &lt;-<span class="st"> </span><span class="kw">t</span>(S) <span class="op">*</span><span class="st"> </span>S <span class="op">*</span><span class="st"> </span>rho  
 
<span class="co"># put the variances on the diagonal </span>
<span class="kw">diag</span>(Sigma) &lt;-<span class="st"> </span>sigma<span class="op">^</span><span class="dv">2</span>  </code></pre>
<p>Run the simulation</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># stack &#39;nsims&#39; individual data frames into one large data frame</span>
df =<span class="st"> </span>dm[<span class="kw">rep</span>(<span class="kw">seq_len</span>(<span class="kw">nrow</span>(dm)), nsims), ]
 
<span class="co"># add an index column to track the simulation run</span>
df<span class="op">$</span>simID =<span class="st"> </span><span class="kw">sort</span>(<span class="kw">rep</span>(<span class="kw">seq_len</span>(nsims), <span class="kw">nrow</span>(dm)))
 
<span class="co"># sample the observed data from a multivariate normal distribution</span>
<span class="co"># using MASS::mvrnorm with the mu and Sigma created earlier</span>
<span class="co"># and bind to the existing df</span>
 

make.y =<span class="st"> </span><span class="kw">expression</span>(<span class="kw">as.vector</span>(<span class="kw">t</span>(<span class="kw">mvrnorm</span>(nsubs, mu, Sigma))))
df<span class="op">$</span>y =<span class="st"> </span><span class="kw">as.vector</span>(<span class="kw">replicate</span>(nsims, <span class="kw">eval</span>(make.y)))             
 
<span class="co"># use do(), the general purpose complement to the specialized data </span>
<span class="co"># manipulation functions available in dplyr, to run the ANOVA on</span>
<span class="co"># each section of the grouped data frame created by group_by</span>
 

mods &lt;-<span class="st"> </span>df <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(simID) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">do</span>(<span class="dt">model =</span> <span class="kw">aov</span>(y <span class="op">~</span><span class="st"> </span>X1 <span class="op">*</span><span class="st"> </span>X2 <span class="op">+</span><span class="st"> </span><span class="kw">Error</span>(subject <span class="op">/</span><span class="st"> </span>(X1 <span class="op">*</span><span class="st"> </span>X2)), 
                 <span class="dt">qr =</span> <span class="ot">FALSE</span>, <span class="dt">data =</span> .)) 
 
<span class="co"># extract p-values for each effect and store in a data frame</span>
p_val_<span class="dv">1</span> =<span class="st"> </span><span class="kw">data.frame</span>(
  mods <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">do</span>(<span class="kw">as.data.frame</span>(<span class="kw">tidy</span>(.<span class="op">$</span>model[[<span class="dv">3</span>]])<span class="op">$</span>p.value[<span class="dv">1</span>])),
  mods <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">do</span>(<span class="kw">as.data.frame</span>(<span class="kw">tidy</span>(.<span class="op">$</span>model[[<span class="dv">4</span>]])<span class="op">$</span>p.value[<span class="dv">1</span>])),
  mods <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">do</span>(<span class="kw">as.data.frame</span>(<span class="kw">tidy</span>(.<span class="op">$</span>model[[<span class="dv">5</span>]])<span class="op">$</span>p.value[<span class="dv">1</span>])))
<span class="kw">colnames</span>(p_val_<span class="dv">1</span>) =<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;X1&#39;</span>,<span class="st">&#39;X2&#39;</span>,<span class="st">&#39;Interaction&#39;</span>)</code></pre>
<p>The empirical power is easy to compute, it’s just the proportion of simulation runs where <em>p</em> &lt; .05.</p>
<pre class="sourceCode r"><code class="sourceCode r">power.res =<span class="st"> </span><span class="kw">apply</span>(<span class="kw">as.matrix</span>(p_val_<span class="dv">1</span>), <span class="dv">2</span>, 
  <span class="cf">function</span>(x) <span class="kw">round</span>(<span class="kw">mean</span>(<span class="kw">ifelse</span>(x <span class="op">&lt;</span><span class="st"> </span><span class="fl">.05</span>, <span class="dv">1</span>, <span class="dv">0</span>) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>),<span class="dv">2</span>))
power.res</code></pre>
<pre><code>##          X1          X2 Interaction 
##        4.80        4.66       47.50</code></pre>
<p>Visualize the distributions of <em>p</em>-values</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot the known effects</span>

 
means =<span class="st"> </span><span class="kw">data.frame</span>(cond[<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>,], mu, <span class="dt">SE =</span> sigma <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(nsubs))
plt1 =<span class="st"> </span><span class="kw">ggplot</span>(means, <span class="kw">aes</span>(<span class="dt">y =</span> mu, <span class="dt">x =</span> X1, <span class="dt">fill =</span> X2)) <span class="op">+</span>
<span class="kw">geom_bar</span>(<span class="dt">position =</span> <span class="kw">position_dodge</span>(), <span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="op">+</span>
<span class="kw">geom_errorbar</span>(
<span class="kw">aes</span>(<span class="dt">ymin =</span> mu <span class="op">-</span><span class="st"> </span>SE, <span class="dt">ymax =</span> mu <span class="op">+</span><span class="st"> </span>SE),
<span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="dt">width =</span> <span class="fl">0.9</span>),
<span class="dt">size =</span> <span class="fl">.6</span>,
<span class="dt">width =</span> <span class="fl">.3</span>
) <span class="op">+</span>
<span class="kw">coord_cartesian</span>(<span class="dt">ylim =</span> <span class="kw">c</span>((.<span class="dv">7</span> <span class="op">*</span><span class="st"> </span><span class="kw">min</span>(mu)), <span class="fl">1.2</span> <span class="op">*</span><span class="st"> </span><span class="kw">max</span>(mu))) <span class="op">+</span>
<span class="kw">theme_bw</span>()

<span class="co"># melt the data into a ggplot friendly &#39;long&#39; format</span>

plotData &lt;-<span class="st"> </span><span class="kw">melt</span>(p_val_<span class="dv">1</span>, <span class="dt">value.name =</span> <span class="st">&#39;p&#39;</span>)

<span class="co"># plot each of the p-value distributions on a log scale</span>
<span class="kw">options</span>(<span class="dt">scipen =</span> <span class="dv">999</span>) <span class="co"># &#39;turn off&#39; scientific notation</span>
plt2 =<span class="st"> </span><span class="kw">ggplot</span>(plotData, <span class="kw">aes</span>(<span class="dt">x =</span> p)) <span class="op">+</span>
<span class="kw">scale_x_log10</span>(<span class="dt">breaks =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="fl">0.05</span>, <span class="fl">0.001</span>),
<span class="dt">labels =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="fl">0.05</span>, <span class="fl">0.001</span>)) <span class="op">+</span>
<span class="kw">geom_histogram</span>(<span class="dt">colour =</span> <span class="st">&quot;darkblue&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span>
<span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="fl">0.05</span>, <span class="dt">colour =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span>
<span class="kw">facet_grid</span>(variable <span class="op">~</span><span class="st"> </span>.) <span class="op">+</span>
<span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">expression</span>(Log[<span class="dv">10</span>] <span class="op">~</span><span class="st"> </span>P)) <span class="op">+</span>
<span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">color =</span> <span class="st">&#39;black&#39;</span>, <span class="dt">size =</span> <span class="dv">7</span>))

<span class="co"># arrange plots side by side and print</span>
<span class="kw">grid.arrange</span>(plt1, plt2, <span class="dt">nrow =</span> <span class="dv">1</span>)</code></pre>
<p><img src="SuperpowerValidation_files/figure-html/unnamed-chunk-141-1.png" width="672" /></p>
<p>We can reproduce this simulation:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># true effects (in this case, a double dissociation)</span>
mu =<span class="st"> </span><span class="kw">c</span>(<span class="dv">700</span>, <span class="dv">670</span>, <span class="dv">670</span>, <span class="dv">700</span>) 
sigma =<span class="st"> </span><span class="dv">150</span>  <span class="co"># population standard deviation</span>
n &lt;-<span class="st"> </span><span class="dv">25</span>
sd &lt;-<span class="st"> </span><span class="dv">150</span>
r &lt;-<span class="st"> </span><span class="fl">0.75</span>
string =<span class="st"> &quot;2w*2w&quot;</span>
alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span>
labelnames =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;age&quot;</span>, <span class="st">&quot;old&quot;</span>, <span class="st">&quot;young&quot;</span>, <span class="st">&quot;color&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;red&quot;</span>)
design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> string,
                              <span class="dt">n =</span> n, 
                              <span class="dt">mu =</span> mu, 
                              <span class="dt">sd =</span> sd, 
                              <span class="dt">r =</span> r, 
                              <span class="dt">labelnames =</span> labelnames)</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">simulation_result &lt;-<span class="st"> </span><span class="kw">ANOVA_power</span>(design_result, 
                                 <span class="dt">alpha_level =</span> alpha_level, 
                                 <span class="dt">nsims =</span> nsims,
                                 <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-144">Table 3.11: </span>Simulated ANOVA Result
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
power
</th>
<th style="text-align:right;">
effect_size
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
anova_age
</td>
<td style="text-align:right;">
4.99
</td>
<td style="text-align:right;">
0.0396351
</td>
</tr>
<tr>
<td style="text-align:left;">
anova_color
</td>
<td style="text-align:right;">
5.17
</td>
<td style="text-align:right;">
0.0405810
</td>
</tr>
<tr>
<td style="text-align:left;">
anova_age:color
</td>
<td style="text-align:right;">
47.80
</td>
<td style="text-align:right;">
0.1641690
</td>
</tr>
</tbody>
</table>
<pre class="sourceCode r"><code class="sourceCode r">exact_result &lt;-<span class="st"> </span><span class="kw">ANOVA_exact</span>(design_result,
                            <span class="dt">alpha_level =</span> alpha_level,
                            <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-146">Table 3.12: </span>Exact ANOVA Result
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
power
</th>
<th style="text-align:right;">
partial_eta_squared
</th>
<th style="text-align:right;">
cohen_f
</th>
<th style="text-align:right;">
non_centrality
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
5.0
</td>
<td style="text-align:right;">
0.0000
</td>
<td style="text-align:right;">
0.0000
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
color
</td>
<td style="text-align:right;">
5.0
</td>
<td style="text-align:right;">
0.0000
</td>
<td style="text-align:right;">
0.0000
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
age:color
</td>
<td style="text-align:right;">
48.4
</td>
<td style="text-align:right;">
0.1429
</td>
<td style="text-align:right;">
0.4082
</td>
<td style="text-align:right;">
4
</td>
</tr>
</tbody>
</table>
<p>The simulations yield closely matching results.</p>
</div>
<div id="examine-variation-of-means-and-correlation" class="section level3">
<h3><span class="header-section-number">3.4.2</span> Examine variation of means and correlation</h3>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># define the parameters</span>
<span class="co"># true effects (in this case, a double dissociation)</span>
mu =<span class="st"> </span><span class="kw">c</span>(<span class="dv">700</span>, <span class="dv">670</span>, <span class="dv">690</span>, <span class="dv">750</span>) 
sigma =<span class="st"> </span><span class="dv">150</span>  <span class="co"># population standard deviation</span>
rho =<span class="st"> </span><span class="fl">0.4</span> <span class="co"># correlation between repeated measures</span>
nsubs =<span class="st"> </span><span class="dv">25</span> <span class="co"># how many subjects?</span>
nsims =<span class="st"> </span>nsims <span class="co"># how many simulation replicates?</span>
 
<span class="co"># create 2 factors representing the 2 independent variables</span>
cond =<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">X1 =</span> <span class="kw">rep</span>(<span class="kw">factor</span>(letters[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>]), nsubs <span class="op">*</span><span class="st"> </span><span class="dv">2</span>),
<span class="dt">X2 =</span> <span class="kw">rep</span>(<span class="kw">factor</span>(letters[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>]), nsubs, <span class="dt">each =</span> <span class="dv">2</span>))
 
<span class="co"># create a subjects factor</span>
subject =<span class="st"> </span><span class="kw">factor</span>(<span class="kw">sort</span>(<span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span>nsubs, <span class="dv">4</span>)))
 
<span class="co"># combine above into the design matrix</span>
dm =<span class="st"> </span><span class="kw">data.frame</span>(subject, cond)</code></pre>
<p>Build Sigma: the population variance-covariance matrix</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># create k x k matrix populated with sigma</span>
sigma.mat &lt;-<span class="st"> </span><span class="kw">rep</span>(sigma, <span class="dv">4</span>)
S &lt;-
<span class="kw">matrix</span>(sigma.mat,
<span class="dt">ncol =</span> <span class="kw">length</span>(sigma.mat),
<span class="dt">nrow =</span> <span class="kw">length</span>(sigma.mat))

<span class="co"># compute covariance between measures</span>
Sigma &lt;-<span class="st"> </span><span class="kw">t</span>(S) <span class="op">*</span><span class="st"> </span>S <span class="op">*</span><span class="st"> </span>rho

<span class="co"># put the variances on the diagonal</span>
<span class="kw">diag</span>(Sigma) &lt;-<span class="st"> </span>sigma <span class="op">^</span><span class="st"> </span><span class="dv">2</span>  </code></pre>
<p>Run the simulation</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># stack &#39;nsims&#39; individual data frames into one large data frame</span>
df =<span class="st"> </span>dm[<span class="kw">rep</span>(<span class="kw">seq_len</span>(<span class="kw">nrow</span>(dm)), nsims), ]
 
<span class="co"># add an index column to track the simulation run</span>
df<span class="op">$</span>simID =<span class="st"> </span><span class="kw">sort</span>(<span class="kw">rep</span>(<span class="kw">seq_len</span>(nsims), <span class="kw">nrow</span>(dm)))
 
<span class="co"># sample the observed data from a multivariate normal distribution</span>
<span class="co"># using MASS::mvrnorm with the mu and Sigma created earlier</span>
<span class="co"># and bind to the existing df</span>
 

make.y =<span class="st"> </span><span class="kw">expression</span>(<span class="kw">as.vector</span>(<span class="kw">t</span>(<span class="kw">mvrnorm</span>(nsubs, mu, Sigma))))
df<span class="op">$</span>y =<span class="st"> </span><span class="kw">as.vector</span>(<span class="kw">replicate</span>(nsims, <span class="kw">eval</span>(make.y)))             
 
<span class="co"># use do(), the general purpose complement to the specialized data </span>
<span class="co"># manipulation functions available in dplyr, to run the ANOVA on</span>
<span class="co"># each section of the grouped data frame created by group_by</span>
 

mods &lt;-<span class="st"> </span>df <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(simID) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">do</span>(<span class="dt">model =</span> <span class="kw">aov</span>(y <span class="op">~</span><span class="st"> </span>X1 <span class="op">*</span><span class="st"> </span>X2 <span class="op">+</span><span class="st"> </span><span class="kw">Error</span>(subject <span class="op">/</span><span class="st"> </span>(X1 <span class="op">*</span><span class="st"> </span>X2)), 
                 <span class="dt">qr =</span> <span class="ot">FALSE</span>, <span class="dt">data =</span> .))
  
  <span class="co"># extract p-values for each effect and store in a data frame</span>
  p_val_<span class="dv">2</span> =<span class="st"> </span><span class="kw">data.frame</span>(mods <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">                   </span><span class="kw">do</span>(<span class="kw">as.data.frame</span>(<span class="kw">tidy</span>(.<span class="op">$</span>model[[<span class="dv">3</span>]])<span class="op">$</span>p.value[<span class="dv">1</span>])),
  mods <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">do</span>(<span class="kw">as.data.frame</span>(<span class="kw">tidy</span>(.<span class="op">$</span>model[[<span class="dv">4</span>]])<span class="op">$</span>p.value[<span class="dv">1</span>])),
  mods <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">do</span>(<span class="kw">as.data.frame</span>(<span class="kw">tidy</span>(.<span class="op">$</span>model[[<span class="dv">5</span>]])<span class="op">$</span>p.value[<span class="dv">1</span>])))
  <span class="kw">colnames</span>(p_val_<span class="dv">2</span>) =<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;X1&#39;</span>, <span class="st">&#39;X2&#39;</span>, <span class="st">&#39;Interaction&#39;</span>)</code></pre>
<p>The empirical power is easy to compute, it’s just the proportion of simulation runs where p &lt;. 05.</p>
<pre class="sourceCode r"><code class="sourceCode r">power.res =<span class="st"> </span><span class="kw">apply</span>(<span class="kw">as.matrix</span>(p_val_<span class="dv">2</span>), <span class="dv">2</span>, 
  <span class="cf">function</span>(x) <span class="kw">round</span>(<span class="kw">mean</span>(<span class="kw">ifelse</span>(x <span class="op">&lt;</span><span class="st"> </span><span class="fl">.05</span>, <span class="dv">1</span>, <span class="dv">0</span>) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>),<span class="dv">2</span>))
power.res</code></pre>
<pre><code>##          X1          X2 Interaction 
##        9.47       30.17       46.45</code></pre>
<p>Visualize the distributions of <em>p</em>-values</p>
<pre class="sourceCode r"><code class="sourceCode r">means =<span class="st"> </span><span class="kw">data.frame</span>(cond[<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>,], mu, <span class="dt">SE =</span> sigma <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(nsubs))
plt1 =<span class="st"> </span><span class="kw">ggplot</span>(means, <span class="kw">aes</span>(<span class="dt">y =</span> mu, <span class="dt">x =</span> X1, <span class="dt">fill =</span> X2)) <span class="op">+</span>
<span class="kw">geom_bar</span>(<span class="dt">position =</span> <span class="kw">position_dodge</span>(), <span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="op">+</span>
<span class="kw">geom_errorbar</span>(
<span class="kw">aes</span>(<span class="dt">ymin =</span> mu <span class="op">-</span><span class="st"> </span>SE, <span class="dt">ymax =</span> mu <span class="op">+</span><span class="st"> </span>SE),
<span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="dt">width =</span> <span class="fl">0.9</span>),
<span class="dt">size =</span> <span class="fl">.6</span>,
<span class="dt">width =</span> <span class="fl">.3</span>
) <span class="op">+</span>
<span class="kw">coord_cartesian</span>(<span class="dt">ylim =</span> <span class="kw">c</span>((.<span class="dv">7</span> <span class="op">*</span><span class="st"> </span><span class="kw">min</span>(mu)), <span class="fl">1.2</span> <span class="op">*</span><span class="st"> </span><span class="kw">max</span>(mu))) <span class="op">+</span>
<span class="kw">theme_bw</span>()
 
<span class="co"># melt the data into a ggplot friendly &#39;long&#39; format</span>

plotData &lt;-<span class="st"> </span><span class="kw">melt</span>(p_val_<span class="dv">2</span>, <span class="dt">value.name =</span> <span class="st">&#39;p&#39;</span>)
 
<span class="co"># plot each of the p-value distributions on a log scale</span>
<span class="kw">options</span>(<span class="dt">scipen =</span> <span class="dv">999</span>) <span class="co"># &#39;turn off&#39; scientific notation</span>
plt2 =<span class="st"> </span><span class="kw">ggplot</span>(plotData, <span class="kw">aes</span>(<span class="dt">x =</span> p)) <span class="op">+</span>
<span class="kw">scale_x_log10</span>(<span class="dt">breaks =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="fl">0.05</span>, <span class="fl">0.001</span>),
<span class="dt">labels =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="fl">0.05</span>, <span class="fl">0.001</span>)) <span class="op">+</span>
<span class="kw">geom_histogram</span>(<span class="dt">colour =</span> <span class="st">&quot;darkblue&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span>
<span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="fl">0.05</span>, <span class="dt">colour =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span>
<span class="kw">facet_grid</span>(variable <span class="op">~</span><span class="st"> </span>.) <span class="op">+</span>
<span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">expression</span>(Log[<span class="dv">10</span>] <span class="op">~</span><span class="st"> </span>P)) <span class="op">+</span>
<span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">color =</span> <span class="st">&#39;black&#39;</span>, <span class="dt">size =</span> <span class="dv">7</span>))

<span class="co"># arrange plots side by side and print</span>
<span class="kw">grid.arrange</span>(plt1, plt2, <span class="dt">nrow =</span> <span class="dv">1</span>)</code></pre>
<p><img src="SuperpowerValidation_files/figure-html/unnamed-chunk-151-1.png" width="672" /></p>
<p>We can reproduce this simulation:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># true effects (in this case, a double dissociation)</span>
mu =<span class="st"> </span><span class="kw">c</span>(<span class="dv">700</span>, <span class="dv">670</span>, <span class="dv">690</span>, <span class="dv">750</span>) 
sigma =<span class="st"> </span><span class="dv">150</span>  <span class="co"># population standard deviation</span>
n &lt;-<span class="st"> </span><span class="dv">25</span>
sd &lt;-<span class="st"> </span><span class="dv">150</span>
r &lt;-<span class="st"> </span><span class="fl">0.4</span>
string =<span class="st"> &quot;2w*2w&quot;</span>
alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span>
labelnames =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;AGE&quot;</span>, <span class="st">&quot;old&quot;</span>, <span class="st">&quot;young&quot;</span>, 
               <span class="st">&quot;COLOR&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;red&quot;</span>)

design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> string,
                              <span class="dt">n =</span> n, 
                              <span class="dt">mu =</span> mu, 
                              <span class="dt">sd =</span> sd, 
                              <span class="dt">r =</span> r, 
                              <span class="dt">labelnames =</span> labelnames)</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">simulation_result &lt;-<span class="st"> </span><span class="kw">ANOVA_power</span>(design_result, 
                                 <span class="dt">alpha_level =</span> <span class="fl">0.05</span>, 
                                 <span class="dt">nsims =</span> nsims)</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-154">Table 3.13: </span>Simulated ANOVA Result
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
power
</th>
<th style="text-align:right;">
effect_size
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
anova_AGE
</td>
<td style="text-align:right;">
30.60
</td>
<td style="text-align:right;">
0.1143202
</td>
</tr>
<tr>
<td style="text-align:left;">
anova_COLOR
</td>
<td style="text-align:right;">
9.41
</td>
<td style="text-align:right;">
0.0541130
</td>
</tr>
<tr>
<td style="text-align:left;">
anova_AGE:COLOR
</td>
<td style="text-align:right;">
46.22
</td>
<td style="text-align:right;">
0.1595391
</td>
</tr>
</tbody>
</table>
<pre class="sourceCode r"><code class="sourceCode r">exact_result &lt;-<span class="st"> </span><span class="kw">ANOVA_exact</span>(design_result, <span class="dt">alpha_level =</span> alpha_level)</code></pre>
<pre><code>## Power and Effect sizes for ANOVA tests
##           power partial_eta_squared cohen_f non_centrality
## AGE       30.40              0.0864  0.3074         2.2685
## COLOR      9.51              0.0171  0.1318         0.4167
## AGE:COLOR 45.98              0.1351  0.3953         3.7500
## 
## Power and Effect sizes for contrasts
##                                            power effect_size
## p_AGE_old_COLOR_blue_AGE_old_COLOR_red     14.16     -0.1826
## p_AGE_old_COLOR_blue_AGE_young_COLOR_blue   5.98     -0.0609
## p_AGE_old_COLOR_blue_AGE_young_COLOR_red   30.91      0.3043
## p_AGE_old_COLOR_red_AGE_young_COLOR_blue    9.00      0.1217
## p_AGE_old_COLOR_red_AGE_young_COLOR_red    64.66      0.4869
## p_AGE_young_COLOR_blue_AGE_young_COLOR_red 41.80      0.3651</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-156">Table 3.14: </span>Exact ANOVA Result
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
power
</th>
<th style="text-align:right;">
partial_eta_squared
</th>
<th style="text-align:right;">
cohen_f
</th>
<th style="text-align:right;">
non_centrality
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
AGE
</td>
<td style="text-align:right;">
30.40
</td>
<td style="text-align:right;">
0.0864
</td>
<td style="text-align:right;">
0.3074
</td>
<td style="text-align:right;">
2.2685
</td>
</tr>
<tr>
<td style="text-align:left;">
COLOR
</td>
<td style="text-align:right;">
9.51
</td>
<td style="text-align:right;">
0.0171
</td>
<td style="text-align:right;">
0.1318
</td>
<td style="text-align:right;">
0.4167
</td>
</tr>
<tr>
<td style="text-align:left;">
AGE:COLOR
</td>
<td style="text-align:right;">
45.98
</td>
<td style="text-align:right;">
0.1351
</td>
<td style="text-align:right;">
0.3953
</td>
<td style="text-align:right;">
3.7500
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="part-5" class="section level2">
<h2><span class="header-section-number">3.5</span> Part 5</h2>
<p><strong>Credit for the non-centrality parameter for the interaction goes to Andrew Vigotsky</strong></p>
<div id="x2-anova-within-design" class="section level3">
<h3><span class="header-section-number">3.5.1</span> 2x2 ANOVA, within design</h3>
<p>Potvin &amp; Schutz (2000) simulate a wide range of repeated measure designs. They give an example of a 3x3 design, with the following correlation matrix:</p>
<p><img src="screenshots/PS2000.png" /></p>
<p>Variances were set to 1 (so all covariance matrices in their simulations were identical). In this specific example, the white fields are related to the correlation for the A main effect (these cells have the same level for B, but different levels of A). The grey cells are related to the main effect of B (the cells have the same level of A, but different levels of B). Finally, the black cells are related to the AxB interaction (they have different levels of A and B). The diagonal (all 1) relate to cells with the same levels of A and B.</p>
<p>Potvin &amp; Schulz (2000) examine power for 2x2 within ANOVA designs and develop approximations of the error variance. For a design with 2 within factors (A and B) these are:</p>
<p>For the main effect of A:
<span class="math inline">\(\sigma _ { e } ^ { 2 } = \sigma ^ { 2 } ( 1 - \overline { \rho } _ { A } ) + \sigma ^ { 2 } ( q - 1 ) ( \overline { \rho } _ { B } - \overline { \rho } _ { AB } )\)</span></p>
<p>For the main effectof B:
<span class="math inline">\(\sigma _ { e } ^ { 2 } = \sigma ^ { 2 } ( 1 - \overline { \rho } _ { B } ) + \sigma ^ { 2 } ( p - 1 ) ( \overline { \rho } _ { A } - \overline { \rho } _ { A B } )\)</span></p>
<p>For the interaction between A and B:
<span class="math inline">\(\sigma _ { e } ^ { 2 } = \sigma ^ { 2 } ( 1 - \rho _ { \max } ) - \sigma ^ { 2 } ( \overline { \rho } _ { \min } - \overline { \rho } _ { AB } )\)</span></p>
<p>Let’s now compare the formulas in Potvin and Schutz (2000) with <code>Superpower</code> with a simple scenario.</p>
<pre class="sourceCode r"><code class="sourceCode r">mu =<span class="st"> </span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">4</span>,<span class="dv">2</span>) 
n &lt;-<span class="st"> </span><span class="dv">20</span>
sd &lt;-<span class="st"> </span><span class="dv">5</span>
r &lt;-<span class="st"> </span><span class="fl">.77</span>
string =<span class="st"> &quot;2w*2w&quot;</span>
alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span>


design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> string,
                              <span class="dt">n =</span> n, 
                              <span class="dt">mu =</span> mu, 
                              <span class="dt">sd =</span> sd, 
                              <span class="dt">r =</span> r, 
                              <span class="dt">labelnames =</span> labelnames,
                              <span class="dt">plot =</span> <span class="ot">TRUE</span>)</code></pre>
<p><img src="SuperpowerValidation_files/figure-html/unnamed-chunk-157-1.png" width="672" /></p>
<pre class="sourceCode r"><code class="sourceCode r">design_result<span class="op">$</span>cor_mat</code></pre>
<pre><code>##            old_blue old_red young_blue young_red
## old_blue       1.00    0.77       0.77      0.77
## old_red        0.77    1.00       0.77      0.77
## young_blue     0.77    0.77       1.00      0.77
## young_red      0.77    0.77       0.77      1.00</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">exact_result &lt;-<span class="st"> </span><span class="kw">ANOVA_exact</span>(design_result,
                            <span class="dt">alpha_level =</span> alpha_level,
                            <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-159">Table 3.15: </span>Exact ANOVA Result
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
power
</th>
<th style="text-align:right;">
partial_eta_squared
</th>
<th style="text-align:right;">
cohen_f
</th>
<th style="text-align:right;">
non_centrality
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
AGE
</td>
<td style="text-align:right;">
75.61
</td>
<td style="text-align:right;">
0.2917
</td>
<td style="text-align:right;">
0.6418
</td>
<td style="text-align:right;">
7.8261
</td>
</tr>
<tr>
<td style="text-align:left;">
COLOR
</td>
<td style="text-align:right;">
75.61
</td>
<td style="text-align:right;">
0.2917
</td>
<td style="text-align:right;">
0.6418
</td>
<td style="text-align:right;">
7.8261
</td>
</tr>
<tr>
<td style="text-align:left;">
AGE:COLOR
</td>
<td style="text-align:right;">
14.36
</td>
<td style="text-align:right;">
0.0438
</td>
<td style="text-align:right;">
0.2139
</td>
<td style="text-align:right;">
0.8696
</td>
</tr>
</tbody>
</table>
<p>Further, as we use the analytical solution below, the variance components should be equal to the corresponding MSE from the <code>ANOVA_exact</code> produced <code>anova_table</code> object.</p>
<pre class="sourceCode r"><code class="sourceCode r">exact_result<span class="op">$</span>aov_result<span class="op">$</span>anova_table</code></pre>
<pre><code>## Anova Table (Type 3 tests)
## 
## Response: y
##           num Df den Df  MSE      F      pes  Pr(&gt;F)  
## AGE            1     19 5.75 7.8261 0.291734 0.01149 *
## COLOR          1     19 5.75 7.8261 0.291734 0.01149 *
## AGE:COLOR      1     19 5.75 0.8696 0.043764 0.36278  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We can try to use the formula in Potvin &amp; Schutz (2000).</p>
<pre class="sourceCode r"><code class="sourceCode r">k &lt;-<span class="st"> </span><span class="dv">1</span> <span class="co">#one group (because all factors are within)</span>

rho_A &lt;-<span class="st"> </span><span class="fl">.77</span> <span class="co">#mean r for factor A</span>

rho_B &lt;-<span class="st"> </span><span class="fl">.77</span> <span class="co">#mean r for factor B</span>

rho_AB &lt;-<span class="st"> </span><span class="fl">.77</span> <span class="co">#mean r for factor AB</span>

alpha &lt;-<span class="st"> </span><span class="fl">0.05</span>

sigma &lt;-<span class="st"> </span>sd

m_A &lt;-<span class="st"> </span><span class="dv">2</span> <span class="co">#levels factor A</span>

variance_e_A &lt;-<span class="st"> </span>(sigma<span class="op">^</span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>rho_A) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span>sigma<span class="op">^</span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(m_A <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">*</span><span class="st"> </span>(rho_B <span class="op">-</span><span class="st"> </span>rho_AB) )
<span class="co">#Variance A</span>
variance_e_A</code></pre>
<pre><code>## [1] 5.75</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">m_B &lt;-<span class="st"> </span><span class="dv">2</span> <span class="co">#levels factor B</span>

variance_e_B &lt;-<span class="st"> </span>sigma<span class="op">^</span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>rho_B) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span>sigma<span class="op">^</span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(m_B <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">*</span><span class="st"> </span>(rho_A <span class="op">-</span><span class="st"> </span>rho_AB)
<span class="co">#Variance B</span>
variance_e_B</code></pre>
<pre><code>## [1] 5.75</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">variance_e_AB &lt;-
<span class="st">  </span>(sigma <span class="op">^</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">max</span>(rho_A, rho_B)) <span class="op">-</span><span class="st"> </span>
<span class="st">     </span>sigma <span class="op">^</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(<span class="kw">min</span>(rho_A,rho_B) <span class="op">-</span><span class="st"> </span>rho_AB)) 
<span class="co">#Variance AB</span>
variance_e_AB</code></pre>
<pre><code>## [1] 5.75</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Create a mean matrix</span>
mean_mat &lt;-<span class="st"> </span><span class="kw">t</span>(<span class="kw">matrix</span>(mu, <span class="dt">nrow =</span> m_B,<span class="dt">ncol =</span> m_A)) 
mean_mat</code></pre>
<pre><code>##      [,1] [,2]
## [1,]    2    1
## [2,]    4    2</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Potvin &amp; Schutz, 2000, formula 2, p. 348</span>
<span class="co"># For main effect A</span>
lambda_A &lt;-
<span class="st">  </span>(n <span class="op">*</span><span class="st"> </span>m_A <span class="op">*</span><span class="st"> </span><span class="kw">sum</span>((<span class="kw">rowMeans</span>(mean_mat) <span class="op">-</span><span class="st"> </span>
<span class="st">                   </span><span class="kw">mean</span>(<span class="kw">rowMeans</span>(mean_mat))) <span class="op">^</span><span class="st"> </span><span class="dv">2</span>) ) <span class="op">/</span><span class="st"> </span>variance_e_A
  lambda_A</code></pre>
<pre><code>## [1] 7.826087</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#calculate degrees of freedom 1 - ignoring the sphericity correction</span>
df1 &lt;-<span class="st"> </span>(m_A <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) 

df2 &lt;-<span class="st"> </span>(n <span class="op">-</span><span class="st"> </span>k) <span class="op">*</span><span class="st"> </span>(m_A <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="co">#calculate degrees of freedom 2</span>

F_critical &lt;-<span class="st"> </span><span class="kw">qf</span>(alpha, <span class="co"># critical F-vaue</span>
                 df1,
                 df2, 
                 <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>) 

pow_A &lt;-<span class="st"> </span><span class="kw">pf</span>(<span class="kw">qf</span>(alpha, <span class="co">#power </span>
             df1, 
             df2, 
             <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>), 
          df1, 
          df2, 
          lambda_A, 
          <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)
pow_A<span class="op">*</span><span class="dv">100</span></code></pre>
<pre><code>## [1] 75.61412</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">lambda_B &lt;-
<span class="st">  </span>n <span class="op">*</span><span class="st"> </span>m_B <span class="op">*</span><span class="st"> </span><span class="kw">sum</span>((<span class="kw">colMeans</span>(mean_mat) <span class="op">-</span><span class="st"> </span>
<span class="st">                   </span><span class="kw">mean</span>(<span class="kw">colMeans</span>(mean_mat))) <span class="op">^</span><span class="st"> </span><span class="dv">2</span>) <span class="op">/</span><span class="st"> </span>variance_e_B 
lambda_B</code></pre>
<pre><code>## [1] 7.826087</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">df1 &lt;-<span class="st"> </span>(m_B <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="co">#calculate degrees of freedom 1</span>

df2 &lt;-<span class="st"> </span>(n <span class="op">-</span><span class="st"> </span>k) <span class="op">*</span><span class="st"> </span>(m_B <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="co">#calculate degrees of freedom 2</span>

F_critical &lt;-<span class="st"> </span><span class="kw">qf</span>(alpha, <span class="co"># critical F-vaue</span>
                 df1,
                 df2,
                 <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>) 

pow_B &lt;-<span class="st"> </span><span class="kw">pf</span>(<span class="kw">qf</span>(alpha, <span class="co">#power </span>
             df1, 
             df2, 
             <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>), 
          df1, 
          df2, 
          lambda_B, 
          <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)


pow_B<span class="op">*</span><span class="dv">100</span></code></pre>
<pre><code>## [1] 75.61412</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Peform double summation courtesy of Andrew Vigotsky</span>
term &lt;-<span class="st"> </span><span class="dv">0</span>
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(mean_mat)) {
  <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">ncol</span>(mean_mat)) {
    term &lt;-<span class="st"> </span>(term <span class="op">+</span><span class="st"> </span>(mean_mat[i,j] <span class="op">-</span><span class="st"> </span>
<span class="st">                       </span><span class="kw">mean</span>(mean_mat[i,]) <span class="op">-</span><span class="st"> </span>
<span class="st">                       </span><span class="kw">mean</span>(mean_mat[,j]) <span class="op">+</span><span class="st"> </span><span class="kw">mean</span>(mean_mat))<span class="op">^</span><span class="dv">2</span>)
  }
}
term</code></pre>
<pre><code>## [1] 0.25</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Calculate lambda for interaction term</span>
lambda_AB &lt;-<span class="st"> </span>n<span class="op">*</span>term<span class="op">/</span>variance_e_AB
lambda_AB</code></pre>
<pre><code>## [1] 0.8695652</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">df1 &lt;-<span class="st"> </span>(m_A <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">*</span><span class="st"> </span>(m_B <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)  <span class="co">#calculate degrees of freedom 1</span>
df2 &lt;-
(n <span class="op">-</span><span class="st"> </span>k) <span class="op">*</span><span class="st"> </span>(m_A <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">*</span><span class="st"> </span>(m_B <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="co">#calculate degrees of freedom 2</span>
F_critical &lt;-<span class="st"> </span><span class="kw">qf</span>(alpha, <span class="co"># critical F-vaue</span>
df1,
df2,
<span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)

pow_AB &lt;-<span class="st"> </span><span class="kw">pf</span>(<span class="kw">qf</span>(alpha, <span class="co">#power</span>
df1,
df2,
<span class="dt">lower.tail =</span> <span class="ot">FALSE</span>),
df1,
df2,
lambda_AB,
<span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)

pow_AB<span class="op">*</span><span class="dv">100</span></code></pre>
<pre><code>## [1] 14.36376</code></pre>
<p>We can now compile all the analytical results into a single table, and see that the results match those from <code>ANOVA_exact</code>.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-163">Table 3.16: </span>Analytical Result
</caption>
<thead>
<tr>
<th style="text-align:right;">
variance
</th>
<th style="text-align:right;">
lambda
</th>
<th style="text-align:right;">
power
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
5.75
</td>
<td style="text-align:right;">
7.8260870
</td>
<td style="text-align:right;">
75.61412
</td>
</tr>
<tr>
<td style="text-align:right;">
5.75
</td>
<td style="text-align:right;">
7.8260870
</td>
<td style="text-align:right;">
75.61412
</td>
</tr>
<tr>
<td style="text-align:right;">
5.75
</td>
<td style="text-align:right;">
0.8695652
</td>
<td style="text-align:right;">
14.36376
</td>
</tr>
</tbody>
</table>
<p>And we can see in the simple scenario matches <code>ANOVA_exact</code> and <code>ANOVA_power</code> output.</p>
<p>Let’s now extend to one of the simlations presented by Potvin and Schultz with a 3x3 solution.</p>
<pre class="sourceCode r"><code class="sourceCode r">mu =<span class="st"> </span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">4</span>,
       <span class="dv">2</span>,.<span class="dv">5</span>,<span class="dv">3</span>,
       <span class="dv">2</span>,<span class="dv">0</span>,<span class="dv">6</span>) 
n &lt;-<span class="st"> </span><span class="dv">20</span>
sd &lt;-<span class="st"> </span><span class="dv">5</span>
r &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">1.0</span>,<span class="fl">0.8</span>,<span class="fl">0.8</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,
       <span class="fl">0.8</span>,<span class="fl">1.0</span>,<span class="fl">0.8</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,
       <span class="fl">0.8</span>,<span class="fl">0.8</span>,<span class="fl">1.0</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,
       <span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">1.0</span>,<span class="fl">0.8</span>,<span class="fl">0.8</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,
       <span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.8</span>,<span class="fl">1.0</span>,<span class="fl">0.8</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,
       <span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.8</span>,<span class="fl">0.8</span>,<span class="fl">1.0</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,
       <span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">1.0</span>,<span class="fl">0.8</span>,<span class="fl">0.8</span>,
       <span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.8</span>,<span class="fl">1.0</span>,<span class="fl">0.8</span>,
       <span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>,<span class="fl">0.8</span>,<span class="fl">0.8</span>,<span class="fl">1.0</span>)


string =<span class="st"> &quot;3w*3w&quot;</span>
alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span>

design_result &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> string,
                              <span class="dt">n =</span> n, 
                              <span class="dt">mu =</span> mu, 
                              <span class="dt">sd =</span> sd, 
                              <span class="dt">r =</span> r, 
                              <span class="dt">plot =</span> <span class="ot">TRUE</span>)</code></pre>
<p><img src="SuperpowerValidation_files/figure-html/unnamed-chunk-164-1.png" width="672" /></p>
<pre class="sourceCode r"><code class="sourceCode r">design_result<span class="op">$</span>cor_mat</code></pre>
<pre><code>##       a1_b1 a1_b2 a1_b3 a2_b1 a2_b2 a2_b3 a3_b1 a3_b2 a3_b3
## a1_b1   1.0   0.8   0.8   0.4   0.4   0.4   0.4   0.4   0.4
## a1_b2   0.8   1.0   0.8   0.4   0.4   0.4   0.4   0.4   0.4
## a1_b3   0.8   0.8   1.0   0.4   0.4   0.4   0.4   0.4   0.4
## a2_b1   0.4   0.4   0.4   1.0   0.8   0.8   0.4   0.4   0.4
## a2_b2   0.4   0.4   0.4   0.8   1.0   0.8   0.4   0.4   0.4
## a2_b3   0.4   0.4   0.4   0.8   0.8   1.0   0.4   0.4   0.4
## a3_b1   0.4   0.4   0.4   0.4   0.4   0.4   1.0   0.8   0.8
## a3_b2   0.4   0.4   0.4   0.4   0.4   0.4   0.8   1.0   0.8
## a3_b3   0.4   0.4   0.4   0.4   0.4   0.4   0.8   0.8   1.0</code></pre>
<p>The design now matches the correlation matrix in Figure 1 of Potvin and Schultz.</p>
<p>And we can estimate power with <code>ANOVA_exact</code>.</p>
<pre class="sourceCode r"><code class="sourceCode r">exact_result &lt;-<span class="st"> </span><span class="kw">ANOVA_exact</span>(design_result,
                            <span class="dt">alpha_level =</span> alpha_level,
                            <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-166">Table 3.17: </span>Exact ANOVA Result
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
power
</th>
<th style="text-align:right;">
partial_eta_squared
</th>
<th style="text-align:right;">
cohen_f
</th>
<th style="text-align:right;">
non_centrality
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
a
</td>
<td style="text-align:right;">
9.44
</td>
<td style="text-align:right;">
0.0156
</td>
<td style="text-align:right;">
0.1260
</td>
<td style="text-align:right;">
0.6032
</td>
</tr>
<tr>
<td style="text-align:left;">
b
</td>
<td style="text-align:right;">
100.00
</td>
<td style="text-align:right;">
0.7021
</td>
<td style="text-align:right;">
1.5352
</td>
<td style="text-align:right;">
89.5556
</td>
</tr>
<tr>
<td style="text-align:left;">
a:b
</td>
<td style="text-align:right;">
90.09
</td>
<td style="text-align:right;">
0.1779
</td>
<td style="text-align:right;">
0.4652
</td>
<td style="text-align:right;">
16.4444
</td>
</tr>
</tbody>
</table>
<p>Further, as we use the analytical solution below, the variance components should be equal to the corresponding MSE from the <code>ANOVA_exact</code> produced <code>anova_table</code> object.</p>
<pre class="sourceCode r"><code class="sourceCode r">exact_result<span class="op">$</span>aov_result<span class="op">$</span>anova_table</code></pre>
<pre><code>## Anova Table (Type 3 tests)
## 
## Response: y
##     num Df den Df MSE       F     pes          Pr(&gt;F)    
## a        2     38  35  0.3016 0.01563        0.741397    
## b        2     38   5 44.7778 0.70209 0.0000000001018 ***
## a:b      4     76   5  4.1111 0.17788        0.004542 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">k &lt;-<span class="st"> </span><span class="dv">1</span> <span class="co">#one group (because all factors are within)</span>

rho_A &lt;-<span class="st"> </span><span class="fl">.4</span> <span class="co">#mean r for factor A</span>

rho_B &lt;-<span class="st"> </span><span class="fl">.8</span> <span class="co">#mean r for factor B</span>

rho_AB &lt;-<span class="st"> </span><span class="fl">.4</span> <span class="co">#mean r for factor AB</span>

alpha &lt;-<span class="st"> </span><span class="fl">0.05</span>

sigma &lt;-<span class="st"> </span>sd

m_A &lt;-<span class="st"> </span><span class="dv">3</span> <span class="co">#levels factor A</span>

variance_e_A &lt;-<span class="st"> </span>sigma<span class="op">^</span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>rho_A) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span>sigma<span class="op">^</span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(m_A <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">*</span><span class="st"> </span>(rho_B <span class="op">-</span><span class="st"> </span>rho_AB) 
<span class="co">#Variance A</span>
variance_e_A</code></pre>
<pre><code>## [1] 35</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">m_B &lt;-<span class="st"> </span><span class="dv">3</span> <span class="co">#levels factor B</span>

variance_e_B &lt;-<span class="st"> </span>sigma<span class="op">^</span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>rho_B) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span>sigma<span class="op">^</span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(m_B <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">*</span><span class="st"> </span>(rho_A <span class="op">-</span><span class="st"> </span>rho_AB)
<span class="co">#Variance B</span>
variance_e_B</code></pre>
<pre><code>## [1] 5</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">variance_e_AB &lt;-
<span class="st">  </span>(sigma <span class="op">^</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">max</span>(rho_A, rho_B)) <span class="op">-</span><span class="st"> </span>
<span class="st">     </span>sigma <span class="op">^</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(<span class="kw">min</span>(rho_A,rho_B) <span class="op">-</span><span class="st"> </span>rho_AB)) 
<span class="co">#Variance AB</span>
variance_e_AB</code></pre>
<pre><code>## [1] 5</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Create a mean matrix</span>
mean_mat &lt;-<span class="st"> </span><span class="kw">t</span>(<span class="kw">matrix</span>(mu, <span class="dt">nrow =</span> m_B,<span class="dt">ncol =</span> m_A)) 
mean_mat</code></pre>
<pre><code>##      [,1] [,2] [,3]
## [1,]    2  1.0    4
## [2,]    2  0.5    3
## [3,]    2  0.0    6</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Potvin &amp; Schutz, 2000, formula 2, p. 348</span>
<span class="co"># For main effect A</span>
lambda_A &lt;-
<span class="st">  </span>(n <span class="op">*</span><span class="st"> </span>m_A <span class="op">*</span><span class="st"> </span><span class="kw">sum</span>((<span class="kw">rowMeans</span>(mean_mat) <span class="op">-</span><span class="st"> </span>
<span class="st">                   </span><span class="kw">mean</span>(<span class="kw">rowMeans</span>(mean_mat))) <span class="op">^</span><span class="st"> </span><span class="dv">2</span>) ) <span class="op">/</span><span class="st"> </span>variance_e_A
  lambda_A</code></pre>
<pre><code>## [1] 0.6031746</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#calculate degrees of freedom 1 - ignoring the sphericity correction</span>
df1 &lt;-<span class="st"> </span>(m_A <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) 

df2 &lt;-<span class="st"> </span>(n <span class="op">-</span><span class="st"> </span>k) <span class="op">*</span><span class="st"> </span>(m_A <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="co">#calculate degrees of freedom 2</span>

F_critical &lt;-<span class="st"> </span><span class="kw">qf</span>(alpha, <span class="co"># critical F-vaue</span>
                 df1,
                 df2, 
                 <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>) 

pow_A &lt;-<span class="st"> </span><span class="kw">pf</span>(<span class="kw">qf</span>(alpha, <span class="co">#power </span>
             df1, 
             df2, 
             <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>), 
          df1, 
          df2, 
          lambda_A, 
          <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)
pow_A<span class="op">*</span><span class="dv">100</span></code></pre>
<pre><code>## [1] 9.441726</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">lambda_B &lt;-
<span class="st">  </span>n <span class="op">*</span><span class="st"> </span>m_B <span class="op">*</span><span class="st"> </span><span class="kw">sum</span>((<span class="kw">colMeans</span>(mean_mat) <span class="op">-</span><span class="st"> </span>
<span class="st">                   </span><span class="kw">mean</span>(<span class="kw">colMeans</span>(mean_mat))) <span class="op">^</span><span class="st"> </span><span class="dv">2</span>) <span class="op">/</span><span class="st"> </span>variance_e_B 
lambda_B</code></pre>
<pre><code>## [1] 89.55556</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">df1 &lt;-<span class="st"> </span>(m_B <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="co">#calculate degrees of freedom 1</span>

df2 &lt;-<span class="st"> </span>(n <span class="op">-</span><span class="st"> </span>k) <span class="op">*</span><span class="st"> </span>(m_B <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="co">#calculate degrees of freedom 2</span>

F_critical &lt;-<span class="st"> </span><span class="kw">qf</span>(alpha, <span class="co"># critical F-vaue</span>
                 df1,
                 df2,
                 <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>) 

pow_B &lt;-<span class="st"> </span><span class="kw">pf</span>(<span class="kw">qf</span>(alpha, <span class="co">#power </span>
             df1, 
             df2, 
             <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>), 
          df1, 
          df2, 
          lambda_B, 
          <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)


pow_B<span class="op">*</span><span class="dv">100</span></code></pre>
<pre><code>## [1] 100</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Peform double summation courtesy of Andrew Vigotsky</span>
term &lt;-<span class="st"> </span><span class="dv">0</span>
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(mean_mat)) {
  <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">ncol</span>(mean_mat)) {
    term &lt;-<span class="st"> </span>((term <span class="op">+</span><span class="st"> </span>(mean_mat[i,j] <span class="op">-</span>
<span class="st">                        </span><span class="kw">mean</span>(mean_mat[i,]) <span class="op">-</span><span class="st"> </span>
<span class="st">                        </span><span class="kw">mean</span>(mean_mat[,j]) <span class="op">+</span><span class="st"> </span><span class="kw">mean</span>(mean_mat))<span class="op">^</span><span class="dv">2</span>))
  }
}
term</code></pre>
<pre><code>## [1] 4.111111</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Calculate lambda for interaction term</span>
lambda_AB &lt;-<span class="st"> </span>n<span class="op">*</span>term<span class="op">/</span>variance_e_AB
lambda_AB</code></pre>
<pre><code>## [1] 16.44444</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">df1 &lt;-<span class="st"> </span>(m_A <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">*</span><span class="st"> </span>(m_B <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)  <span class="co">#calculate degrees of freedom 1</span>
df2 &lt;-
(n <span class="op">-</span><span class="st"> </span>k) <span class="op">*</span><span class="st"> </span>(m_A <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">*</span><span class="st"> </span>(m_B <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="co">#calculate degrees of freedom 2</span>
F_critical &lt;-<span class="st"> </span><span class="kw">qf</span>(alpha, <span class="co"># critical F-vaue</span>
df1,
df2,
<span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)

pow_AB &lt;-<span class="st"> </span><span class="kw">pf</span>(<span class="kw">qf</span>(alpha, <span class="co">#power</span>
df1,
df2,
<span class="dt">lower.tail =</span> <span class="ot">FALSE</span>),
df1,
df2,
lambda_AB,
<span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)

pow_AB<span class="op">*</span><span class="dv">100</span></code></pre>
<pre><code>## [1] 90.09263</code></pre>
<p>Again, when we compile all the analytical results into a single table we can see that the results match those from <code>ANOVA_exact</code>.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-170">Table 3.18: </span>Analytical Result
</caption>
<thead>
<tr>
<th style="text-align:right;">
variance
</th>
<th style="text-align:right;">
lambda
</th>
<th style="text-align:right;">
power
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
35
</td>
<td style="text-align:right;">
0.6031746
</td>
<td style="text-align:right;">
9.441726
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
89.5555556
</td>
<td style="text-align:right;">
100.000000
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
16.4444444
</td>
<td style="text-align:right;">
90.092634
</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="one-way-anova.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="mixed-anova.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["SuperpowerValidation.pdf", "SuperpowerValidation.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
